### ISSUE TITLE
7.12 documentation: Mark this 'fix' as breaking change

### ISSUE THREAD

**Issue by bartrikers** [mendix/docs#1053]
Hi,

In the [7.12 documentation](https://github.com/mendix/docs/blob/development/content/releasenotes/desktop-modeler/7.12.md) this 'fix' is mentioned:

![afbeelding](https://user-images.githubusercontent.com/23105910/37149148-405fd754-22cd-11e8-804a-e976174faeff.png)

but since this a fundamentally different way of using css in widgets imo, this is not a fix, but a change, and should be included in the breaking change section, as this could break some custom widgets.

See for example this issue on the forum: https://forum.mendixcloud.com/link/questions/89151

Kind regards,
Bart Rikers

**Comment by Adam-Dupaski** [comment]
Hi @bartrikers , I have coordinated with the developers who wrote this release note and they decided the note should be left in the Fixes section but should be expanded. The note has been updated:

https://docs.mendix.com/releasenotes/desktop-modeler/7.12#fixes

This update fixes this issue. Please let me know if you have any further questions. Thanks,
Adam
