### ISSUE TITLE
Want a local build for mobile applications for iOS and Android

### ISSUE THREAD

**Issue by isamu-tanaka** [mendix/docs#1097]
There are some blog sites for a local build for mobile applications for iOS and Android.
However, those are based on old PhoneGap library.  We want documents of a local build for mobile applications for iOS and Android

**Comment by ConnorLand** [comment]
Hi @isamu-tanaka , 

To build locally for iOS and Android, the **Build and run locally** section of the _Mendix PhoneGap Build App Template_ might give you the information you need. https://github.com/mendix/hybrid-app-template/blob/master/README.md

Does the information in that section address your use case? If not, could you please give me more context on your situation? 

Thank you,
Connor
