### ISSUE TITLE
Windows deployment guide missing important security setting

### ISSUE THREAD

**Issue by tieniber** [mendix/docs#110]
Per [this discussion](https://forum.mendixcloud.com/link/questions/86039) on the forums, I think the rewrite rules section in [Deploying Mendix on Microsoft WIndows](https://docs.mendix.com/howto50/deploying-mendix-on-microsoft-windows) needs to be updated to include setting a server variable / http header that is recommended in [Security Checklist for your On-Premises Installation](https://docs.mendix.com/howto50/security-checklist-for-your-on-premises-installation).

I'm still awaiting a positive response on the forum but wanted to note it here before I forget.

**Comment by Adam-Dupaski** [comment]
Hi Eric, after you get verification from Paul on your forum answer, please update the documentation with what's necessary and send a pull request for us to review. This should be done for the how-to in versions 5-7 if relevant. Thanks.

**Comment by tieniber** [comment]
Ok, this answer was confirmed working. It apparently requires setting up a URL rewrite rule at the _server_ level rather than at the _site_ level. I don't have an instance of IIS to step through the process and take good screenshots. I may have one available to me in 2-3 weeks.

**Comment by Adam-Dupaski** [comment]
Thanks for the update, Eric. Please keep me posted about updating the documentation when you have an environment available.

**Comment by jandevriesmendix** [comment]
Any updates on this?

**Comment by Adam-Dupaski** [comment]
Hi, I believe this has been taken care of here: https://docs.mendix.com/developerportal/deploy/deploy-mendix-on-microsoft-windows#5-4-2-rule-add-x-forwarded-proto-header
@tieniber please let me know if there's something missing
