### ISSUE TITLE
Link on the SDK page leads to nowhere

### ISSUE THREAD

**Issue by vjb** [mendix/docs#1198]
![sdk-page-button](https://user-images.githubusercontent.com/6693590/40550669-c7b3ae06-6008-11e8-9b7a-24ee1def8fb3.PNG)

The "Step by Step Tutorial" button leads to nowhere, instead of: https://docs.mendix.com/apidocs-mxsdk/mxsdk/setting-up-your-development-environment, which is the intention (I think).

**Comment by Adam-Dupaski** [comment]
Thanks for registering this issue, @vjb. However, this is not a documentation issue, this is an issue with that SDK page, which has a different owner. I am closing this issue and will pursue this via email.
