### ISSUE TITLE
Create a Custom Save Button doc page not relevant

### ISSUE THREAD

**Issue by florentbo** [mendix/docs#128]
Hi
We just tried to make our first "Custom Save Button".
But the action "Right click the Cancel button and select Add button left > Microflow" is not possible at all in the Mendix Modeller 6.8.1

**Comment by jandevriesmendix** [comment]
Hi Florent,
The custom save button how-to has been updated for Mendix 6.9.1.

Regards,
Jan de Vries

**Comment by florentbo** [comment]
![mendix](https://cloud.githubusercontent.com/assets/2943414/22734163/0b08b16a-edf5-11e6-94fa-03283254dc68.jpg)
This is Business Modeler 6.10.1 and this is not working

**Comment by jandevriesmendix** [comment]
Hi Florent,
The how-to has been updated with new information, it's available here https://docs.mendix.com/howto6/create-a-custom-save-button.

**Comment by florentbo** [comment]
Hi Jan,
Thank you for your quick reaction

**Comment by jandevriesmendix** [comment]
No problem. Good luck developing!
