### ISSUE TITLE
Update how-to: Consume a complex webservice

### ISSUE THREAD

**Issue by JelteMX** [mendix/docs#1316]
Related to #1304, the links were updated. One how-to needs to be rewritten:

**/howto/integration/consume-a-complex-web-service** uses the following link as an example (including the images and follow-up steps):

http://www.webservicex.net/medicareSupplier.asmx?WSDL

Unfortunately, this one is no longer valid. A new link needs to be found and the steps need to be updated.

**Comment by Adam-Dupaski** [comment]
Fixed
