### ISSUE TITLE
Broken external links 2019-02-13

### ISSUE THREAD

**Issue by JelteMX** [mendix/docs#1513]
The following errors have occurred in the last external links check.

We should check the links for these pages, replace/delete them:

======= Errors

File: **/apidocs-mxsdk/mxsdk/setting-up-your-development-environment.html** has the following errors:

   + Has broken link to http://windows.microsoft.com/en-us/windows/command-prompt-faq

File: **/apidocs-mxsdk/mxsdk/working-with-when.js-and-promises-in-typescript.html** has the following errors:

   + Has broken link to http://recurial.com/programming/understanding-callback-functions-in-javascript/

File: **/howto50/selenium-support.html** has the following errors:

   + Has broken link to https://addons.mozilla.org/nl/firefox/addon/firebug/

File: **/howto6/selenium-support.html** has the following errors:

   + Has broken link to https://addons.mozilla.org/nl/firefox/addon/firebug/

File: **/howto/integration/selenium-support.html** has the following errors:

   + Has broken link to https://addons.mozilla.org/nl/firefox/addon/firebug/

File: **/howto/testing/testing-mendix-applications-using-selenium-ide.html** has the following errors:

   + Has broken link to https://addons.mozilla.org/en-US/firefox/addon/firebug/
   + Has broken link to https://addons.mozilla.org/en-US/firefox/addon/firepath/

File: **/ats/howtos/ht-version-2/custom-action-helpful-resources-2.html** has the following errors:

   + Has broken link to https://chrome.google.com/webstore/detail/jquery-selector-helper/fgnjfdfdoeonimejccacdgananeckabl

**Comment by Adam-Dupaski** [comment]
I'll take a look.

**Comment by Adam-Dupaski** [comment]
Fixed broken links.
