### ISSUE TITLE
Push Notification documentation error

### ISSUE THREAD

**Issue by tieniber** [mendix/docs#1537]
In [this](https://docs.mendix.com/howto/mobile/setting-up-apple-push-notification-server) article about setting up APNS, it states:

> Choose a topic for the new configuration (you can freely choose one)

In testing, when we specified a topic here, we received an error from APNS stating "Topic disallowed". Leaving the topic field empty worked for us.

**Comment by Adam-Dupaski** [comment]
Hi, I added the extra info. Please note that sending a PR for such an update might be more efficient. Thanks.
