### ISSUE TITLE
Mendix and IBM Watson integration 

### ISSUE THREAD

**Issue by Andrewchu50** [mendix/docs#1570]
Hi,

I am having a tough time integrating the IBM Watson chatbot on my Mendix landing page. Is there any way I can get some help with this?. Thanks.

**Comment by Adam-Dupaski** [comment]
Hi Andrew, the best thing you can do to get help outside of referring to the documentation is to post a question on the Mendix Forum: https://forum.mendixcloud.com/index4.html. The Mendix community is very active there and is sure to help you if you explain your scenario and what you are trying to accomplish.
Cheers,
Adam

**Comment by Adam-Dupaski** [comment]
Just to verify - have you checked this documentation?: https://docs.mendix.com/refguide/ibm/ibm-watson-connector#WatsonAssistant
