### ISSUE TITLE
Debug Native Custom Widget

### ISSUE THREAD

**Issue by vietduc1441** [mendix/docs#1638]
I am a newbie in React Native!

I am following the following links:
https://docs.mendix.com/howto/mobile/getting-started-with-native-mobile
and 
https://docs.mendix.com/howto/extensibility/pluggable-widgets
So now I can create my custom native widget and can see it on my physical IPhone (not Simulator)
However, if i want to debug my script, it is not straightforward how to do it.
Could you add a section to clarify the way to debug?
(If possible, how to see my app on Simulator install on my PC also, it is not really convenient to use my phone all the time)

**Comment by ConnorLand** [comment]
We are outlining some widget debug documentation now. Thank you for your comment.

**Comment by ConnorLand** [comment]
Hi @vietduc1441 ,

I'm sorry for the long delay on this. We have some more documentation and tech to help fix your issue. Specifically, we have an element inspector which helps speed up native widget debugging. You can find the details in the [Debugging Your Styling]([https://docs.mendix.com/howto/mobile/native-debug#3-debugging-your-styling] section of _Debug Native Apps_.

If you wish to use an emulator for Android mobile testing, install a product such as Bluestacks or Genymotion (your emulator must have Google Play services supported).

I hope this speeds up your debugging. Can I help you with anything else?

Connor
