### ISSUE TITLE
APM port in documentation seems incorrect

### ISSUE THREAD

**Issue by feddovanede** [mendix/docs#1782]
https://docs.mendix.com/apm/installation-guide/ig-2/installation-2#4-security it says:
> The agent initiates all communication to the APM 2 manager in HTTPS over port 80.

HTTPS over port 80 isn't very common. Given that the APM 2 Manager runs in the Mendix Cloud, I would expect this to be port 443.

**Comment by Adam-Dupaski** [comment]
@gajduk-mansystems Hi Andrej, are you able to confirm whether this should be port 443 instead of port 80 for APM?
Thanks,
Adam

**Comment by Adam-Dupaski** [comment]
Verified with Bart that it should be 443.
