### ISSUE TITLE
'Set up Gulp & Sass' does not take beta3 changes into account

### ISSUE THREAD

**Issue by reinouts** [mendix/docs#1799]
https://docs.mendix.com/howto/front-end/set-up-sass does not mention the new location of SASS source files in` theme/styles/web/sass`. Please have the UX people update this.

**Comment by ConnorLand** [comment]
Hi @reinouts . I have updated the doc's file pathways to reflect the new structure. I have also updated a few screenshots to reflect this. Thank you.
