### ISSUE TITLE
Native Styling Refguide missing Layout Grid

### ISSUE THREAD

**Issue by tieniber** [mendix/docs#2363]
We need styling documentation for the layout grid!

**Comment by ConnorLand** [comment]
Good tip @tieniber. Are you familiar enough with Layout Grid to PR your own new Layout Grid section, or should I ask someone else in R&D? You can see that the section formula in that doc is consistent and simple.

**Comment by tieniber** [comment]
I am not unfortunately. I went looking for the documentation to try and
figure it out!

**Comment by ConnorLand** [comment]
Ok no problem. I'll find a developer who can PR it. Thanks!

**Comment by ConnorLand** [comment]
Wesley has made a story for this. Thanks!

**Comment by ConnorLand** [comment]
This info has just been committed to the docs.
