### ISSUE TITLE
Private Cloud Operator Documentation missing MicroflowConstants (Mendix Constant) configuration

### ISSUE THREAD

**Issue by tieniber** [mendix/docs#2432]
The example in this section doesn't cover how to set constants. There's a key called MicroflowConstants, which is missing here:

https://github.com/mendix/docs/blob/development/content/developerportal/deploy/private-cloud-operator.md#32-editing-the-credit-cr

**Comment by MarkvanMents** [comment]
The documentation does say that _**all** custom Mendix Runtime parameters go here,_ which implies that we haven't included every single possibility.

Asked development team on Slack what is reasonable to document.

**Comment by tieniber** [comment]
MicroflowConstants isn’t a documented custom runtime setting so I had to
ask the team what to put here:

https://docs.mendix.com/refguide/custom-settings#1-custom-runtime-settings

Plus, every mendix app uses constants and they must be set, so it should be
in the sample.

**Comment by MarkvanMents** [comment]
Hi Eric,
I've spoken with the development team and they agree that there should be something about constants in here - and will be drafting something for me to publish this week.
Thanks for the feedback.
I'll keep this issue open until I've published the new documentation.

**Comment by MarkvanMents** [comment]
Hi Eric,
The documentation is written but is combined with some other changes which are awaiting review.
You can see the information in this PR #2488 and it will be published by the end of the week at the latest.

**Comment by MarkvanMents** [comment]
Hi Eric,
Just to let you know that the documentation has now been published and you can find it here. https://docs.mendix.com/developerportal/deploy/private-cloud-operator#set-app-constants
Hope it covers everything you were looking for.
Yours
Mark

**Comment by MarkvanMents** [comment]
I'll close this issue now, but feel free to raise further issues or Pull Requests if you see anything that needs changing.
Mark
