### ISSUE TITLE
Configuration instructions could be improved

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#2553]
This is a great module but on more than one occasion I have struggled because the page I linked to wasn't the one I needed. 
The instructions for configuration (Section 3 in the documentation) advise us to link to Templates_Overview page.  
In fact the page I always want is ExcelImporter.ExcelImportOverview. 
It may depend on what you are trying to achieve but for many people this is used primarily for importing reference data where the template set-up and import will be done at the same time. 
Perhaps both pages should be referenced?

**Comment by Adam-Dupaski** [comment]
Thanks @Chris-Karona, I've added that page to the section.
