### ISSUE TITLE
Typo in mx.data.getOffline operator value

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/docs#2595]
Hi,

I noticed a typo in the Mendix 8 client API documentation for the operator values for getOffline in the mx.data package, It says _greatherThan_, additional _h_ in _greater_.

I wanted to create a pull request for it but I can only find the client API docs submenu, where the main versions are listed.

With regards,

Marcel

**Comment by Andries-Smit** [comment]
@mgroeneweg Docs of the API are auto generated based on the comments in the Mendix code base (which is not public). So it is not possible to open a PR. Front end dev team can change this.

**Comment by Adam-Dupaski** [comment]
@ConnorLand please take a look at this and talk to the team about this change.

**Comment by ConnorLand** [comment]
Will do. Thank you @mgroeneweg and @Andries-Smit .

**Comment by ConnorLand** [comment]
Mitya was already aware of the issue. It is fixed in this MR, which should go through before 8.14 https://gitlab.rnd.mendix.com/appdev/appdev/merge_requests/5428

Thanks all!
