### ISSUE TITLE
Link broken in section 7, private cloud of deployment guide

### ISSUE THREAD

**Issue by fintanr** [mendix/docs#2613]
In https://github.com/mendix/docs/blob/development/content/developerportal/deploy/index.md

the link to private-cloud.md is broken, see diff below

diff --git a/content/developerportal/deploy/index.md b/content/developerportal/deploy/index.md
index a859f1823..56bcefc79 100644
--- a/content/developerportal/deploy/index.md
+++ b/content/developerportal/deploy/index.md
@@ -57,7 +57,7 @@ To find out how to do this, read [Siemens MindSphere](deploying-to-mindsphere).
 
 Mendix for Private Cloud allows you to deploy and manage your Mendix apps in a Kubernetes private cloud cluster.
 
-The instructions for doing this are in [Private Cloud}(private-cloud).
+The instructions for doing this are in [Private Cloud](private-cloud).
 
 ## 8 Cloud Foundry

**Comment by Adam-Dupaski** [comment]
Thanks @fintanr, I made the fix: https://github.com/mendix/docs/commit/d22d36b70641e55766eaad900f361db853cc9a63
