### ISSUE TITLE
Incorrect link in JavaScript Best Practices

### ISSUE THREAD

**Issue by Ixxith** [mendix/docs#2945]
In Studio 8 Pro guides, under JavaScript best practices 2.2.1, the Client API links to version 7 rather than version 8 of the client API.

Link to page section: https://docs.mendix.com/howto/extensibility/best-practices-javascript-actions#2-2-coding-the-actions

Incorrect link: https://apidocs.rnd.mendix.com/7/client/index.html
Correct link: https://apidocs.rnd.mendix.com/8/client/index.html

**Comment by Adam-Dupaski** [comment]
Thanks for pointing this out @Ixxith - I've made the fix here: https://github.com/mendix/docs/commit/c78581c413c191e3074ac9f773f2fdb9d9faa85e
Cheers,
Adam
