### ISSUE TITLE
Build a Pluggable Web Widget: Part 2

### ISSUE THREAD

**Issue by HeikoOsigus** [mendix/docs#2958]
In Chapter 3.5 Adding Accessibility 
in the first Step: the user should add in "TextBox.tsx" 
`id={this.props.id}`
but this.props.id does not exist - it must be 
`this.props.name`

![image](https://user-images.githubusercontent.com/12611406/102607067-f8491080-4127-11eb-8e5a-9c0989aaf466.png)

**Comment by ConnorLand** [comment]
Hello Heiko,

Thank you for commenting on this issue for us. Our developers are currently working on the issue and a fix is forthcoming. I will update this issue when their fix has been published.

Connor

**Comment by diego-antonelli** [comment]
Hi @HeikoOsigus,

The Pluggable widgets tools v8.18.0 now includes the id for properties marked as labeled.

Please take a look at -> https://github.com/mendix/widgets-resources/releases/tag/pluggable-widgets-tools-8.18.0

Regards
Diego
