### ISSUE TITLE
error in "Setup error handling"

### ISSUE THREAD

**Issue by WimStevens** [mendix/docs#3033]
Section 4.3 Error Handling – Custom without Rollback

The example does not look correct
![image](https://user-images.githubusercontent.com/28532368/106387066-47958880-63d8-11eb-9b74-f662367cc7e3.png)
At step 3 the order must be present.  It has been committed and we are in the situation "custom without rollback"
I just attended the training.  In the syllabus the example is correct.

**Comment by Adam-Dupaski** [comment]
Thanks @WimStevens I've made the correction via the above commit.
