### ISSUE TITLE
No access to the Android MiN apk

### ISSUE THREAD

**Issue by x4g** [mendix/docs#3092]
Cannot get dropbox access for the Android Make it native apk mentioned in the [official doc page](https://docs.mendix.com/refguide/getting-the-make-it-native-app#2-1-android)

**Comment by ConnorLand** [comment]
Hi @x4g ,

I checked the links and the APK file downloads for me successfully. I notice you are located in Shanghai? I believe major parts of Dropbox website and servers are blocked in China by the great firewall. Do you think this might be the issue?

Thank you,

Connor
