### ISSUE TITLE
Error on compilation using community commons

### ISSUE THREAD

**Issue by rafaelsauzlmc** [mendix/docs#3122]
In my project I updated the community commons, and then I get the error bellow when try to deploy in my local environment.

Are there some workaround to avoid this error in the compilation?

Buildfile: C:\Users\rafael.carvalho\Documents\Mendix\.......-main_2\deployment\build_core.xml

compile:
    [javac] Compiling 615 source files to C:\Users\rafael.carvalho\Documents\Mendix\......-main_2\deployment\run\bin
    [javac] C:\Users\rafael.carvalho\Documents\Mendix\.....-main_2\javasource\communitycommons\StringUtils.java:313: error: method randomAlphanumeric in class RandomStringUtils cannot be applied to given types;
    [javac] 		String totalChars = RandomStringUtils.randomAlphanumeric(minLen - fixedNumber, maxLen - fixedNumber);
    [javac] 		                                     ^
    [javac]   required: int
    [javac]   found: int,int
    [javac]   reason: actual and formal argument lists differ in length
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: C:\Users\rafael.carvalho\Documents\Mendix\........-main_2\javasource\saml20\implementation\common\MendixUtils.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED
C:\Users\rafael.carvalho\Documents\Mendix\.......-main_2\deployment\build_core.xml:29: Compile failed; see the compiler error output for details.

Total time: 13 seconds

**Comment by Adam-Dupaski** [comment]
Hi Rafael, this channel is for feedback on the Mendix documentation. For your issue, I would recommend posting to the Mendix Forum https://forum.mendixcloud.com/index3.html or sending a Support ticket https://support.mendix.com/hc/en-us.
Thanks,
Adam
