### ISSUE TITLE
Does number of "Reduce number of in use session objects" apply to native apps 

### ISSUE THREAD

**Issue by mjaferDo** [mendix/docs#3128]
The following link talks about the web clients and the need to reduce number of session objects.
Does any of this apply to Native Mobile and PWA apps?

https://docs.mendix.com/howto/general/minimize-number

**Comment by smarki** [comment]
Hi @mjaferDo,
It indeed applies to any of the platforms Mendix is running on. 

We will update the documentation to reflect that. 

Regards
