### ISSUE TITLE
Missing documentation regarding datetime special tokens

### ISSUE THREAD

**Issue by dan-covaliu** [mendix/docs#3161]
Tokens representing special moments like [%BeginOfCurrentDay%], [%EndOfCurrentWeekUTC%], etc., are not documented in the **Docs/Studio (Pro) X Guide/App Modeling/Application Logic/Expressions** chapter - or anywhere else for that matter.
This applies to documentation back to at least Mendix 6

![image](https://user-images.githubusercontent.com/16047546/112349572-39a90900-8c9f-11eb-9167-ef357ecfbd66.png)

**Comment by RCatersels** [comment]
They can be found here: https://docs.mendix.com/refguide/xpath-keywords-and-system-variables

**Comment by dan-covaliu** [comment]
Thanks @RCatersels! However, that page is not reachable by searching the Mendix documentation for terms like "BeginOfCurrent" (while other pages are!)
![image](https://user-images.githubusercontent.com/16047546/112642918-28383c00-8e1a-11eb-85b3-f73bb5f3b3ec.png)

**Comment by RCatersels** [comment]
Yes, the search function is for certain searches quite bad.... Might be something todo with the name of those keywords.
