### ISSUE TITLE
Build a Pluggable Native Widget - Errors in Code Snippets for 8.18.3

### ISSUE THREAD

**Issue by neiho** [mendix/docs#3163]
Hi, 

I'm using Mendix 8.18.3 to do the [Build a Pluggable Native Widget How To](https://docs.mendix.com/howto8/extensibility/build-native-widget). The following two code snippets can't be replicated due to either missing resources or erroneous code despite copy pasting the code snippets.

I'm aware that the [prerequisites ](https://docs.mendix.com/howto8/extensibility/build-native-widget#2-prerequisites) ask for Mendix 8.3, but the same issues exist in the [docs for Mendix 9](https://docs.mendix.com/howto/extensibility/build-native-widget) where it is only stated to install the latest version of Mendix Studio Pro. So the docs should be updated either way.

[3.3.6](https://docs.mendix.com/howto8/extensibility/build-native-widget#3-3-6-adding-an-expand-and-collapse-icon-property)

`import { Style, flattenStyles } from "./utils/common";`

The module ./ultils can't be found which will result in a compilation error. I suspect that this module was part of an earlier build, but is not included anymore by the latest Mendix Widget Generator. 

[3.3.8](https://docs.mendix.com/howto8/extensibility/build-native-widget#3-3-8-adding-a-custom-default-style)

```
import shadeblendconvert from "../core/helpers/_functions/shadeblendconvert";

export const com_mendix_widget_native_groupbox_GroupBox = {
    header: {
        backgroundColor: shadeblendconvert(0.4, brand.primary)
    }
};
```

Will not work since theme\styles\native\core\helpers\_functions\shadeblendconvert.js has been updated. The tutorial used [this version](https://github.com/mendix/native-group-box-pluggable-widget-sample/blob/master/test/MxTestProject/theme/styles/native/core/helpers/_functions/shadeblendconvert.js), whereas the latest shadeblendconvert.js looks like this: 

```
export function shadeBlendConvert(c, fromValue, toValue = undefined) {
    if (typeof c != "number" ||
        c < -1 ||
        c > 1 ||
        typeof fromValue != "string" ||
        (fromValue[0] != "r" && fromValue[0] != "#") ||
        (toValue && typeof toValue != "string"))
        return "red"; //ErrorCheck
    const sbcRip = (value) => {
        const l = value.length, RGB = [];
        if (l > 9) {
            const d = value.split(",");
            if (d.length < 3 || d.length > 4)
                return null; //ErrorCheck
            (RGB[0] = i(d[0].split("(")[1])),
                (RGB[1] = i(d[1])),
                (RGB[2] = i(d[2])),
                (RGB[3] = d[3] ? parseFloat(d[3]) : -1);
        }
        else {
            let hex = "";
            if (l == 8 || l == 6 || l < 4)
                return null; //ErrorCheck
            if (l == 4 || l == 5)
                hex = "#" + value[1] + value[1] + value[2] + value[2] + value[3] + value[3] + (l > 4 ? value[4] + "" + value[4] : ""); //3 or 4 digit
            let d = i(hex.slice(1), 16);
            RGB[0] = (d >> 16) & 255;
            RGB[1] = (d >> 8) & 255;
            RGB[2] = d & 255;
            RGB[3] = -1;
            if (l == 9 || l == 5) {
                RGB[3] = r((RGB[2] / 255) * 10000) / 10000;
                RGB[2] = RGB[1];
                RGB[1] = RGB[0];
                RGB[0] = (d >> 24) & 255;
            }
        }
        return RGB;
    };
    let i = parseInt, r = Math.round, th = fromValue.length > 9, h = typeof toValue == "string" ? (toValue.length > 9 ? true : toValue == "c" ? !th : false) : th, b = c < 0, p = b ? c * -1 : c, to = toValue && toValue != "c" ? toValue : b ? "#000000" : "#FFFFFF", f = sbcRip(fromValue), t = sbcRip(to);
    if (!f || !t)
        return "red"; //ErrorCheck
    if (h)
        return ("rgb" +
            (f[3] > -1 || t[3] > -1 ? "a(" : "(") +
            r((t[0] - f[0]) * p + f[0]) +
            "," +
            r((t[1] - f[1]) * p + f[1]) +
            "," +
            r((t[2] - f[2]) * p + f[2]) +
            (f[3] < 0 && t[3] < 0
                ? ")"
                : "," +
                    (f[3] > -1 && t[3] > -1 ? r(((t[3] - f[3]) * p + f[3]) * 10000) / 10000 : t[3] < 0 ? f[3] : t[3]) +
                    ")"));
    else
        return ("#" +
            (0x100000000 +
                r((t[0] - f[0]) * p + f[0]) * 0x1000000 +
                r((t[1] - f[1]) * p + f[1]) * 0x10000 +
                r((t[2] - f[2]) * p + f[2]) * 0x100 +
                (f[3] > -1 && t[3] > -1
                    ? r(((t[3] - f[3]) * p + f[3]) * 255)
                    : t[3] > -1
                        ? r(t[3] * 255)
                        : f[3] > -1
                            ? r(f[3] * 255)
                            : 255))
                .toString(16)
                .slice(1, f[3] > -1 || t[3] > -1 ? undefined : -2));
}
```

However, even if you properly address this updated function, it fails to convert the passed color code and does not set the create the transparency.

**Comment by ConnorLand** [comment]
We are working on addressing the code issues in this doc now.

**Comment by ConnorLand** [comment]
Thank you for your feedback. We have recently completed [an overhaul](https://github.com/mendix/docs/pull/5763) of that document which solves your issues and adds a few more improvements.

These same improvements will soon be duplicated to the Mx9 version of the document as well.
