### ISSUE TITLE
Is there a starter app called "Mendix Design System"?

### ISSUE THREAD

**Issue by tingzilla** [mendix/docs#3222]
I am reading the documentation here: https://docs.mendix.com/howto/front-end/create-a-company-design-system

The first paragraph of section 2 says "Create a new app based on the Mendix Design System app". 

I cannot find an app called Mendix Design System either in the App store or in the list of starter apps available when I create a new app.

Does this app exist? Where can I find it?

**Comment by ConnorLand** [comment]
Hi @tingzilla . 

This app will be available in the future, but it is not online yet. I will delete this mention from the documentation now, and replace that content when the app is live.

Thank you for contributing to the documentation,

Connor
