### ISSUE TITLE
"Debug a Hybrid Mobile App" some type-Os in 3.1

### ISSUE THREAD

**Issue by BuzzyLizzy** [mendix/docs#3266]
3.1 macOS Configuration
Since Mendix Studio Pro only runs on ----Mendix---- (should be **Windows**), you need to make sure that your virtual (Windows) machine can be accessed by the outside world. To do that, the network setting ----much---- (should be **must**) be shared between the virtual machine and your Mac, and the appropriate ports forwarded.

**Comment by ConnorLand** [comment]
Thank you for your contribution to the documentation. I have made the changes.
