### ISSUE TITLE
native mobile styling guide describes structures in xml instead of JS

### ISSUE THREAD

**Issue by NicolasBRUNAUD** [mendix/docs#3379]
https://docs.mendix.com/refguide/native-styling-refguide

i don't understand why the description of the widgets styles are formatted in xml and not JS. 
Can we make any use of this XML version ?

why not sharing it formatted in js  as a snippet to be directly used ?

For example : carousel
https://docs.mendix.com/refguide/native-styling-refguide#11-25-carousel

Structure is described in XML in documentation
```
</container>
<cardLayout>
    </slideItem>
    </inactiveSlideItem>
    </indicator>
    <pagination>
        </container>
        </dotStyle>
        </inactiveDotStyle>
        </dotContainerStyle>
        </text>
    </pagination>
</cardLayout>
<fullWidthLayout>
    </slideItem>
    </inactiveSlideItem>
    </indicator>
    <pagination>
        </container>
        </dotStyle>
        </inactiveDotStyle>
        </dotContainerStyle>
        </text>
    </pagination>
</fullWidthLayout>
```

but it's implemented in JS
```
export const myCarouselStyle = {
    container: {
		height:"100%"
	},
	cardLayout: {
		slideItem:{
			height:"100%"
		}
	},
    fullWidthLayout: {
		slideItem:{
			height:"100%"
		}
	}
}
```

**Comment by ConnorLand** [comment]
Hello @NicolasBRUNAUD,

I have changed the language in this document to be more accurate. Specifically, instances that erroneously referred to styling properties now properly refer to a widget's "internal structure".

Furthermore, your feedback has led us to creating a wider-ranging widget styling improvement project for the documentation. It will contain diverse improvements and will be finished in the coming months.

Thank you for contributing to the documentation,

Connor
