### ISSUE TITLE
native-styling Documentation page is not reflecting Mx9 theme folder

### ISSUE THREAD

**Issue by NicolasBRUNAUD** [mendix/docs#3380]
This page is still refering to the Mx8 folders.
In Mx9 the theme folder has been reorganized.
https://docs.mendix.com/howto/mobile/native-styling

**Comment by Adam-Dupaski** [comment]
@ConnorLand should be a quick win

**Comment by ConnorLand** [comment]
Hi @NicolasBRUNAUD . I am going to quickly fix these references and look for other instances of incorrect references. Thank you for your contribution to the documentation.

**Comment by ConnorLand** [comment]
Hi again @NicolasBRUNAUD. 

[This document](https://docs.mendix.com/howto/mobile/native-styling) has been edited with appropriate Mx9 instructions. I will check if other documents require similar updates.

Thanks again,

Connor

**Comment by NicolasBRUNAUD** [comment]
Happy to help when I can.
  
Thanks   
  
  
  
    
  

  
  
>
