### ISSUE TITLE
notification framework documentation

### ISSUE THREAD

**Issue by jorgethearchitect** [mendix/docs#3417]
The link to the notification prerequisites "basic differences" on Part 1: Local Notifications Section 2 points to a document which Apple has flagged as a retired document. 
![image](https://user-images.githubusercontent.com/5487243/121291696-8ca55c00-c89d-11eb-9aeb-d33a1c5bdb03.png)

A. https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/
B. https://developer.apple.com/documentation/usernotifications

I'm  hoping someone can clarify which version of the Apple notifications framework is supported by Mendix Native mobile?

We're on Studio Pro 9.1.1.

**Comment by smarki** [comment]
The notifications APIs are OS-level features, thus there isn't a particular version that is supported and one that isn't.
Afaik the push notifications implementation for the latest NT with support for Mendix 9 relies on usernotifications APIs.

Regards,
Stefanos

**Comment by ConnorLand** [comment]
Thank you for your issue @jorgethearchitect . I will replace links to retired Apple documentation and also add details from this conversation to our documentation.
