### ISSUE TITLE
pluggable widget development document needs update

### ISSUE THREAD

**Issue by wiwengweng** [mendix/docs#3424]
Hi, I followed the pluggable widget development document and find the `npm run dev` is not available in the package.json. Also I try to add this, but find no entry in pluggable-widgets-tools either. Can you figure this out? Thanks

![image](https://user-images.githubusercontent.com/1968042/121624548-50901800-caa4-11eb-8bd2-6aab9bef783f.png)

p.s: the deps are:
![image](https://user-images.githubusercontent.com/1968042/121624652-7cab9900-caa4-11eb-80aa-8ddeed9099cc.png)

![image](https://user-images.githubusercontent.com/1968042/121624366-f8f1ac80-caa3-11eb-9aa5-f9c550df8a47.png)

**Comment by warrengay** [comment]
I agree, I see the same

**Comment by ConnorLand** [comment]
Thank you for your feedback. We have recently completed [an overhaul of the Mx8 document](https://github.com/mendix/docs/pull/5763) which solves these issues and adds a few more improvements.

These same improvements will soon be duplicated to the Mx9 version of the document as well.
