### ISSUE TITLE
"Asset Manager" Template still referenced in documentation although it has been deprecated

### ISSUE THREAD

**Issue by BuzzyLizzy** [mendix/docs#3467]
I noticed this, but it may be in the cards to be updated in near future, just mentioning it in case it slipped through the cracks:
On this page (link below) for the "Extend your Application with Java" the paragraph "Prerequisites" referes to the "Asset Manager Template", and when I click on this it indicates "deprecated". Should this be replaced with something else?
The link to the page:
https://docs.mendix.com/howto/logic-business-rules/extending-your-application-with-custom-java

**Comment by Adam-Dupaski** [comment]
Thanks @BuzzyLizzy yes we're aware of this issue and will push it up in the backlog. We'll notify you when the update has been done.

**Comment by NatasaKralj** [comment]
@BuzzyLizzy The how-to and linked template have been updated. Thanks again for bringing it up.
