### ISSUE TITLE
formatDecimal() limited functionality within text parameter  

### ISSUE THREAD

**Issue by elliotclements-mendix** [mendix/docs#3479]
It is not possible to use formatDecimal() with the optional format string (e.g. '#.00') within a text parameter on a page. 
The text parameter works in the same way as a nanoflow and restricted to only using the system locale to specify the decimal format. 

There is no mention of this restriction within the docs.

Document Reference: https://docs.mendix.com/refguide/parse-and-format-decimal-function-calls#3-formatdecimal

![image](https://user-images.githubusercontent.com/68073174/123616380-2194d880-d7fe-11eb-8728-6c80a8f4fd3b.png)

**Comment by Adam-Dupaski** [comment]
Thanks @elliotclements-mendix I've put a warning note in section 3.1.2: https://github.com/mendix/docs/commit/89e79e2922531e6abc845aa8a0ccd6bba22cbbcc
