### ISSUE TITLE
microflow nameing conventions

### ISSUE THREAD

**Issue by wobweger** [mendix/docs#3489]
microflow naming conventions changed in [Mendix 9](https://docs.mendix.com/howto/general/dev-best-practices), 
e.g. before commit now `BCO_` shall be used, in [Mendix 8](https://docs.mendix.com/howto8/general/dev-best-practices) `BCo_`  

I come for case sensitive coding (C/C++), so for me this is a rather big change. Personally I liked previous convention better.
(All capital letters direct me towards constants.)

**Comment by Adam-Dupaski** [comment]
Hi @wobweger thanks for the feedback. This is a rather big change for microflow names, but the goal is to align with what we are teaching developers in Academy as well. This is a best practice we have standardized in Mendix, but of course it can be adapted to your requirements.
Best,
Adam
