### ISSUE TITLE
'HUGO_ENV' is not an internal or external command, nor is it an executable program or batch file.

### ISSUE THREAD

**Issue by wiwengweng** [mendix/docs#3516]
Hi, all. I want to build the doc on my onw server, but failed with this error. I follow the readme doc to set up nodejs, hugo, and yarn. The versions are:

![image](https://user-images.githubusercontent.com/1968042/125034046-b6cb8300-e0c2-11eb-987a-8b22fb61cdae.png)

'HUGO_ENV' is not an internal or external command, nor is it an executable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mxdocumentation@1.0.0 serve-test: `HUGO_ENV=test ./node_modules/.bin/gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mxdocumentation@1.0.0 serve-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wiwengweng\AppData\Roaming\npm-cache\_logs\2021-07-09T02_28_07_026Z-debug.log

**Comment by wiwengweng** [comment]
I suppose I need to set a env variable, but the doc doesn't mention it. Thanks.

**Comment by NatasaKralj** [comment]
@wiwengweng Thank you for bringing this to our attention. Please see the updated instructions on installing and launching the environment for a local build on Windows. Do let us know if this solved your issue or not.
