### ISSUE TITLE
'Model' tab of App Settings is not correct anymore

### ISSUE THREAD

**Issue by martinleppen** [mendix/docs#3523]
In chapter 3 of https://docs.mendix.com/refguide/date-and-time-handling, the last paragraph speaks of the Model tab under App Settings.
The setting that is talked about (the default timezone) can be found on the Runtime tab instead.

**Comment by MarkvanMents** [comment]
Hi Martin,
Thanks very much for pointing out this error. I have updated the documentation in this commit: https://github.com/mendix/docs/commit/5efca7990ac5504d1a186154604b4569d25cfec1.
Thanks for taking the time to point out the error and submitting an issue. It is great to have support in keeping the documentation up-to-date and correct.
Yours
Mark
