### ISSUE TITLE
Sending mail page doesn't specify internal mailserver isn't available in MxCloudV4

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/docs#355]
The page on

[Sending mail from your Mendix app](https://docs.mendix.com/howtogeneral/mendixcloud/sending-email#2-mendix-mail-servers)
Fails to specify that, while the internal mail server works for Mendix cloud nodes on V3 of the Mendix cloud, the nodes which are on the V4 of the cloud can't use the internal mail server.

It does mention it on the [Migrating to Cloud v4] (https://docs.mendix.com/howtogeneral/mendixcloud/migrating-to-v4) page

Should be mentioned at the  'general' page aswell in my opinion

**Comment by jandevriesmendix** [comment]
Hi @Mcpoowl,
The page was just updated in development and will be published to reflect this information soon.

Regards,
Jan
