### ISSUE TITLE
Manage Local Users - User Roles link points to Refguide instead of Studio guide

### ISSUE THREAD

**Issue by mengdix** [mendix/docs#3554]
In the document 'Manage Local Users in Studio': 
https://github.com/mendix/docs/blob/development/content/developerportal/deploy/managing-local-users-after-deployment.md#213-user-role

The link under 2.1.3. User Role currently points to:
https://github.com/mendix/docs/blob/development/refguide8/user-roles

It should point to:
https://docs.mendix.com/studio8/settings-security

Could this be updated? Many thanks!

Thanks!

**Comment by Adam-Dupaski** [comment]
@MarkvanMents feedback on a deployment doc.

**Comment by MarkvanMents** [comment]
Updated document.
