### ISSUE TITLE
offline docs deployment are dependent with some CDN resources

### ISSUE THREAD

**Issue by wiwengweng** [mendix/docs#3569]
Hi all. The deployment cannot be more simple, and thank you. As we deploy this docs for our client, totally offline. We need to download and customize many offline packages. 
We make a success to deploy this doc with a lot efforts, but unfortunately we find it dependent with many online CDN resources, like js and css files. This makes the deployment fail to serve the client. I wonder, if there's a quick way to fix this?
![mendix-doc](https://user-images.githubusercontent.com/1968042/127516592-15a7d0e5-a728-4dcd-a3c7-fb7985db5bbc.jpg)

**Comment by Adam-Dupaski** [comment]
Hi @wiwengweng not sure what the issue is here, can you be more specific?

**Comment by wiwengweng** [comment]
Hi, Adam. I mean can we deploy and use this document totally offline. Now there are many online resources need to be fetched from CDN. And my client want to deploy this doc, and use this doc without Internet. Thank you.

**Comment by Adam-Dupaski** [comment]
Hi, there is no offline option, but there is a Local Development option: https://github.com/mendix/docs#local-development

**Comment by Adam-Dupaski** [comment]
In the future we hope to make downloadable PDFs available. Until then, there is no offline version of our documentation site. You can choose to download selected content in Markdown: https://github.com/mendix/docs/tree/development/content

**Comment by wiwengweng** [comment]
@Adam-Dupaski Thank you Adam. I suggest if we can add a 'export PDF' in the official document website, that's more convenient.
