### ISSUE TITLE
"Start with data"-radiobox doesn't exist

### ISSUE THREAD

**Issue by RufusJWB** [mendix/docs#3595]
The "Start with data" radiobox doesn't exist anymore:
![image](https://user-images.githubusercontent.com/1633499/129042243-09caa900-3dbd-4054-95ec-b7526c56ad14.png)
This should be corrected.

**Comment by Adam-Dupaski** [comment]
Hi @RufusJWB thanks for the feedback, I've passed this on to the Academy team and they'll look into it.
Cheers,
Adam

**Comment by Adam-Dupaski** [comment]
Hi, the Academy team have informed me this has been fixed, though the fix will go out on the next deployment.
