### ISSUE TITLE
Typo in workflow commons module documentation

### ISSUE THREAD

**Issue by mpn6687** [mendix/docs#3697]
Attached screenshot highlights the typing issue.

![image](https://user-images.githubusercontent.com/55679209/133212263-52303b01-2edb-450c-88c4-580c1ff278ef.png)

**Comment by MarkvanMents** [comment]
Thanks very much for reporting this.
I have updated the document in this commit: https://github.com/mendix/docs/commit/c76f91c2a88281551f21b9467ee6427f078c6d9b
