### ISSUE TITLE
Building Block: No documentation for Category / Category Weight

### ISSUE THREAD

**Issue by elliotclements-mendix** [mendix/docs#3708]
The building block page doesn't explain the use of the new Category / Category Weight attributes 

https://docs.mendix.com/refguide/building-block

**Comment by MarkvanMents** [comment]
Hi Elliot,
Thanks for the report. Sorry that this feature hasn't been documented yet.
I have asked the developers to provide us with some documentation, and will let you know when it has been added.
Yours
Mark

**Comment by MarkvanMents** [comment]
Hi Elliot,
Just to let you know that we have published updated documentation on Category and Category weight in this document: https://docs.mendix.com/refguide/building-block

Thanks for spotting this omission and bringing it to our attention. It all helps to make our documentation better.
Yours
Mark
