### ISSUE TITLE
      Docs  / Build JavaScript Actions for Native Mobile - update to reference Mendix Native Mobile Builder 

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#3709]
"The Native Builder, a CLI tool, has been deprecated in favor of the Mendix Native Mobile Builder"

It would be helpful if the How-To for JavaScript Actions was updated to reflect this

**Comment by ConnorLand** [comment]
Hi Chris,

We are currently working on updating all how-to's affected by changes in native app building. I will update this issue when this how-to has been updated.

Thank you,

Connor

**Comment by ConnorLand** [comment]
Hi Chris,

We have completed an overhaul of the JS Actions document so it does not use the outdated CLI method: https://github.com/mendix/docs/pull/4583

Thank you for your feedback,

Connor
