### ISSUE TITLE
Backup v2 API, mendix 7 support

### ISSUE THREAD

**Issue by Snailpower** [mendix/docs#3720]
Hello,

I have been setting up an automated suite for backing up applications and then deploying them. During the backup proces I noticed that my mendix 8 apps were able to be backed up with the backup V2 API but the mendix 7 apps were not (404 environment not found with the correct projectID and envID filled in the request).

All apps are running on cloud node v4, but the mendix 7 apps were only able to be backed up with the V1 service.

The docs don't reflect this limited support, so either it is a current bug or the docs need some extra information on this :)

**Comment by MarkvanMents** [comment]
Thanks for letting us know about this, Tom.
I will take your question to the developers and let you know the outcome.
Thanks for taking the trouble to raise an issue on this - it all helps to make Mendix, and the documentation, better.
Yours
Mark

**Comment by MarkvanMents** [comment]
Hi Tom,
The development team would like to follow up on this, as they think it shouldn't be happening.
They will be in touch to ask you to raise a support ticket and provide some more information.
I will, therefore, close this issue as it doesn't appear (at present) to be documentation related. But do get in touch if you have any further concerns.

Thanks for raising this and wanting to improve the Mendix documentation.
Yours
Mark
