### ISSUE TITLE
Wrong documentation for the round() function

### ISSUE THREAD

**Issue by dan-covaliu** [mendix/docs#373]
The doc states that the round is using banker's rounding. However logging the following statements:
toString(round(23.5)) + '
' + toString(round(-23.5)) + '
' + toString(round(24.5)) + '
' + toString(round(-24.5)) + '
' + toString(round(22.5)) + '
' + toString(round(-22.5)) + '
' + toString(round(21.5)) + '
' + toString(round(-21.5))
obtains: 24,-24,25,-25,23,-23,22,-22, which looks more like "half away from zero" rounding, also called commercial rounding (https://en.wikipedia.org/wiki/Rounding#Round_half_away_from_zero).

**Comment by Rvthof** [comment]
Hi Dan,

There is an option in your Settings where you can switch between these two. Can you check if that's set correctly?

It is maybe a good idea to add this to the docs for the round function, to make this more clear.

![image](https://user-images.githubusercontent.com/688564/27275057-17a885ce-54d6-11e7-9613-1a1eed484a94.png)

**Comment by Adam-Dupaski** [comment]
Documentation updated: https://docs.mendix.com/refguide/mathematical-function-calls#output-2

Closing issue.

**Comment by dan-covaliu** [comment]
Hi Adam,

I knew about the setting… Thank you for making the documentation more precise. Still, I detect an error in the banker’s rounding definition. These are tests conducted using each setting, in turn:

Half away from zero:
toString(round(200000 div 72,2)): 2777.78
toString(round(2777.775, 2)): 2777.78
toString(round(88.725, 2)): 88.73
toString(round(23.5)): 24
toString(round(-23.5)): -24
toString(round(24.5)): 25
toString(round(-24.5)): -25
toString(round(22.5)): 23
toString(round(-22.5)): -23
toString(round(21.5)): 22
toString(round(-21.5)): -22

Half to the nearest EVEN number:
toString(round(200000 div 72,2)): 2777.78
toString(round(2777.775, 2)): 2777.78
toString(round(88.725, 2)): 88.72
toString(round(23.5)): 24
toString(round(-23.5)): -24
toString(round(24.5)): 24
toString(round(-24.5)): -24
toString(round(22.5)): 22
toString(round(-22.5)): -22
toString(round(21.5)): 22
toString(round(-21.5)): -22

As you can see EVEN numbers are 22,-22, 24 and -24, not 23 and -23


Regards, | Cordialement,

Dan Covaliu
Software Integrator and Designer | Intégrateur et concepteur de logiciel
T  514-496-1479     F 514-496-9344

bdc.ca<http://www.bdc.ca/EN/Pages/home.aspx?utm_campaign=signature&utm_medium=email&utm_source=signature>

**Comment by Adam-Dupaski** [comment]
Hi Dan,
Thanks for the message. I've clarified the example in the documentation:
https://docs.mendix.com/refguide/mathematical-function-calls#output-2
Cheers.

**Comment by Adam-Dupaski** [comment]
Hi Dan, one more thing: please note that you can contribute to the Mendix documentation yourself by sending a pull request with any changes/suggestions. See [here ](https://docs.mendix.com/community/documentation/contribute-to-the-mendix-documentation)for more details!
