### ISSUE TITLE
MindSphere IIoT for Makers doc does not explain how to obtain keys when you are not the technical owner

### ISSUE THREAD

**Issue by dlhartveld** [mendix/docs#3732]
MindSphere IIoT for Makers doc does not explain how to obtain keys when you are not the technical owner. A message is shown that does not explain what to do. The documentation should mention this scenario. Instead, the documentation now assumes you are the technical owner. That does not seem to be the common case: There's a limited number of technical owners and there will be numerous other consumers.

Link: https://docs.mendix.com/partners/siemens/mindsphere-app-service

**Comment by MarkvanMents** [comment]
Hi David,
The limitation of being a Technical Contact is mentioned in the Marketplace documentation: https://docs.mendix.com/appstore/general/app-store-overview#subscriptions.
![image](https://user-images.githubusercontent.com/35492184/135277074-b9fcafda-a8d0-4dde-9a7d-bc7d55f1c54f.png)

This is therefore a limitation within Marketplace and there is no way that a customer can obtain the binding key unless they are the technical contact.

I will raise your concern with the Marketplace developers and find out:
* why there is this limitation
* whether there are plans to lift this limitation

I will let you know when I have a response.

If you want to suggest this as an improvement, you can do this on the Mendix forum (https://forum.mendixcloud.com/p/ideas).

**Comment by dlhartveld** [comment]
That clarifies things.

I would like to suggest we point to this documentation in the UI of the service mgmt dashboard. I would not have known where to find this info otherwise.

**Comment by MarkvanMents** [comment]
Hi David,
I have a response from the developers:
1. The restriction to technical contacts is a governance feature to prevent all developers of an app being able to get the keys
2. There is a plan to allow multiple users to be given a role which allows them to get the keys, but this will not be extended to all developers of an app.

I'm told that there is already a link to the documentation from the UI. I don't have access to this page, so I can't check personally.

**Comment by MarkvanMents** [comment]
Hi David,
I'm closing this issue.
Please let me know if you spot anything else which needs changing in the documentation.
