### ISSUE TITLE
/srv/mendix/web/xas/index.html" is not found

### ISSUE THREAD

**Issue by FengXuas** [mendix/docs#3745]
I deployed the package on Redhat Server. When I login, it will cause an error "/srv/mendix/epaper/web/xas/index.html" is not found"
![image](https://user-images.githubusercontent.com/33900935/135185404-e026cad9-d35a-4809-9b1f-4be4941029b1.png)

**Comment by Adam-Dupaski** [comment]
Hi @FengXuas this looks like a dev issue that will require further context and details. This is the space for feedback on Mendix documentation. I kindly point you to the Mendix Forum, where you can post questions on your app development: https://forum.mendixcloud.com/p/questions If you suspect you are running into a bug, consider sending a Support ticket: https://support.mendix.com/hc/en-us Thanks.
