### ISSUE TITLE
Module Security > Module Role Description 

### ISSUE THREAD

**Issue by elliotclements-mendix** [mendix/docs#3756]
In section 2 of https://docs.mendix.com/refguide/module-security the definition of a module role is defined as:

`A module role defines a set of access permissions that you can assign **to a user.** For more information on module roles, user roles, and their relation, see Security.`

I believe 'to a user' should be replaced with 'to a user role'. It has caused some confusion on the RAD course.

**Comment by Adam-Dupaski** [comment]
@NatasaKralj please take a look at this via recent your recent dev experience.

**Comment by NatasaKralj** [comment]
@elliotclements-mendix I agree that the phrase is confusing, but I would not change it to 'user role' without more context. While you do assign module roles to user roles, it is not done at module role creation, nor in the menu of module roles. 

Perhaps something like the paragraph below would be better?
`A module role is a specific role you create within the module to define a set of access permissions. The permissions are contained within the module. You can assign multiple module roles to a user role under App Security > User roles. For more information on module roles, user roles, and their relation, see Security.` 
The links 'user roles' and 'security' have more detailed explanations of the differences between user roles and module roles, so I would be hesitant to add much more to this section, to avoid repetition.

**Comment by elliotclements-mendix** [comment]
@NatasaKralj that is much clearer and looks good. Thanks

**Comment by NatasaKralj** [comment]
I've updated the [doc,](https://github.com/mendix/docs/commit/98392cf71cbd4093945a34a175012d4a6bf80a53) according to the suggestion above. Closing the issue.
@elliotclements-mendix Thanks again for bringing this to out attention.
