### ISSUE TITLE
Migrate From Atlas 2 To Atlas 3

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#3794]
Various errors in this page that seem to be cut and paste type mistakes.  These cause considerable confuson when, for example, folder paths are wrong. 

E.g. confusion in this section between web / SASS and Native / js
>>>
2.4.3 Native Additonal Custom Styling

This section concerns modifications you have made to the app folder of your Atlas 2 theme and any additional js stylesheets that you might have added.

theme_atlas2/styles/native/**sass**/app/_

To move you additional stylesheets that you have added here to Atlas 3, there are two options:

Option 1 - If the additional stylesheets apply to the app level, these changes should be moved into the **web** directory of the Atlas 3 theme.

**Comment by cjfhodges** [comment]
Path names are indeed incorrect for native files

**Comment by ConnorLand** [comment]
Doc changes made [here](https://github.com/mendix/docs/pull/3849#pullrequestreview-797418997). I will close this PR now. Thank you @Chris-Karona for brining this to my attention.
