### ISSUE TITLE
error in Debug Java Actions Remotely

### ISSUE THREAD

**Issue by troyxuanyichen** [mendix/docs#3853]
Please update the jvm parameter configuration. The slash should be included.
![image](https://user-images.githubusercontent.com/14349265/140245110-3ddbf012-9586-4533-a0b4-750906d3ccef.png)

**Comment by NatasaKralj** [comment]
Hello @troyxuanyichen, thank you for your contribution.

The `-` symbol is already part of the jvm parameter. Looking at the screenshot, it appears the line break forced everything after the `-` to a new line, making it seem like `-` might not be part of the statement. 
We've updated our website in the meantime, resizing the window has the line break occur at a more convenient point in the statement.
