### ISSUE TITLE
Navigation Layout module

### ISSUE THREAD

**Issue by dan-covaliu** [mendix/docs#3877]
This module was last updated in 2017; It was long ago replaced by Atlas UI Resources; it does not even import in Mx8 and up. The documentation should not mention it for Mx9. 
![nav lay marketplace](https://user-images.githubusercontent.com/16047546/142289975-4b59992e-73f9-4d20-9126-4dcadf64e8a1.png)
In the Marketplace, it doesn't event have a Framework version. The Marketplace doc should point out the deprecation (obsolescence) and advise users not to use it anymore and switch to Atlas UI. Several User Reviews on Marketplace point this out.

https://docs.mendix.com/appstore/modules/navigation-layout

**Comment by Luyao-Zhang-1** [comment]
The issue is taken care of by [PR4010](https://github.com/mendix/docs/pull/4010)
