### ISSUE TITLE
After the 9.6 release, the Workflow documentation seems to be partially incomplete

### ISSUE THREAD

**Issue by JeroenAppel** [mendix/docs#3912]
I noticed that both on the Workflow documentation page and in the Workflow learning path there were some inconsistencies regarding the changed domain model. I had to read the 9.6 release notes to discover that I have to create a workflow context entity that is associated with the WorkflowInstance object in order to be able to select it. I think it would be helpful to update the documentation and learning path.

**Comment by MariaShaposhnikova** [comment]
Hello Jeroen,

Thanks a lot for your feedback! 

The documentation is designed to describe the latest versions of our products. We keep it up-to-date to describe what customers can do if they have the Long-term support versions of Mendix 7 and 8, or the latest release of Mendix 9. For Studio Pro, the latest release is 9.7 and we describe how workflows work in this version where more updates were introduced. For example, you no longer have to create entities, they are generated for you when you create a workflow or add a user task. For more information on the updates, see [the release notes](https://docs.mendix.com/releasenotes/studio-pro/9.7), and for information on workflow parameters and user task entities, see the [Workflow Parameters](https://docs.mendix.com/refguide/workflows#parameters) section in _Workflows_ [Workflows] and the [Data](https://docs.mendix.com/refguide/user-task#data) section in _User Task_. I hope this information helps.
 As for the learning path, the Documentation team is not responsible for maintaining learning paths, please leave the feedback on the Academy site.
 
 Best regards,
 Maria
