### ISSUE TITLE
Explanation is overdone

### ISSUE THREAD

**Issue by tvzanten** [mendix/docs#3922]
Dear Mendix Education,

It seems Mendix has the intention that every section of the Mendix documentation "how to's" should be executable by newbies, even for the advanced topics.  As a result the "how-to's" feel really overdone and don't come to the point quickly. 
 
Nor it does really teach, the overall feels like a click-through with describing every little step (like explicitly stating how to add a new action to a microflow). Maybe it is targeted to newbies to give them the feeling they can achieve something quickly with Mendix?

The issue is that in general Mendix explanations become over-detailed, missing the real grab on the matter. When e.g. explaining  REST services one could assume the developer knows how to add a microflow, add a parameter to this microflow, add an action, etc ... this should not be needed to describe again and again if someone decided to work with REST services in the first place?

Maybe Mendix could consider a 'Newbies section' with step-by-step overviews and have a regular section where it is assumed a basis Mendix knowledge is present and more attention can be given to more advanced topics related to the matter,

Regards

**Comment by Adam-Dupaski** [comment]
Thanks @tvzanten for the feedback and ideas. We have these factors in mind and are planning review, updates, and overhaul of the how-to's. I have transferred your feedback to our backlog and we will examine it moving forward with this how-to work. Cheers.
