### ISSUE TITLE
Screenshot of the Cloud Settings is outdated

### ISSUE THREAD

**Issue by joshuamoesa** [mendix/docs#3940]
Screenshot of the Cloud Settings is outdated
https://docs.mendix.com/developerportal/deploy/attachments/sap-cloud-platform/cloud-settings.png 

"SAP Cloud" is renamed to "SAP BTP".

**Comment by MarkvanMents** [comment]
Hi Joshua (@joshuamoesa)
Thanks for pointing out the outdated image(s). I have updated all the ones I could find in this commit: https://github.com/mendix/docs/commit/e056bc2abda7c8901cc4884760f411fe949445e4
Thanks for helping us keep the Mendix documentation up-to-date.
Mark
