### ISSUE TITLE
Screenshot of Create Development is outdated

### ISSUE THREAD

**Issue by joshuamoesa** [mendix/docs#3941]
In the schreenshot postgres-9.4 is mentioned. This is a deprecated service plan and when you choose this one, things won't work I've noticed. I had to choose at lease v9.6 to be successful.

See image:
https://docs.mendix.com/developerportal/deploy/attachments/sap-cloud-platform/create-development.png

**Comment by MarkvanMents** [comment]
Thanks for pointing out this issue Joshua (@joshuamoesa).
I've replaced this image with one referring to a more current database. See https://github.com/mendix/docs/commit/9e73c057dd6d365aae9a9aabad15c5dd6b0a5b73.
Thanks for helping to improve the Mendix documentation, we rely on readers to help us when we have made mistakes or not updated things which are now out of date.
Mark
