### ISSUE TITLE
Gallery Filter should be AND not OR?

### ISSUE THREAD

**Issue by laurenra7** [mendix/docs#3946]
According to the behavior I see it looks like the documentation under the [Filter section](https://docs.mendix.com/appstore/modules/gallery#3-filtering) of the [Gallery widget](https://docs.mendix.com/appstore/modules/gallery) should indicate that multiple filters are composed together in an **AND** expression not an OR expression. The documentation says this:

> The attributes selected here will be used for the matching filter placed inside the composable region. When using multiple attributes, the filters will automatically select the matching attributes and then compose the desired filter value in an OR expression.

I may be wrong, but I believe it should say this:

> The attributes selected here will be used for the matching filter placed inside the composable region. When using multiple attributes, the filters will automatically select the matching attributes and then compose the desired filter value in an **AND** expression. 

Perhaps an OR expression is how filters are composed together in a DataGrid 2, but it looks like multiple filters are being ANDed together in the Gallery widget.

**Comment by ConnorLand** [comment]
Hello Lauren,

Our developers have confirmed that your proposed edits are correct. The "OR" documentation was for a previous version of the widget. I will update the documents using your correct "AND" language.

Thank you for contributing to the documentation,

Connor
