### ISSUE TITLE
Explanation of changing the login-with-sso.thlm is out-dated in the Mendix Single Sign-On instructions page

### ISSUE THREAD

**Issue by elize-vdr** [mendix/docs#4075]
On the Mendix Single Sign-On instructions page here: https://docs.mendix.com/developerportal/deploy/mendix-sso
Paragraph `4 Setting Up Mendix Single Sign-On`
Point number 5 explains `Rename the file login-with-sso.html in the theme folder of your app to login.html `
When I opened the `thene` folder I found 2 files namely:
```
login-with-mendixsso-automatically.html
login-with-mendixsso-button.html
```
It was unclear which one I should be changing and what the difference is between the 2.
THis is or Studio Pro 9.9.1

**Comment by MarkvanMents** [comment]
Hi @elize-vdr 
Thanks for your observation. I have asked the development team for more clarity and will update the documentation when I have received more information.
Thanks for letting us know about this missing documentation, it helps us to ensure that Mendix is properly documented.
I'll let you know when the updates are published.
Yours
Mark

**Comment by MarkvanMents** [comment]
Hi @elize-vdr,
I've had approval for the changes to the documentation and have now published the updated version.
Thanks again for letting us know about this issue and enabling us to resolve it. Contributions from users are always helpful in pointing out things which are incorrect. Please do let us know if you spot anything else which could be improved.
Yours
Mark
