### ISSUE TITLE
Mendix Cloud | Cloud Resource Packs Exchange Rate

### ISSUE THREAD

**Issue by elliotclements-mendix** [mendix/docs#4115]
The Mendix Cloud documentation does not include information on the Exchange Rates for Cloud Resource Packs.
https://docs.mendix.com/developerportal/deploy/mendix-cloud-deploy#plans

As I understand it the Exchange Rates are as follows:
2XS = 1 S
2 S = 1 M
2 M = 1 L 
2L = 1 XL and so on..

e.g. a customer with 2L packs can procure 4 medium containers / environments. 

A customer requested this information, but it is not available on our public documentation.

**Comment by MarkvanMents** [comment]
Hi Elliot (@elliotclements-mendix)
I've added this to a review of resource pack information which is on Jira issue [TW-1555].
I've taken it up with the PM who is in charge of this communication from the R&D side. I'll update here once I have further information.

**Comment by MarkvanMents** [comment]
Hi Elliot,
Sorry about the delay in getting back to you.
Although we do this for customers, it is on a case-by-case basis and isn't an official policy. Therefore customers should come with requests through their CSM if they want to change their cloud resource packs.

If the official policy changes, then I will definitely add this information to the documentation.
