### ISSUE TITLE
Typo in Agile Awareness

### ISSUE THREAD

**Issue by thomasthaddeus** [mendix/docs#4128]
### learn you to focus
it should read
### 'teach you to focus'
![image](https://user-images.githubusercontent.com/92204097/151635452-ff7dbe4a-3f19-4c35-9872-5b007a04b514.png)

**Comment by Adam-Dupaski** [comment]
Thanks @thomasthaddeus I've passed this on to the Mendix Academy team, who maintains the Academy content, for the fix.
