### ISSUE TITLE
Typo in Mendix Docs, Text under 2.3.2.1

### ISSUE THREAD

**Issue by Arahndir27** [mendix/docs#4129]
There is a bullet point in the Text article of Mendix Docs under 2.3.2.1 which reads "Place the Text widget must be placed in a context of an entity, as in, inside a data widget." This doesn't make sense. I think it should just say "The Text widget must be placed in a context of an entity, as in, inside a data widget."

**Comment by MariaShaposhnikova** [comment]
Hello @Arahndir27, 

Thanks a lot for reporting the typo! As this sentence describes a step a user should follow, I have changed it to "Place the Text widget in a context of an entity, as in, inside a data widget."

Best regards,
Maria
