### ISSUE TITLE
Ldap module and Mendix v7

### ISSUE THREAD

**Issue by jamespgilbert** [mendix/docs#413]
docs/howto7/integration/synchronizing-user-accounts-using-the-ldap-module.md

There is a compatibility issue with Mendix 7 and the Ldap module spring-core-ldap library…

Error: Could not initialize class org.springframework.ldap.core.support.LdapContextSource

I had to replace the jar in the project userlib folder with version 1.3.0 which I downloaded off the internet. Then I updated the .classpath of the project to point here, and the error went away.

**Comment by Adam-Dupaski** [comment]
Hi James,
Thanks for letting us know about this. At this point this isn't a documentation issue, though. This is an issue with the App Store module, which Mendix Support will have to deal with. Please file a support request here:
[https://support.mendix.com/hc/en-us](https://support.mendix.com/hc/en-u).
Documentation will be adjusted if necessary according to how the ticket is dealt with.
Thanks,
Adam
