### ISSUE TITLE
3DViewer - Learning Path and Documentation are outdated

### ISSUE THREAD

**Issue by SebastianKru** [mendix/docs#4132]
The Mendix tutorial"Build a 3D Model Inspection App" and the documentation about the 3D Model Viewer are both not up too date. 

Build a 3D Model Inspection App
https://academy.mendix.com/link/paths/115/Build-a-3D-Model-Inspection-App

Doc
https://docs.mendix.com/appstore/app-services/3d-viewer

Both instructions state, that in order to get the model viewer to run, you need an on StartUp MicroFlow. 
"Add VisServerAction java action as AfterStartup microflow"
But this VisServer Action is outdated:
![image](https://user-images.githubusercontent.com/39736641/151781183-bb41ce9d-8a69-497a-bf92-8a76bd8dec16.png)

The current VisServerAction looks like this
![image](https://user-images.githubusercontent.com/39736641/151781322-fbc2d173-1c62-4f5d-a1b4-2d52c0771928.png)
 
So it is unclear how I can setup the 3D Model viewer. 

It is okay, if the How To is not up to date (as it recommends using an older version of 3D Model viewer) but the documentation should be up to date / have versions

**Comment by Luyao-Zhang-1** [comment]
The issue in the doc is fixed.
I also forwarded the issue in the learning path to academy and connected them with the app service developer. They are working on resolving this issue.
