### ISSUE TITLE
Creating native JS action how-to needs an update

### ISSUE THREAD

**Issue by tieniber** [mendix/docs#4139]
This article references the Mx8 and below way of manually installing native dependencies:
https://docs.mendix.com/howto/extensibility/create-native-javascript-action#installing-dependency-app

It should be updated to follow the Mx9+ process, which is much simpler:
https://docs.mendix.com/apidocs-mxsdk/apidocs/pluggable-widgets-native-dependencies

**Comment by NatasaKralj** [comment]
https://github.com/mendix/docs/pull/4583 resolves this issue
