### ISSUE TITLE
Link to .mpk file doesn't work

### ISSUE THREAD

**Issue by therden-siemens** [mendix/docs#4142]
Hi. The dropbox link (https://www.dropbox.com/s/2mbssghy754h2jh/JavaScript_Actions_How_To_Advanced.mpk?dl=0) to the .mpk file in the chapter on javascript actions doesn't work.

**Comment by NatasaKralj** [comment]
Created [PR ](https://github.com/mendix/docs/pull/4150) to fix link.
I added the package to the repo, as the dropbox link can change again, and it is not public.
