### ISSUE TITLE
Scout-App updates

### ISSUE THREAD

**Issue by TheJaredWilcurt** [mendix/docs#42]
The Screenshots on this page:

* https://docs.mendix.com/howto6/Create+a+custom+theme+with+the+Mendix+UI+Framework

Show the 2012 app.

And you link to a separate page for a Windows work around:

* https://docs.mendix.com/howto6/Scout+and+Windows+10+Workaround

The 2016 app works on Windows XP, Vista, 7, 8, and 10 out of the box. It also works on Linux and OSX 10.6+.

The new website is

* http://scout-app.io

**Comment by jandevriesmendix** [comment]
Hi @TheJaredWilcurt,
You can edit the documentation in GitHub now. When you submit a pull request we will do a final review and publish your changes.

**Comment by TheJaredWilcurt** [comment]
@jandevriesmendix 

On further inspection it looks like your UI framework is built on Compass and Ruby-Sass.

* https://www.mendix.com/application-platform-as-a-service/responsive-ui-framework/

Scout-App 2 (2016) no longer supports Ruby-Sass and will not in the future as the maintainers of it have switched to Node and Dart. Compass is end-of-life and unmaintained.

Scout-App Classic (2012) is also no longer maintained and is end-of-life.

So if you guys require the 2012 era of Sass (Ruby-Sass/Compass) then the links for Scout-App should be updated to point to the classic version.

* http://Scout-App.io/classic

Good luck with your project.

**Comment by jandevriesmendix** [comment]
Hi @TheJaredWilcurt,
You are free to change the files and links and submit a pull request. We will look at your changes and merge them. It's one of the reason we moved to GitHub, so that observant members of the community like you can update and improve the documentation :)

**Comment by Adam-Dupaski** [comment]
Hi @TheJaredWilcurt,
Please see [How to Contribute to the Mendix Documentation](https://docs.mendix.com/community/Contribute+to+the+Mendix+Documentation) for details on how to make changes and submit a pull request.
Thanks!
