### ISSUE TITLE
Update for docs page on exposing data to BI tools using OData

### ISSUE THREAD

**Issue by mchmx** [mendix/docs#4205]
Team,

A client reported that the following documentation is missing a step.
https://docs.mendix.com/howto/integration/exposing-data-to-bi-tools-using-odata#4-working-with-mendix-data-in-excel-for-office-365

He noted that in step 3, the URL should not be as displayed in the documentation, but instead be the link seen when viewing "Edit published resource.

The attached screenshot is of the email describing his findings.

Thanks in advance.

-Matt

![image](https://user-images.githubusercontent.com/22504473/154561170-1510b683-ae9e-467a-b5a3-fc802fd99588.png)

**Comment by johannahemminger** [comment]
Hi @mchmx , thanks very much for submitting this, and sorry for my late reply. I'll work on rewriting this document to reflect the changes, including removing the deprecated sample app.

**Comment by johannahemminger** [comment]
Releasing new version of the document without the dependency on the deprecated sample app and with missing instructions. Thanks for reporting this initially!
