### ISSUE TITLE
This MF activity doesn't exist in mx9.6.6

### ISSUE THREAD

**Issue by x4g** [mendix/docs#4254]
Cannot find the "Retrieve workflow context" microflow activity in mx 9.6.6 as described in https://docs.mendix.com/refguide/retrieve-workflow-context

Please update the documentation or give more precise instruction about how to use it.

Please also explain how a WorkflowContext object is defined and used. 
ex. How to determine the entity type a WorkflowContext refers to?

**Comment by MariaShaposhnikova** [comment]
Hi @x4g ,
Thank you for your feedback. Our documentation is updated according to the latest version, which is 9.11.1 now. The **Retrieve workflow context** activity is not available in 9.6.6, it was released in [9.10.0](https://docs.mendix.com/releasenotes/studio-pro/9.10).
The **Retrieve workflow context** action will determine the return type based on the selected workflow (it'll be the configured context entity of that workflow). At Runtime it will break if the passed workflow object is not of the right type.
I will clarify information in the document ASAP.

Best regards,
Maria

**Comment by MariaShaposhnikova** [comment]
Hi @x4g 
I've added a bit more information on the **Retrieve workflow context** document in [this PR](https://github.com/mendix/docs/pull/4340). I hope, it makes the explanation on the Workflow Context more clear.

Best regards,
Maria
