### ISSUE TITLE
Doumentaion for Nanoflow Commons

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#4275]
When you look at the Marketplace module Nanoflow Commons the documentation section refers the reader to the Mendix Studio Pro Ref Guide with a link.  The Mendix Studio Pro Ref Guide refers the reader back to the MarketPlace documentation.  

I have a specific question I was trying to address.  If I want to use the geolocation actions we get a runtime error because the library @react-native-community/geolocation is imported but it does not appear to be in the Mendix Native Template.  There are no instructions in the documentation that the library needs to be imported into a custom native template but this appears to be the only way to make it work.  Is this correct? 

I am sure there are other things that users of the module might like to know too. 

Thanks for your help.

**Comment by Luyao-Zhang-1** [comment]
@Chris-Karona Are you using Mendix 8 or 9?

**Comment by Luyao-Zhang-1** [comment]
Hi @Chris-Karona, I checked with our developer – so you should do the following:
1. Install the module in Studio Pro
2. Use the native builder UI tool from studio pro to configure the native app
The builder tool detects the dependency and add it to the native app automatically

**Comment by Luyao-Zhang-1** [comment]
I will look into the possibilities of improving the Nanoflow Commons doc. I created a [task](https://mendix.atlassian.net/browse/TW-1614) in the backlog.
