### ISSUE TITLE
Unfinished sentence in "Publish a REST Service"

### ISSUE THREAD

**Issue by BYUDiningWeb** [mendix/docs#4287]
Under [Publish a REST Service](https://docs.mendix.com/howto/integration/publish-rest-service/#1-introduction) The first sentence is incomplete. Here is the paragraph. Note the end of the first sentence:
"Mendix allows you to publish REST web services natively from . This how-to will show you how to publish a REST service in an example project. This example will demonstrate the GET operation for a published REST service."

**Comment by Adam-Dupaski** [comment]
Hi @BYUDiningWeb thanks for pointing out this omission, it should only be "Studio Pro," I've made the fixes.
