### ISSUE TITLE
Native Mobile Styling

### ISSUE THREAD

**Issue by tieniber** [mendix/docs#4315]
Running Chrome on MacOS, I can't see/scroll the whole document tree in the right-hand sidebar:
https://docs.mendix.com/refguide/native-styling-refguide/#21--class-names

**Comment by NatasaKralj** [comment]
Hello @tieniber, thanks for the feedback.
We recently added scrollbars to each menu section, which should fix the issue. Please let us know if you run into more issues in our slack channel.
