### ISSUE TITLE
Build a Pluggable Native Widget

### ISSUE THREAD

**Issue by peerguba-design** [mendix/docs#4321]
There is no hint in this tutorial that I have to install an older node.js version (14) in order to make this running. The process will fail when trying this with the latest node.js version.

**Comment by ConnorLand** [comment]
Thank you for your feedback. We have recently completed [an overhaul of the Mx8 document](https://github.com/mendix/docs/pull/5763) which solves these issues and adds a few more improvements.

These same improvements will soon be duplicated to the Mx9 version of the document as well.
