### ISSUE TITLE
SAML

### ISSUE THREAD

**Issue by joeavelar** [mendix/docs#4347]
For the following on https://docs.mendix.com/appstore/modules/saml/

KeyStore – All the certificates required for encryption are stored in the keystore. Resetting the keystore or uploading another keystore will require all the IdPs to import the new metadata file. If you use a custom keystore, make sure the alias of the keystore is the same as the SP entity ID. In addition, make sure the new keystore password is set in the KeystorePassword constant.

This is not very clear. How are the KeyStore files generated? Manually created if we are going to use one? In which situation would you use this?

**Comment by Luyao-Zhang-1** [comment]
@MarkvanMents would you like to pick up this issue, or should I pick it up?

**Comment by MarkvanMents** [comment]
I'll have a look at it. I've got a meeting about the SAML module next week and can ask about it then.

**Comment by MarkvanMents** [comment]
Hi Joe (@joeavelar )
I have discussed the key store with the developers and have created pull request #4587 to try to clarify this, and a couple of other aspects of the SAML module.
I hope that these changes answer your questions above.
Thank you for bringing this to our attention and helping to improve the quality of our documentation. Please continue to let us know where the documentation can be improved.
Yours
Mark van Ments

**Comment by MarkvanMents** [comment]
PR is now merged. Closing this issue.
