### ISSUE TITLE
Microflow Timer

### ISSUE THREAD

**Issue by elize-vdr** [mendix/docs#4403]
The documentation for the Microflow Timer is not sufficient to understand how it works. The paragraph `Configuration` states:
```
The widget requires a data view or template grid context. This object will be sent as an argument to the invoked microflow or nanoflow.
```

How does one get the `data view or template grid context.` into the microflow or nanoflow since this states it requires `data view or template grid context.` and that `this object` will be sent to the microflow or nanoflow. What is `this object`? How and where  is it create and sent to the microflwo or nanoflow? Must I declare something on the data view or template grid?

**Comment by Luyao-Zhang-1** [comment]
@elize-vdr Thank you for your feedback. I added more details to the [doc](https://docs.mendix.com/appstore/widgets/microflow-timer/). Hopefully this can help you and other users better understand how it works. If you have more feedback, please let us know by opening an issue.
