### ISSUE TITLE
Native Mobile Styling - Badge Text

### ISSUE THREAD

**Issue by Dan-McElroy** [mendix/docs#4422]
In section 11.4 of the Native Mobile Styling page, "Badges", the structure is described as:

```xml
<container>
	<text>New</text>
</container>
```

However, it seems that this is inaccurate, and that `text` should actually be `caption`.

**Comment by ConnorLand** [comment]
Hi @Dan-McElroy ,

Thank you for pointing this code snippet error out. You were totally correct, it should have been `caption`. 

Another user also pointed it out, it was fixed, and I should have replied back to you with a status update: https://docs.mendix.com/refguide/mobile/designing-mobile-user-interfaces/widget-styling-guide/#114-badge

I apologize for your feedback staying unaddressed for so long, and thank you for enhancing the Mendix documentation with your efforts.

Connor
