### ISSUE TITLE
Expose Data to BI Tools Using OData - Issues using non-legacy importer

### ISSUE THREAD

**Issue by Ixxith** [mendix/docs#4432]
When using that standard OData importer for excel, I get the following error (for both OData v3 and v4)
![image](https://user-images.githubusercontent.com/60019877/162475995-7978cc2d-f61e-4a4c-b1ae-5957bdda4c50.png)

In order to fix this, I had go to File -> Options -> Data and then under the Show legacy data import wizards, select "From Odata Data Feed (Legacy)" 
![image](https://user-images.githubusercontent.com/60019877/162476268-6c4422d5-f16e-462b-9937-aee70988b74f.png)

I then could select that option from the normal data source dropdown
![image](https://user-images.githubusercontent.com/60019877/162476333-1edb1700-4ace-4ed4-b725-ccfe0734f9d1.png)

This option still only worked with OData v3, so far no luck getting v4 to work on Excel. Whenever I would try v4 it told me 
`Unable to connect :  Details: "OData: The feed's metadata document appears to be invalid."`

**Comment by johannahemminger** [comment]
Thanks @Ixxith for submitting this, I will look into this.

**Comment by johannahemminger** [comment]
Hi @Ixxith , I have verified that this is a known bug with Excel not parsing metadata properly. We are working on it and a fix is expected soon. I will close this issue for now, but please feel free to be in touch if you have any issues or suggestions for our documentation. Thanks!
