### ISSUE TITLE
Mendix Feedback

### ISSUE THREAD

**Issue by SiemensHenrique** [mendix/docs#4433]
Perhaps this screen should be included in the configuration 
<img width="715" alt="Captura de ecrã 2022-04-08 181423" src="https://user-images.githubusercontent.com/103277747/162490646-293e3218-7a0f-4ab5-96f0-cfa68494ded2.png">

**Comment by MarkvanMents** [comment]
Hi @SiemensHenrique 
I'm not sure I understand what you are asking?
In our documentation, we describe what should be on this screen in https://docs.mendix.com/developerportal/collaborate/general-settings/.
Is there something missing in our documentation which you would like to see, or is there information which you can't find on the platform?

Please can you let me know what you think should be covered and I can investigate it further.
Thanks
Mark

**Comment by SiemensHenrique** [comment]
Hi Mark,

Yes it is there under the documentation, but not under the configuration of the feedback widget itself, which is present under the marketplace guide. And also, there is no reference to the feedback widget under the link you shared, and neither there is a reference to the existence of the general settings link under the marketplace widget.

Best regards

**Comment by MarkvanMents** [comment]
Hi Henrique,
Thanks for the clarification. I will look into this and see how we can improve the references to configuring the feedback widget.
Yours
Mark

**Comment by MarkvanMents** [comment]
Hi Henrique,
Just to let you know that we have updated the documentation. I hope that this improves the documentation to help with the configuration of the feedback widget.
Thanks for bringing this to our attention.
Please let us know if you identify further improvements we can make to the documentation.
Yours
Mark.

**Comment by SiemensHenrique** [comment]
> Hi Henrique, Just to let you know that we have updated the documentation. I hope that this improves the documentation to help with the configuration of the feedback widget. Thanks for bringing this to our attention. Please let us know if you identify further improvements we can make to the documentation. Yours Mark.

Thank you for your time and consideration. The whole Mendix community will have an easier life with this guide. Thanks
