### ISSUE TITLE
Community Commons

### ISSUE THREAD

**Issue by dan-covaliu** [mendix/docs#4434]
CommunityCommons documentation does not contain anything for the StringSplit Java Action. The JA itself has its Documentation tab empty

**Comment by Luyao-Zhang-1** [comment]
@dan-covaliu  I added the info about the `StringSplit` java action to the doc. You can find it in the [StringUtils](https://docs.mendix.com/appstore/modules/community-commons-function-library/#49-stringutils) section now. Thank you for your feedback!
