### ISSUE TITLE
Generate Code from the Model

### ISSUE THREAD

**Issue by alexkleymen** [mendix/docs#4439]
What Studio version are you using? 
Does it work with the new Model and platform SDK (new version)

**Comment by MariaShaposhnikova** [comment]
@alexkleymen , thanks for your message.
Could you please specify what document or what space (for example, Studio 9 Guide) you are referring to? 

Best regards,
Maria

**Comment by MariaShaposhnikova** [comment]
@alexkleymen, as I could not find a problem I will close this issue. I will be happy to reopen it when you have more details. If you run into any other issue that the Documentation team can help with, please let us know. You can also try the Mendix Forum or Support if you run into other kinds of errors. 

Best regards,
Maria
