### ISSUE TITLE
Automate the import of Multiple  Excel files in Mendix 

### ISSUE THREAD

**Issue by Patilvikas1910** [mendix/docs#4447]
What are the contents in the microflow to automate the above process.

**Comment by johannahemminger** [comment]
Hi @Patilvikas1910 , thanks for raising this issue. Which document are you referring to when you ask about the contents of the microflow?

**Comment by johannahemminger** [comment]
Hi @Patilvikas1910 , I haven't heard back from you so I will close this issue. But if you have any suggestions for improvements or clarifications in our docs, please let us know by opening another issue. You can also check out the Mendix forum or contact support if you are having a specific problem. Thanks again.
