### ISSUE TITLE
OData Query Options

### ISSUE THREAD

**Issue by RoelandSalij** [mendix/docs#4453]
For the associated objects retrieve it would be helpful to understand how Employees correlate to Cars and Address. Are these related or just an example of two associated entities.
For example by showing a domain model for reference?

**Comment by johannahemminger** [comment]
Hi @RoelandSalij , thanks for the feedback. Could you point me to the specific section in **OData Query Options** that you are referring to? Or where you think it would make sense to add this?

**Comment by johannahemminger** [comment]
Thanks for reporting this! I have added a clarification of the entities and associations in this section.
