### ISSUE TITLE
Ctrl-f phantom results

### ISSUE THREAD

**Issue by tieniber** [mendix/docs#4479]
Page link: [Native Template 6](https://docs.mendix.com/releasenotes/mobile/nt-6-rn/)

Document link: [nt-6-rn.md](https://github.com/mendix/docs/blob/development/content/en/docs/releasenotes/mobile/native-template/nt-studio-pro-9-parent/nt-6-rn.md)

## Using ctrl+f page search in documentation shows "phantom" results.

This applies to most (all?) pages in our documentation. Search for a word and you'll see double or triple of the number of real results. Most of them don't highlight anywhere on the page.

**Comment by Adam-Dupaski** [comment]
Hi @tieniber thanks for the feedback, yes, we are aware of this issue - searching seems to find everything that is in a link, as well as what is shown on the page. This is on our list of improvements that need research.
