### ISSUE TITLE
Validation Rules

### ISSUE THREAD

**Issue by rayyqh** [mendix/docs#4496]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Validation Rules](https://docs.mendix.com/refguide/validation-rules/)

Document link: [validation-rules.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/domain-model/entities/validation-rules.md)

## My Issue/Suggestion
the screen copies are used in this page are wrongly positioned. Move up to down, vice verse.

**Comment by NatasaKralj** [comment]
@rayyqh Thank you for letting us know about this issue! I've swapped the images in section 3.1.3 Generalizations. Please let us know if you find any other issues in the future.
