### ISSUE TITLE
Write Data to Another App

### ISSUE THREAD

**Issue by mx-jdeloo** [mendix/docs#4512]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Write Data to Another App](https://docs.mendix.com/data-hub/write-data/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/data-hub/write-data/_index.md)

## My Issue/Suggestion

The table seems wrong:

<html>
<body>

Data Hub | Studio Pro
-- | --
Create | Creatable
Read | Insertable
Update | Updatable
Delete | Deletable

</body>
</html>

should be as follows I think:

<html>
<body>

Data Hub | Studio Pro
-- | --
Create | Insertable
Read |  Readable
Update | Updatable
Delete | Deletable

</body>
</html>

**Comment by johannahemminger** [comment]
@mx-jdeloo you are absolutely right, thanks for reporting this! I have made the changes.
