### ISSUE TITLE
Install Mendix Studio Pro

### ISSUE THREAD

**Issue by x4g** [mendix/docs#4543]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Install Mendix Studio Pro](https://docs.mendix.com/howto/general/install/)

Document link: [install.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/general/install.md)

## My Issue/Suggestion

The latest studio pro installation dependencies include the Microsoft .NET Desktop Runtime 6.0, as described in the **"5 Troubleshooting"** paragraph.
But what about the **offline installation** instructions? What should the latest .NET installer file be renamed to? The content about the _.NET Framework 4.7.2_ needs to be updated

**Comment by Adam-Dupaski** [comment]
Hi @x4g thanks for the feedback. We updated those instructions via #4574, so please reference the updated doc.

Cheers,
Adam
