### ISSUE TITLE
Drop-Down

### ISSUE THREAD

**Issue by jasonteunissen** [mendix/docs#4558]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Drop-Down](https://docs.mendix.com/refguide/drop-down/)

Document link: [drop-down.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/pages/input-widgets/drop-down.md)

## My Issue/Suggestion

The dropdown button isnt a dropdown.
it just creates a popup that doesnt respect the DOM at all.
either fix the button, or make it clear in the documentation that this is just a popup creator.

**Comment by ConnorLand** [comment]
Hi @jasonteunissen ,

I spoked with Takuma about your comments at length. Owing partially to your feedback, and the feedback of other users, this widget is going to undergo comprehensive changes in the future. So while the widget and its docs will stay as they are for the moment, they will be changed drastically in the future due (in part) to your feedback.

Thank you for improving Mendix,

Connor
