### ISSUE TITLE
Drop-Down Button

### ISSUE THREAD

**Issue by jasonteunissen** [mendix/docs#4559]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Drop-Down Button](https://docs.mendix.com/refguide7/drop-down-button/)

Document link: [drop-down-button.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide7/desktop-modeler/pages/button-widgets/drop-down-button.md)

## My Issue/Suggestion
this is not a dropdown.
this does not respect the DOM
this just opens a popup.

**Comment by ConnorLand** [comment]
This issue is duplicated [here](https://github.com/mendix/docs/issues/4558). I will reply at that location.
