### ISSUE TITLE
Build JavaScript Actions for Native Mobile

### ISSUE THREAD

**Issue by OlafNekemanSvinergy** [mendix/docs#4581]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Build JavaScript Actions for Native Mobile](https://docs.mendix.com/howto/extensibility/create-native-javascript-action/)

Document link: [create-native-javascript-action.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/extensibility/build-javascript-actions/create-native-javascript-action.md)

## My Issue/Suggestion

I think you can update this page. For example, in the Build Native App wizard, you can set "App permissions" for Ios and Android. Now it is confusing if the part from the toturial with all the manual code editing is still necessary. 

More importantly, I executed this toturial in Mendix 9.11.1 and it did not work. Importing the NFC module in a javascript action causes the app to crash in the Make it Native app on start up. I did not even fire any actions....

**Comment by NatasaKralj** [comment]
Hello @OlafNekemanSvinergy,
Thank you for your suggestions. We recently updated the document in question to better align with Studio Pro 9 workflow in [PR 4583](https://github.com/mendix/docs/pull/4583). Please see the updated documentation. 
In case of any more issues or suggestions, don't hesitate to reach out again.
