### ISSUE TITLE
3D Viewer for Teamcenter

### ISSUE THREAD

**Issue by usturgeom101** [mendix/docs#4599]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [3D Viewer for Teamcenter](https://docs.mendix.com/appstore/app-services/3d-viewer-for-teamcenter/)

Document link: [3d-viewer-for-teamcenter.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/app-services/3d-viewer/3d-viewer-for-teamcenter.md)

**Comment by usturgeom101** [comment]
instruction given on https://docs.mendix.com/appstore/app-services/3d-viewer-for-teamcenter/ is not pulling jt file to the viewer . Look like something is missing.

**Comment by DISW-Mendix-3DViewer** [comment]
> instruction given on https://docs.mendix.com/appstore/app-services/3d-viewer-for-teamcenter/ is not pulling jt file to the viewer . Look like something is missing.

Hi :
This is 3D Viewer dev team, Can you provide more details about the issue you reported?
You can directly email us: 3DViewer_Mendix_WC.sisw@siemens.com
Best Regards

**Comment by Luyao-Zhang-1** [comment]
We closed this ticket, because we could not get needed input from the reporter .
