### ISSUE TITLE
Docs load slowly on slow/mobile networks

### ISSUE THREAD

**Issue by jdiehl** [mendix/docs#4614]
Every document that is loaded is more than 1MB in size, most of which is the navigation. On slow networks (Chrome Fast 3G) it takes more than 10s to load the page source, leading to a total load time of 20s.

**Comment by jdiehl** [comment]
I have noticed that compression is turned off on the production server. Enabling compression reduces transferable content of pages from > 1MB to < 100KB on my system.

**Comment by NatasaKralj** [comment]
docs.mendix.com now has compression enabled, pages are now cca. 100KBs. Thank you @jdiehl for the suggestion and tips.
