### ISSUE TITLE
9.12 Download button does not works

### ISSUE THREAD

**Issue by Grasshooper** [mendix/docs#4630]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [9.12](https://docs.mendix.com/releasenotes/studio-pro/9.12/)

Document link: [9.12.md](https://github.com/mendix/docs/blob/development/content/en/docs/releasenotes/studio-pro/9/9.12.md)

**Comment by Adam-Dupaski** [comment]
Hi @Grasshooper thanks for the feedback. I just tested all 3 buttons for 9.12 versions from the 9.12 release notes, and they brought me to the correct page in the Marketplace. Which specific version were you referring to? Can you check this again?
Thanks,
Adam
