### ISSUE TITLE
Document Generation Activities

### ISSUE THREAD

**Issue by Adangge** [mendix/docs#4658]
Page link: [Activities](https://docs.mendix.com/refguide/activities/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/_index.md)

## My Issue/Suggestion
There is an error, microflow activity "Document generation activities" is only in **microflows** not in **nanoflows**. 
![image](https://user-images.githubusercontent.com/25549363/172019922-872a2aea-6d74-4c2a-850c-af69e2e224b6.png)

**Comment by MariaShaposhnikova** [comment]
Hi @Adangge , thanks a lot for reporting this issue! I have changed the text to "only in microflows". 

Cheers,
Maria
