### ISSUE TITLE
Confusing/contradictory description of metrics filters

### ISSUE THREAD

**Issue by sjoerdbreur** [mendix/docs#4661]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Metrics](https://docs.mendix.com/refguide/metrics/)

Document link: [metrics.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/runtime/metrics.md)

## My Issue/Suggestion
Reading note 3 for filters describes the following:
> Filters are executed on a first come, first served basis. Hence the first applied filter gets the priority. For example, If you have a below setup,
```
[
  {
    "type": "statsd",
    "settings": { "protocol": "TCP" },
    "filters": [
      { "type" : "nameStartsWith", "result" : "accept", "values" : ["app."] },
      { "type" : "nameStartsWith", "result" : "deny", "values" : ["app.others."] }
    ]
  }
]
```
> This will deny metrics like “app.others.counter” due to the contradiction with the first accept filter “app.".

This seems contradictory/confusing way of formulating to me. To me 'first come, first served' could be explained as that the first filter would cause any metric for which the name starts with `app.` to be accepted, and the second filter rendered meaningless. However, the second part of the quote suggests that a metric like `app.others.counter` would be excluded because of the second filter. 

In that case it seems 'first come, first served' is a term that at best ends up quite confusing. The example gives the impression that instead the filters are applied in order of declaration, with the final filter that is declared which applies to a metric deciding whether it gets accepted or not.

**Comment by MarkvanMents** [comment]
Agreed @sjoerdbreur. I think it is better to say that the filters are applied _in order_ and that all the filters need to pass.
I'll make a PR and ask you and Jonathan to review it for me.
Thanks.

**Comment by MarkvanMents** [comment]
Looks like the text is correct and the example is wrong. Rather than the other way around.
> And regarding the example, as you noticed it would just accept app.others.counter because  it matches with the first filter and once it matches it will no longer continue to check other filters.

Updating the PR #4695

**Comment by MarkvanMents** [comment]
Document updated.
Thanks for finding this Sjoerd.
