### ISSUE TITLE
Set Up an SSO (BYOIDP)

### ISSUE THREAD

**Issue by NicolasBRUNAUD** [mendix/docs#4672]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Set Up an SSO (BYOIDP)](https://docs.mendix.com/developerportal/control-center/set-up-sso-byoidp/)

Document link: [set-up-sso-byoidp.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/control-center/set-up-sso-byoidp.md)

## My Issue/Suggestion

"The Mendix Cloud solution offers an Identity Provider (IdP) that allows users to sign in to:
Mendix Platform services
Mendix applications that have been built with Mendix SSO"

==> should provide the link to the "Mendix SSO" module documentation 
https://docs.mendix.com/developerportal/deploy/mendix-sso/

**Comment by MarkvanMents** [comment]
Thanks for your suggestion, Nicolas.
I've made the change in this commit: 4c98ec4a931341778844ca40dfcf501d2f75944d
Thank you for taking the time to raise this issue - the suggestion will make it easier for readers to find the right documentation.
Please let us know if you have any further suggestions for improvements to the documentation.
Yours
Mark
