### ISSUE TITLE
Work with Git On-Premises Version Control Server

### ISSUE THREAD

**Issue by x4g** [mendix/docs#4698]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Work with Git On-Premises Version Control Server](https://docs.mendix.com/howto/collaboration-requirements-management/on-premises-git-howto/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/collaboration-requirements-management/on-premises-howto/on-premises-git-howto/_index.md)

## My Issue/Suggestion
Is the git integration in Studio Pro still in Beta? Local R&D said they've been officially using git in Studio Pro for a long time.
Can you please confirm if the documentation is outdated? 
Because some customers actually need to use git but have concerns about the stability of the beta version functionality.

**Comment by plp95** [comment]
+1 - I am also wondering if git (in my case GitHub) can be released as Enterprise standard and VCS of first choice in Mendix.

**Comment by grootjans** [comment]
The documentation that was written at the time of MxWorld has unfortunately not yet been updated to the reflect current situation. Our focus and effort has been on the rollout of our Teamserver Git offering. In our current timeline we plan to release BYO:Git GA on April 2023, but we will update the planning if the timeline improves or changes. We will update the documentation accordingly.

**Comment by grootjans** [comment]
@plp95 Github is one of the supported providers in the current Beta offering: https://docs.mendix.com/refguide/system-requirements/#supported-providers and will continue to be a part when this goes GA.

**Comment by MariaShaposhnikova** [comment]
Hi @x4g , thank you for your feedback! The [documentation](https://docs.mendix.com/releasenotes/mx-world-2021/) has been updated, so I will close this issue.
@grootjans , thanks for addressing all questions!

Best regards,
Maria
