### ISSUE TITLE
Call REST Service

### ISSUE THREAD

**Issue by mheesters** [mendix/docs#4706]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Call REST Service](https://docs.mendix.com/refguide/call-rest-action/)

Document link: [call-rest-action.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/integration-activities/call-rest-action.md)

## My Issue/Suggestion

Regarding: https://docs.mendix.com/refguide/call-rest-action/#731-latesthttpresponse-variable
It is said that: "This variable can be accessed from any microflow action in the scope."

It would be nice if a scope description could be added.
I found out you can't access the variabele in a flow that called your flow, or a flow that was called by your flow.
So you can only access the variable from the flow your webservice call is made in!

Thanks! 🙏

**Comment by johannahemminger** [comment]
Hi @mheesters , thanks very much for the contribution! I will consult with the dev team about this and hope to have some updates on this soon.

**Comment by johannahemminger** [comment]
Hi @mheesters , sorry for the (very long) delay. I have linked some related documentation to help explain this, but we are working on making this and other sections a bit clearer in the longterm. Thanks for reporting this, and if you see other corrections or areas of improvement, please feel free to create a new issue!
