### ISSUE TITLE
Import Excel Documents

### ISSUE THREAD

**Issue by kobamasa1** [mendix/docs#4725]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Import Excel Documents](https://docs.mendix.com/howto/integration/importing-excel-documents/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/integration/importing-excel-documents/_index.md)

## My Issue/Suggestion
The link of Download Sample button is only for image, not excel file.

**Comment by johannahemminger** [comment]
Hi @kobamasa1 , thanks for opening this issue. I just tried it on Chrome and Firefox, and for me it downloads 18581949.xlsx. Can you try again and let me know what happens?

**Comment by johannahemminger** [comment]
Hi @kobamasa1 , as I could not find a problem I will close this issue. But if you run into anything else that we on the documentation team can help with, please let us know! You can also try the Mendix forum or support if you run into other kinds of errors. Thanks again!

**Comment by kobamasa1** [comment]
Hi Johanna,

I could download it. Thank you for your reply. When I tested it in this morning, I could not download it.
But anyway, it resolved!!

Best regards,
Masa

**Comment by johannahemminger** [comment]
@kobamasa1 OK, no worries! It still works for me...wonder why it happens sometimes.

**Comment by kobamasa1** [comment]
I could download it. Thank you for your support.
