### ISSUE TITLE
Community Commons

### ISSUE THREAD

**Issue by Rini222** [mendix/docs#4734]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Community Commons](https://docs.mendix.com/appstore/modules/community-commons-function-library/)

Document link: [community-commons-function-library.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/community-commons-function-library.md)

## My Issue/Suggestion

DuplicateFileDocument – This clones the contents of one file document into another and instantly commits the cloneTarget

**Comment by Luyao-Zhang-1** [comment]
@Rini222 Thank you for your suggestion. We have implemented it in the [doc](https://docs.mendix.com/appstore/modules/community-commons-function-library/#43-files).
Thank you for taking the time to raise this issue. Please let us know if you have any further suggestions for improvements to the documentation.
