### ISSUE TITLE
registerHeadlessTask or registerCancellableHeadlessTask called multiple times for same key 'ReactNativeFirebaseMessagingHeadlessTask'

### ISSUE THREAD

**Issue by Aruna1401** [mendix/docs#4735]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Part 7: Send Your First Test Push Notification](https://docs.mendix.com/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test/)

Document link: [notif-send-test.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md)

**Comment by Adam-Dupaski** [comment]
Hi @Aruna1401 can you describe your feedback?
