### ISSUE TITLE
Publish a REST Service

### ISSUE THREAD

**Issue by ako** [mendix/docs#4741]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Publish a REST Service](https://docs.mendix.com/howto/integration/publish-rest-service/)

Document link: [publish-rest-service.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/integration/publish-rest-service.md)

## My Issue/Suggestion

The example in section 4.2 uses an export mapping to generate json. A remark should be added that this is not required. If you simply return the list of objects from the microflow, the platform will export it in the format desired by the client, as indicated by the Accept header (content negotiation). The client can then specify if it wants to receive xml or json.

Mendix's published REST services provide out of the box support for content negotiation as discussed here: https://nordicapis.com/content-negotiation/

**Comment by johannahemminger** [comment]
Thanks @ako , will update this now.

**Comment by johannahemminger** [comment]
Added a small section, thanks for opening the issue!
