### ISSUE TITLE
Deep Link

### ISSUE THREAD

**Issue by vinicius-ambrosio-truechange** [mendix/docs#4744]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Deep Link](https://docs.mendix.com/appstore/modules/deep-link/)

Document link: [deep-link.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/deep-link.md)

## My Issue/Suggestion
In the section 3.2, the text at 
'''
... For an example of this configuration, see the DeepLink.Home_ResponsiveProfile microflow.
'''

is incorrect.
The name of the microflow should be:
Home_Desktop_Default

**Comment by Luyao-Zhang-1** [comment]
@vinicius-ambrosio-truechange thanks for raising this ticket. May I ask which version of the module you are using?

**Comment by vinicius-ambrosio-truechange** [comment]
Hi, I'm using DeepLink 6.03 - the last version that works with the module "Forgot Password". 
Indeed, the last version 9.02 the info in the docs is correct! 
Let's close this ticket!
