### ISSUE TITLE
Install Mendix Studio Pro

### ISSUE THREAD

**Issue by NicolasBRUNAUD** [mendix/docs#4788]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Install Mendix Studio Pro](https://docs.mendix.com/howto/general/install/)

Document link: [install.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/general/install.md)

## My Issue/Suggestion

Mendix 9.14 has moved from adopt open JDK to eclispse.
Offline installation procedure is obsolete

**Comment by MarkvanMents** [comment]
Thanks for raising this Nicolas @NicolasBRUNAUD 
I've picked up what I believe is the issue and merged it in #4831.
Please let us know if you find any other documentation which is wrong or out of date.
Yours
Mark
