### ISSUE TITLE
Troubleshooting SQL Server - Additional Troubleshooting Issue

### ISSUE THREAD

**Issue by elliotclements-mendix** [mendix/docs#4790]
I'd like to add an additional issue to https://docs.mendix.com/developerportal/deploy/troubleshooting-sql-server/ regarding DataHub

If the Mendix Project contains DataHub entities the Database Synchronization will fail with DLL execution errors when running an on-premise Windows Installation. This took some troubleshooting to understand that the issue was within the mda file and not Database permissions. 

DataHub is not supported on-premises (as far as I'm aware). 

This would need validating but the error message from the console wasn't particularly clear. Removing the DataHub entities (purple) and re-building an mda resolved the issue

**Comment by johannahemminger** [comment]
Hi @elliotclements-mendix , thanks for raising this issue! I will confirm this behavior with the dev team, and then will update the documentation accordingly. Could you provide the error message you received on the console?

**Comment by ako** [comment]
Hi @elliotclements-mendix , do you have a logfile with these DLL execution errors?

**Comment by ako** [comment]
Just to clarify: Data Hub Catalog is not supported on-prem, but this is just a design time tool. Data Hub External Entities are supported on-prem, which is an abstraction no top of REST/OData. On prem apps using External Entities will be able to communicate with apps exposing OData/REST endpoints.

**Comment by elliotclements-mendix** [comment]
That's interesting, so Data Hub entities on-prem shouldn't have any impact on the Database Synchronization...

I don't have the log files to hand.  I'll get the project from my client, run the tests myself and report back. 
You can close this issue in the meantime.

**Comment by johannahemminger** [comment]
Thanks @ako and @elliotclements-mendix , I'll close this for now. If there's anything I need to update in our docs after you run the tests, feel free to open another issue or ping me on Slack. Cheers!
