### ISSUE TITLE
Set Up a Local Selenium Hub

### ISSUE THREAD

**Issue by sbabcoc** [mendix/docs#4796]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Set Up a Local Selenium Hub](https://docs.mendix.com/addons/ats-addon/ht-two-setup-local-selenium-hub/)

Document link: [ht-two-setup-local-selenium-hub.md](https://github.com/mendix/docs/blob/development/content/en/docs/addons/ats-addon/ht/ht-two/ht-two-setup-local-selenium-index/ht-two-setup-local-selenium-hub.md)

## My Issue/Suggestion
This document provides the essential details for setting up a local Selenium 3 Grid collection. You may want to check out my [local-grid-parent](https://github.com/sbabcoc/local-grid-parent) project for a more modular approach. At its core, this project uses the same Selenium APIs; however, I use the individual libraries instead of relying on a massive "uber-JAR". This makes the installation a bit leaner, and I can easily update individual libraries when vulnerabilities or bugs are identified.

**Comment by Adam-Dupaski** [comment]
Hi @sbabcoc thanks for your comments here. I would like to recommend you post your comments as well as your description of and link to your project on the Mendix Idea Forum: https://forum.mendix.com/p/ideas Tha twill help the Mendix community to take a look at your project for its value and best practices. Thanks for contributing to the Mendix community!
Cheers,
Adam
