### ISSUE TITLE
Issue with the dependencies

### ISSUE THREAD

**Issue by Telping** [mendix/docs#4803]
First dependency 

The Microsoft .NET Desktop Runtime 6.0 executable to windowsdesktop-runtime-6.0.3-win-x64.exe

.....is currently not working.... 

Downloading Microsoft .NET Desktop Runtime 6.0.6 and renaming to to windowsdesktop-runtime-6.0.3-win-x64.exe works

Second dependency 

The Java Development Kit 11 (x64) msi to adoptopenjdk_11_x64.msi

Needs to rename to adoptiumjdk_11_x64

**Comment by MarkvanMents** [comment]
Hi Tarig (@Telping)
Thanks for raising this issue.

It is not clear which document you are talking about. If you use the installer online these dependencies should be installed automatically. If you are doing the [installation offline](https://docs.mendix.com/howto/general/install/#offline) step 5 actually mentions that you need to rename these files.
![image](https://user-images.githubusercontent.com/35492184/178432453-6f6ff0f2-b2a9-4a11-b621-1cfd65e9a6d5.png)

Did you come across this issue in a different scenario, or a different document? Or can you suggest a way of making this clearer?
Yours
Mark

**Comment by Telping** [comment]
Thanks for your response Mark. Just heard from one of my team members, that was using the [installation offline ](https://docs.mendix.com/howto/general/install/#offline) documentation, they weren't able to complete the installation with the steps shown. But they did get it to work by replacing the first step:

The Microsoft .NET Desktop Runtime 6.0 executable to windowsdesktop-runtime-6.0.3-win-x64.exe

with the following

Microsoft .NET Desktop Runtime **6.0.6** and renaming to to windowsdesktop-runtime-6.0.3-win-x64.exe works

and the second step

The Java Development Kit 11 (x64) msi to adoptopenjdk_11_x64.msi

The Java Development Kit 11 (x64) msi to **adoptiumjdk_11_x64**

**Comment by MarkvanMents** [comment]
Thanks for raising this Tarig @Telping 
Thanks for helping with the update which I've merged in #4831. Your help in Slack was invaluable in helping me identify what needed to be change.
Please let us know if you find any other documentation which is wrong or out of date.
Yours
Mark
