### ISSUE TITLE
XPath Constraints

### ISSUE THREAD

**Issue by izeno-mubashar-ali** [mendix/docs#4821]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [XPath Constraints](https://docs.mendix.com/refguide/xpath-constraints/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/xpath/xpath-constraints/_index.md)

## My Issue/Suggestion

The below expression doesn't look correct, there is an extra closing bracket 
<html>
<body>

1 | //Sales.User[id = '[%UserRole_Administrator%]']]
-- | --

</body>
</html>
![mendix_xpath_constrains](https://user-images.githubusercontent.com/58155460/179441839-7c6de5cd-ac70-4994-adcc-a0d6114da1b8.png)

**Comment by NatasaKralj** [comment]
Hello @izeno-mubashar-ali!

Thank you for your feedback, it is very appreciated. We've updated the documentation in question. Please don't hesitate to let us know of any other issues you come across.
