### ISSUE TITLE
Outdated Navigation Profiles 

### ISSUE THREAD

**Issue by jdiehl** [mendix/docs#4827]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Navigation](https://docs.mendix.com/refguide/navigation/)

Document link: [navigation.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/menus/view-menu/app-explorer/app/navigation.md)

## My Issue/Suggestion

The navigation profiles are outdated (hybrid should be replaced by native offline)

**Comment by ConnorLand** [comment]
Hello @jdiehl ,

Apologies on the late reply. I partially updated docs on this earlier, but the final changes have been made in this pull request: https://github.com/mendix/docs/pull/6683

Thanks for contributing to the docs Jonathan!

Connor
