### ISSUE TITLE
Push Notifications Connector

### ISSUE THREAD

**Issue by jdiehl** [mendix/docs#4834]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Push Notifications Connector](https://docs.mendix.com/appstore/modules/push-notifications/)

Document link: [push-notifications.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/push-notifications.md)

## My Issue/Suggestion

User struggle to find our Push Notifications guide for native. Please add a prominent link to https://docs.mendix.com/refguide/mobile/using-mobile-capabilities/push-notifications/

**Comment by ConnorLand** [comment]
I have added a prominent link in the intro section.
