### ISSUE TITLE
Nanoflows

### ISSUE THREAD

**Issue by Grasshooper** [mendix/docs#4839]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Nanoflows](https://docs.mendix.com/refguide/nanoflows/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/_index.md)

## My Issue/Suggestion

>> An error event defines a location where the nanoflow will stop and throw an error that occurred earlier. If you call a nanoflow, you may want to know whether any errors occurred within the nanoflow or not.

Correction : I believe Instead of Nanoflow it will be Microflow , as Nanoflow does not have error event.

**Comment by Adam-Dupaski** [comment]
@MariaShaposhnikova please work with @Yiyun333 to resolve this issue.

@Yiyun333 this is an example of feedback work for microflows/nanoflows.

**Comment by MariaShaposhnikova** [comment]
Hi @Grasshooper,
Thanks a lot for your feedback! 
Since the document talks about nanoflows, we have deleted information about the error event that is not available in nanoflows.

Best regards,
Maria
