### ISSUE TITLE
Work with Load Units 

### ISSUE THREAD

**Issue by mkrouwel** [mendix/docs#4845]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Work with Load Units]

Page refers to loadAsPromise, but that does not seem to be available anymore in SDK5.0 and higher.

**Comment by Luyao-Zhang-1** [comment]
@mkrouwel Thank you for raising this issue to us.  
`LoadAsPromise` indeed does not exist in the newer versions of the SDK. The developer now is planning to rewrite the sample code in this page and convert the callbacks to promises. We will update the doc accordingly soon.

**Comment by Luyao-Zhang-1** [comment]
@mkrouwel We updated [Work with Load Units & Elements](https://docs.mendix.com/apidocs-mxsdk/mxsdk/loading-units-and-elements/). You can find the latest information and sample code in the doc. Thank you for raising this issue. Please continue letting us know if you find anything outdated in the documentation in the future.
