### ISSUE TITLE
Set Up a GitHub Repo to Publish a Marketplace Item

### ISSUE THREAD

**Issue by jdiehl** [mendix/docs#4850]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Set Up a GitHub Repo to Publish a Marketplace Item](https://docs.mendix.com/howto/collaboration-requirements-management/set-up-repo/)

Document link: [set-up-repo.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/collaboration-requirements-management/set-up-repo.md)

## My Issue/Suggestion

Can we upgrade this to pluggable widgets?

**Comment by ConnorLand** [comment]
@jdiehl this actually ties into another issue I need to solve: #4846 . A user recently asked about the Widget Boilerplate and I had to ask 5 people before figuring out the following;

It seems that the Widget Boilerplate was made by Jelte and is currently owned and maintained by nobody. 

If we are going to replace the widget boilerplate section 4 to a pluggable widget recommendation, shall I work with a dev to create a new pluggable widget template and drop that in section 4?

**Comment by jdiehl** [comment]
You actually should not use any boilerplate repo to publish a widget for the marketplace but instead use the process described here: https://docs.mendix.com/howto/extensibility/create-a-pluggable-widget-one/

**Comment by ConnorLand** [comment]
Good recommendation. I'll do a roundup of all Widget Boilerplate mentions and see if they can all be replaced by Create a Pluggable Widget.

**Comment by ConnorLand** [comment]
I had already done much of the work for this feedback item. The final Widget Boilerplate mentions have been replaced in this commit: https://github.com/mendix/docs/commit/20a9b9080dcd06d591a0159ff9d85081598cca32

The older docs look better now.
