### ISSUE TITLE
Run Mendix on Kubernetes

### ISSUE THREAD

**Issue by elliotclements-mendix** [mendix/docs#4853]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Run Mendix on Kubernetes](https://docs.mendix.com/developerportal/deploy/run-mendix-on-kubernetes/)

Document link: [run-mendix-on-kubernetes.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md)

## My Issue/Suggestion

The documentation contains limited information on how persistence storage is attached to the app container despite it being mentioned as a topic the guide will teach you about. 

"**This how-to will teach you how to do the following: Attach persistence storage to the app container**"

Can we include something such as the following to make this topic clearer. There doesn't seem to be any documentation how PVs work with the docker buildpack on any other pages: 

"The current version of Docker Buildpack stores files in /opt/mendix/build/data/files. If a PV is mounted into this path in the app container, any uploaded files will be stored in that persistent volume.
Please note that the CF Buildpack will try to set file permissions in the volume before it starts the app, so it should have permissions to do that."

See internal discussion https://mendix.slack.com/archives/C0161BEMQ4B/p1658416780821589

**Comment by MarkvanMents** [comment]
Hi Elliot (@elliotclements-mendix )
Dmitrii has helped me tidy up this document and add the information about PVs.
Thanks for raising this issue - it also uncovered some additional issues so it was really helpful for that.
Please let us know if you spot other improvements which could be made to the documentation.
Mark

**Comment by elliotclements-mendix** [comment]
Excellent, great to hear!
