### ISSUE TITLE
PostgreSQL on Amazon (AWS) for SAP Business Technology Platform

### ISSUE THREAD

**Issue by pietervercammen** [mendix/docs#4859]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [PostgreSQL on Amazon (AWS) for SAP Business Technology Platform](https://docs.mendix.com/partners/sap/sap-postgresql-on-aws/)

Document link: [sap-postgresql-on-aws.md](https://github.com/mendix/docs/blob/development/content/en/docs/partners/sap/sap-postgresql-on-aws.md)

## My Issue/Suggestion

Are we still using t2 and m4 instances for databases?

**Comment by MarkvanMents** [comment]
Hi Pieter,

Thanks for your question.

Apparently, SAP has removed the support for AWS RDS PostgreSQL, so I am removing this document completely in PR #4922. If you still need an answer to this, let me know and I will forward the question to the appropriate development team. Or you can ask on the [Mendix Forum](https://forum.mendix.com/).

Yours
Mark van Ments
