### ISSUE TITLE
Native App Prerequisites and Troubleshooting

### ISSUE THREAD

**Issue by janwiebe-jump** [mendix/docs#4865]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Native App Prerequisites and Troubleshooting](https://docs.mendix.com/refguide/mobile/getting-started-with-mobile/prerequisites/)

Document link: [prerequisites.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/mobile/getting-started-with-mobile/prerequisites.md)

## My Issue/Suggestion
The Dropbox link to the Android app doesn't work anymore. @ConnorLand can you look into it, since you changed the page?

**Comment by ConnorLand** [comment]
Hello,

Apologies for taking so long to reply to you. The link was fixed.

Thank you for contributing to the documentation,

Connor
