### ISSUE TITLE
Missing Microflow aspose image size pixels

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/docs#488]
https://github.com/mendix/docs/blob/development/refguide/java-actions.md line 81
"Expose as Microflow action" there is no suggestion for the icon size.

**Comment by Adam-Dupaski** [comment]
I Andries, do you have a suggestion for this?

**Comment by Andries-Smit** [comment]
No. Don't know. I was trying to find out from the documentation ;)

**Comment by Adam-Dupaski** [comment]
Documentation updated: https://docs.mendix.com/refguide/java-actions#expose-as-microflow-action

Closing this issue.
