### ISSUE TITLE
OPC UA

### ISSUE THREAD

**Issue by ifo234** [mendix/docs#4898]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [OPC UA](https://docs.mendix.com/appstore/connectors/opc-ua/)

Document link: [opc-ua.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/connectors/opc-ua.md)

## My Issue/Suggestion

Hi, the following link is broken:
.....
"You can check out a [sample module](https://marketplace.mendix.com/link/component/114876/), which gives an example of how the connector can be used."
.....

**Comment by Luyao-Zhang-1** [comment]
@ifo234 Thank you for contacting us. Sorry that the link didn't work for you. I just checked the link myself and it works. Is it still broken on your side?

**Comment by Luyao-Zhang-1** [comment]
Hi @ifo234 , I checked the link for multiple times and indeed it sometimes doesn't work. I [updated the doc](https://github.com/mendix/docs/pull/4971/files) with a new link that is stable. Thank you for helping us improve the doc by reporting this issue. 
If you further see anything that is not working or out of date in the documentation, please feel free to open an issue. Thank you again.
