### ISSUE TITLE
Language Settings

### ISSUE THREAD

**Issue by eduard-mendix** [mendix/docs#4902]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Language Settings](https://docs.mendix.com/refguide/language-settings/)

Document link: [language-settings.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/menus/translatable-texts/language-settings.md)

## My Issue/Suggestion
The screenshot of languages supported is showing Russian, Russia.
Maybe to be on the political safe side we would like to change that into a different language.

**Comment by Adam-Dupaski** [comment]
Hi @eduard-mendix thanks for the feedback, we have resolved this in #5066
