### ISSUE TITLE
Check Box

### ISSUE THREAD

**Issue by TrentG77** [mendix/docs#4905]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Check Box](https://docs.mendix.com/refguide/check-box/)

Document link: [check-box.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/pages/input-widgets/check-box.md)

## My Issue/Suggestion

About two months ago we started seeing little black boxes appear randomly on the screen when making a selection on a checkbox. I believe it is a styling issue that emerged out of nowhere. We had to turn the checkbox outline off for this to not occur.

![LittleBlackBoxesIssue](https://user-images.githubusercontent.com/111001812/183965209-034fe96f-b7c1-4bf5-ab06-0602e57591a8.JPG)

**Comment by ConnorLand** [comment]
Hello @TrentG77 . Can you share your Atlas version with me? 

An issue very similar to this was fixed in Atlas Core v3.4.0. If you are using a lower version, upgrading Atlas may solve it.

**Comment by TrentG77** [comment]
Version 3.0.0


TRENT LEMKUS
ASSOCIATE
RAPID APPLICATION DEVELOPMENT

mobile: 2079399513 | email: ***@***.******@***.***> | eastern time | www.epiuse.com<https://www.epiuse.com/> | disclaimer<https://www.epiuse.com/disclaimer/>

A member of groupelephant.com<https://groupelephant.com/>, going Beyond Corporate Purpose with Elephants, Rhinos & People (ERP).
For more information about ERP, please visit erp.ngo.


[https://uploads-ssl.webflow.com/602f5d229e00f192873e9968/60db31a51b4cc411b7e6bb9c_email-banner-erp.png]
________________________________

**Comment by ConnorLand** [comment]
Ok understood. If possible, please upgrade Atlas and let me know if that fixes your issue. Thanks for sharing your feedback with documentation.
