### ISSUE TITLE
Example from the Generate Code from Model are outdated, several API calls have changed. 

### ISSUE THREAD

**Issue by jaspervanderhoek** [mendix/docs#4927]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Generate Code from the Model](https://docs.mendix.com/apidocs-mxsdk/mxsdk/generating-code-from-the-model/)

Document link: [generating-code-from-the-model.md](https://github.com/mendix/docs/blob/development/content/en/docs/apidocs-mxsdk/mxsdk/sdk-howtos/generating-code-from-the-model.md)

## My Issue/Suggestion
APIs have changed:
  Tokens work different, Project is renamed to Ap0, commit function is different, those are just the things I ran into in a quick review.

**Comment by Luyao-Zhang-1** [comment]
@jaspervanderhoek Thank you for reporting this issue to us. I contacted the developer and they will re-review the whole doc. After that, I will update the doc with the verified information.

**Comment by Luyao-Zhang-1** [comment]
@jaspervanderhoek The [doc](https://docs.mendix.com/apidocs-mxsdk/mxsdk/generating-code-from-the-model/) is updated. Thank you for reporting this issue to us. 

Please continue to let us know in the future if you see documentation that can be improved. Thank you!
