### ISSUE TITLE
Title of Javascript serializer howto suggests a different purpose 

### ISSUE THREAD

**Issue by dlhartveld** [mendix/docs#4932]
The page `Generate Code from the Model` [see 1 below] is actually about generating an SDK script based on an existing model. A customer pointed out this page to me and asked how to use it to generate something from the model but that is not what this page is about.

I suggest to rename this page to more accurately represent what you can learn here.

1. https://docs.mendix.com/apidocs-mxsdk/mxsdk/generating-code-from-the-model/

**Comment by Luyao-Zhang-1** [comment]
@dlhartveld We have renamed the doc in this [PR](https://github.com/mendix/docs/pull/4965/files) to better reflect its content. Thank you for reporting this issue.
