### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Grasshooper** [mendix/docs#4935]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Calendar](https://docs.mendix.com/appstore/widgets/calendar/)

Document link: [calendar.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/widgets/calendar.md)

## My Issue/Suggestion : There is lots of query in forum regarding the documentation for calendar configuration is not fully  described. Its just a suggestion it would be nice if the documentation contains more description , however I am also planning to write a blog about this in coming days to provide step by step process on how to configure the calendar widget.

Thanks

**Comment by ConnorLand** [comment]
Hello @Grasshooper ,

Apologies for the late reply. I just wanted you to know that expanding our most popular widget documents has been in our planning. Now I am enacting your suggestion and seeing what can be added to the Calendar document. If you have any specific recommendations for what you'd find most useful, please let me know and I'll add it if I can.

Thanks,

Connor

**Comment by ConnorLand** [comment]
Hi @Grasshooper ,

I have worked with the devs to add a configuration section to the widget. It gives a typical configuration use case with step-by-step guidance: https://github.com/mendix/docs/pull/6898 

Thank you for your suggestion. I know a lot of other users have similar questions as yours. In the future I will try to add more configuration sections to major widget docs.

Connor
