### ISSUE TITLE
9.6

### ISSUE THREAD

**Issue by toonverschoor** [mendix/docs#4937]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [9.6](https://docs.mendix.com/releasenotes/studio-pro/9.6/)

Document link: [9.6.md](https://github.com/mendix/docs/blob/development/content/en/docs/releasenotes/studio-pro/9/9.6.md)

## My Issue/Suggestion
The list of Fixes for 9.6.9 and 9.6.8 have some duplicates - at least the lastn three. Is this on purpose?

**Comment by Adam-Dupaski** [comment]
Thanks @toonverschoor this is not on purpose, sometimes we miss the duplicates. I've corrected in https://github.com/mendix/docs/commit/7fe62bd3571c4ef39294d7d864caab9192ea7201 . Thanks for the feedback!
