### ISSUE TITLE
Mathematical Function Calls

### ISSUE THREAD

**Issue by weissn-mondi** [mendix/docs#4966]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Mathematical Function Calls](https://docs.mendix.com/refguide/mathematical-function-calls/)

Document link: [mathematical-function-calls.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/expressions/mathematical-function-calls.md)

## My Issue/Suggestion

The pow function behaves very differently in Nanoflows, due to the use of big.js. The pow function in big.js requires an integer as the exponent, which is not clearly documented, neither here in the documentation, nor in the modeler itself (allows decimal values to be used in the pow function, which leads to runtime errors).

**Comment by Adam-Dupaski** [comment]
@NatasaKralj please work with @Yiyun333 to resolve this issue.

9.17 had an update for `pow`: https://docs.mendix.com/releasenotes/studio-pro/9.17/#fixes

**Comment by Robinfr** [comment]
Yes, we have changed this in 9.17. When a decimal is used an exponent, we don't use Big.js but fallback to inprecise calculation using regular JavaScript. The same happens in the runtime (but with Java).

**Comment by NatasaKralj** [comment]
Verified with @Robinfr , added alert and Javascript (instead of just Java) to function information. See commit [add3ead](https://github.com/mendix/docs/commit/add3eadcd8082503186dbe935f3ac5cf08d01619)
