### ISSUE TITLE
9.12 xpath [id = '[%CurrentUser%]'] exception

### ISSUE THREAD

**Issue by fuile** [mendix/docs#4968]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [9.12](https://docs.mendix.com/releasenotes/studio-pro/9.12/)

Document link: [9.12.md](https://github.com/mendix/docs/blob/development/content/en/docs/releasenotes/studio-pro/9/9.12.md)

## My Issue/Suggestion

mendixapp_1  | ERROR - TaskQueue: Failed to execute com.mendix.modules.queue.ScheduledEvents$WrappedTask@1e89adae from task queue 'System.ScheduledEventsQueue'.
mendixapp_1  | ERROR - TaskQueue: com.mendix.modules.microflowengine.MicroflowException: com.mendix.systemwideinterfaces.MendixRuntimeException: com.mendix.connectionbus.ConnectionBusRuntimeException: An exception 
has occurred for the following request(s):
mendixapp_1  |  InternalXPathTextGetRequest (depth = 0, amount = 1): //AccountManagement.Account[id = '[%CurrentUser%]']
mendixapp_1  |  at DisplayChart.DS_WeekEfficiency (RetrieveByXPath : 'Retrieve Account from database')
mendixapp_1  |
mendixapp_1  | Advanced stacktrace:
mendixapp_1  |  at com.mendix.modules.microflowengine.MicroflowUtil.processException(MicroflowUtil.java:83)
mendixapp_1  |
mendixapp_1  | Caused by: com.mendix.core.CoreRuntimeException: com.mendix.systemwideinterfaces.MendixRuntimeException: com.mendix.connectionbus.ConnectionBusRuntimeException: An exception has occurred for the foll
owing request(s):
mendixapp_1  |  InternalXPathTextGetRequest (depth = 0, amount = 1): //AccountManagement.Account[id = '[%CurrentUser%]']
mendixapp_1  |  at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:110)
mendixapp_1  |
mendixapp_1  | Caused by: com.mendix.systemwideinterfaces.MendixRuntimeException: com.mendix.connectionbus.ConnectionBusRuntimeException: An exception has occurred for the following request(s):
mendixapp_1  |  InternalXPathTextGetRequest (depth = 0, amount = 1): //AccountManagement.Account[id = '[%CurrentUser%]']
mendixapp_1  |  at com.mendix.util.classloading.Runner$.withContextClassLoader(Runner.scala:23)
mendixapp_1  |
mendixapp_1  | Caused by: com.mendix.connectionbus.ConnectionBusRuntimeException: An exception has occurred for the following request(s):
mendixapp_1  |  InternalXPathTextGetRequest (depth = 0, amount = 1): //AccountManagement.Account[id = '[%CurrentUser%]']
mendixapp_1  |  at com.mendix.connectionbus.RequestAnalyzer.doRequest(RequestAnalyzer.scala:35)
mendixapp_1  |
mendixapp_1  | Caused by: com.mendix.systemwideinterfaces.MendixRuntimeException: [%CurrentUser%] token cannot be used in a system session.
mendixapp_1  |  at com.mendix.basis.conf.Tokens$.resolveCurrentUser$1(Tokens.scala:50)
mendixapp_1  |  at com.mendix.basis.conf.Tokens$.$anonfun$resolveTokensInfo$2(Tokens.scala:60)
mendixapp_1  |  at com.mendix.basis.conf.Tokens$.resolveTokens(Tokens.scala:38)
mendixapp_1  |  at com.mendix.basis.conf.Tokens.resolveTokens(Tokens.scala)
mendixapp_1  |  at com.mendix.basis.impl.MxRuntimeImplBase$2.lambda$createTokenValueResolver$0(MxRuntimeImplBase.java:444)
mendixapp_1  |  at com.mendix.datastorage.handler.steps.TokenValueResolutionExecutor.execute(TokenValueResolutionExecutor.scala:13)
mendixapp_1  |  at com.mendix.datastorage.handler.cache.QueryParameterizerImpl$$anonfun$1.applyOrElse(QueryParameterizer.scala:75)
mendixapp_1  |  at com.mendix.datastorage.handler.cache.QueryParameterizerImpl$$anonfun$1.applyOrElse(QueryParameterizer.scala:66)
mendixapp_1  |  at com.mendix.datastorage.oqltree.transformations.Transformer$.transformNode(Transformer.scala:168)
mendixapp_1  |  at com.mendix.datastorage.oqltree.expressions.BinaryExpression.mapChildren(Expression.scala:93)
mendixapp_1  |  at com.mendix.datastorage.oqltree.transformations.Transformer$.transformNode(Transformer.scala:166)
mendixapp_1  |  at com.mendix.datastorage.query.plans.Where.mapChildren(queryExpressions.scala:243)
mendixapp_1  |  at com.mendix.datastorage.oqltree.transformations.Transformer$.transformNode(Transformer.scala:166)
mendixapp_1  |  at com.mendix.datastorage.oqltree.transformations.Transformer$.$anonfun$transformOption$2(Transformer.scala:177)
mendixapp_1  |  at scala.Option.map(Option.scala:242)
mendixapp_1  |  at com.mendix.datastorage.oqltree.transformations.Transformer$.transformOption(Transformer.scala:177)
mendixapp_1  |  at com.mendix.datastorage.query.plans.Select.mapChildren(queryExpressions.scala:201)
mendixapp_1  |  at com.mendix.datastorage.oqltree.transformations.Transformer$.transformNode(Transformer.scala:166)
mendixapp_1  |  at com.mendix.datastorage.oqltree.transformations.Transformer.withCustomContext(Transformer.scala:20)
mendixapp_1  |  at com.mendix.datastorage.oqltree.transformations.Transformer.withContext(Transformer.scala:17)
mendixapp_1  |  at com.mendix.datastorage.handler.cache.QueryParameterizerImpl.parameterize(QueryParameterizer.scala:66)
mendixapp_1  |  at com.mendix.datastorage.handler.QueryHandler.doCachedHandling(QueryHandler.scala:58)
mendixapp_1  |  at com.mendix.connectionbus.retrieve.OqlRequestHandler.doNewQueryHandling(OqlRequestHandler.scala:198)
mendixapp_1  |  at com.mendix.connectionbus.retrieve.OqlRequestHandler.handleRequest(OqlRequestHandler.scala:59)
mendixapp_1  |  at com.mendix.connectionbus.retrieve.DataStoreCaller.processOqlGetRequest(DataStoreCaller.scala:31)
mendixapp_1  |  at com.mendix.connectionbus.retrieve.DataStoreCaller.$anonfun$getResult$1(DataStoreCaller.scala:26)
mendixapp_1  |  at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
mendixapp_1  |  at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
mendixapp_1  |  at scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:35)
mendixapp_1  |  at com.mendix.connectionbus.retrieve.DataStoreCaller.getResult(DataStoreCaller.scala:26)
mendixapp_1  |  at com.mendix.connectionbus.retrieve.GetRequestHandler.doOtherRequests(GetRequestHandler.scala:69)
mendixapp_1  |  at com.mendix.connectionbus.retrieve.GetRequestHandler.doRequest(GetRequestHandler.scala:29)
mendixapp_1  |  at com.mendix.connectionbus.RequestAnalyzer.doRequest(RequestAnalyzer.scala:30)
mendixapp_1  |  at com.mendix.connectionbus.ConnectionBusImpl.doRequest(ConnectionBusImpl.scala:470)
mendixapp_1  |  at com.mendix.basis.action.user.RetrieveXPathRawAction.executeAction(RetrieveXPathRawAction.scala:66)
mendixapp_1  |  at com.mendix.basis.action.user.RetrieveXPathAction.executeAction(RetrieveXPathAction.scala:40)
mendixapp_1  |  at com.mendix.basis.action.user.RetrieveXPathAction.executeAction(RetrieveXPathAction.scala:12)
mendixapp_1  |  at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:58)
mendixapp_1  |  at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
mendixapp_1  |  at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
mendixapp_1  |  at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.java:56)
mendixapp_1  |  at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:106)
mendixapp_1  |  at com.mendix.util.classloading.Runner$.withContextClassLoader(Runner.scala:20)
mendixapp_1  |  at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:105)
mendixapp_1  |  at com.mendix.basis.component.ExecutionCore.doExecuteSync(ExecutionCore.scala:147)
mendixapp_1  |  at com.mendix.basis.component.ExecutionCore.doExecuteSync$(ExecutionCore.scala:146)
mendixapp_1  |  at com.mendix.basis.component.InternalCore.doExecuteSync(InternalCore.scala:24)
mendixapp_1  |  at com.mendix.basis.component.DataXPathCore.retrieveXPathQuery(DataXPathCore.scala:90)
mendixapp_1  |  at com.mendix.basis.component.DataXPathCore.retrieveXPathQuery$(DataXPathCore.scala:68)
mendixapp_1  |  at com.mendix.basis.component.InternalCore.retrieveXPathQuery(InternalCore.scala:24)
mendixapp_1  |  at com.mendix.modules.microflowengine.actions.mxobject.RetrieveByXPathAction.execute(retrieveActions.scala:85)
mendixapp_1  |  at com.mendix.modules.microflowengine.actions.mxobject.RetrieveByXPathAction.execute(retrieveActions.scala:48)
mendixapp_1  |  at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.$anonfun$execute$1(MicroflowObject.scala:32)
mendixapp_1  |  at scala.Option.flatMap(Option.scala:283)
mendixapp_1  |  at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.scala:29)
mendixapp_1  |  at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.$anonfun$executeAfterBreakingIfNecessary$2(MicroflowImpl.scala:167)
mendixapp_1  |  at scala.Option.flatMap(Option.scala:283)
mendixapp_1  |  at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.scala:167)
mendixapp_1  |  at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.scala:114)
mendixapp_1  |  at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:58)
mendixapp_1  |  at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
mendixapp_1  |  at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:48)
mendixapp_1  |  at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.java:56)
mendixapp_1  |  at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.$anonfun$runMonitoredAction$1(CoreActionHandlerImpl.scala:59)
mendixapp_1  |  at com.mendix.basis.actionmanagement.ActionMonitoring$.$anonfun$monitor$1(ActionMonitoring.scala:49)
mendixapp_1  |  at com.mendix.util.classloading.Runner$.withContextClassLoader(Runner.scala:20)
mendixapp_1  |  at com.mendix.basis.actionmanagement.ActionMonitoring$.monitor(ActionMonitoring.scala:49)
mendixapp_1  |  at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.runMonitoredAction(CoreActionHandlerImpl.scala:59)
mendixapp_1  |  at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:46)
mendixapp_1  |  at com.mendix.core.actionmanagement.internal.InternalCoreAction.call(InternalCoreAction.java:56)
mendixapp_1  |  at com.mendix.basis.actionmanagement.ActionManager.$anonfun$executeSync$2(ActionManager.scala:106)
mendixapp_1  |  at com.mendix.util.classloading.Runner$.withContextClassLoader(Runner.scala:20)
mendixapp_1  |  at com.mendix.basis.actionmanagement.ActionManager.executeSync(ActionManager.scala:105)
mendixapp_1  |  at com.mendix.basis.actionmanagement.MicroflowCallBuilderImpl.execute(MicroflowCallBuilderImpl.scala:62)
mendixapp_1  |  at com.mendix.modules.queue.MicroflowTask.$anonfun$execute$1(MicroflowTask.scala:34)
mendixapp_1  |  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
mendixapp_1  |  at scala.util.Try$.apply(Try.scala:210)
mendixapp_1  |  at com.mendix.modules.queue.MicroflowTask.execute(MicroflowTask.scala:31)
mendixapp_1  |  at com.mendix.modules.queue.ScheduledEvents$WrappedTask.$anonfun$execute$1(ScheduledEvents.scala:136)
mendixapp_1  |  at com.mendix.basis.actionmanagement.UserScheduledAction$.logExecution(UserScheduledAction.scala:59)
mendixapp_1  |  at com.mendix.modules.queue.ScheduledEvents$WrappedTask.execute(ScheduledEvents.scala:136)
mendixapp_1  |  at com.mendix.modules.queue.TaskQueueDispatcher.executeTask(TaskQueueDispatcher.scala:155)
mendixapp_1  |  at com.mendix.modules.queue.TaskQueueDispatcher.$anonfun$dispatchTask$1(TaskQueueDispatcher.scala:149)
mendixapp_1  |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
mendixapp_1  |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
mendixapp_1  |  at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Adam-Dupaski** [comment]
Hi, thanks for the feedback, but this is a channel for feedback on documentation. Please send your stack trace to https://support.mendix.com/hc/en-us in a request if necessary. Thanks.
