### ISSUE TITLE
Ability to change To,CC,BCC when using templates

### ISSUE THREAD

**Issue by CAPE-Rudolf** [mendix/docs#5006]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [Email Connector](https://docs.mendix.com/appstore/connectors/email-connector/)

Document link: [email-connector.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/connectors/email-connector.md)

## My Issue/Suggestion

It seems like it's not possible to add To,CC and BCC in microflows without altering the original module when using templates.
The Java code creates the mail object and calls the microflow in Mendix. It just uses the to,cc,bcc info from the template but filling those in at the template level was not needed.
Am I missing something or is the only way really copying the ACT_SendEmail and altering the email message there?
Because this would mean also editing the ACT_SendEmailFromJava.
Hope I made clear what I mean.

**Comment by johannahemminger** [comment]
Hi @CAPE-Rudolf , thanks for raising this issue. 

I have confirmed with the development team that it is possible to provide To, CC, and BBC during runtime. The **Send email with template** Java action takes the EmailTemplate object as a parameter. In your microflow, just change the EmailTemplate object and set the desired values for the attributes, then pass the same EmailTemplate object as a parameter to the Java action. The sample microflow **Sample_ACT_SendEmailWithTemplate** can be used as a reference (you will then use a **Change object** to alter the EmailTemplate object). 

I will add this information as well as other clarifications and updates to the documentation; feel free to track the progress in this PR: https://github.com/mendix/docs/pull/5128. 

I will mark this as resolved, but please feel free to open another pull request or issue if there are any other documentation improvements we can make!
