### ISSUE TITLE
consume-a-simple-web-service

### ISSUE THREAD

**Issue by axelclevr** [mendix/docs#5024]
Page link: [consume-a-simple-web-service](https://docs.mendix.com/howto/integration/consume-a-simple-web-service/)

Document link: [consume-a-simple-web-service.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/integration/consume-a-simple-web-service.md)

## My Issue/Suggestion
There's an error in the screenshot for step 3. Quotes are shown (backticks), but there should be no quotes.

**Comment by johannahemminger** [comment]
Hi @axelclevr, 

Good eye, thanks for opening this issue. I am removing the screenshot so it doesn't lead to any confusion. Please feel free to open another issue or pull request if you see any other fixes or improvements in our documentation. Much appreciated!
