### ISSUE TITLE
log-message improvement suggestion: not to use constants

### ISSUE THREAD

**Issue by johanflikweert** [mendix/docs#5027]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [log-message](https://docs.mendix.com/refguide/log-message/)

Document link: [log-message.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/log-message.md)

## My Issue/Suggestion
Please revise the advice of putting the name of log nodes in constants, as you describe in part 3.2. The current setup will lead to unmanageable situations where the log node may be different per environment, while you almost never want this to change the default at all.
Alternatively, either:

-  implement the possibility to make constants not configurable (https://forum.mendix.com/link/ideas/2234) or have a seperate document type for defining log nodes (https://forum.mendix.com/link/ideas/297). 
- or advise to use the getKey() of some enumeration called enum_lognode, as this won't show up in configuring the environments and reaches the same effect to have a reusable value which is configured at one central place. This is the recommended way that is described in the learning path: https://academy.mendix.com/link/modules/355/lectures/2837/5.2-Setting-Up-Logging

**Comment by Yiyun333** [comment]
Hi Johan,

Thanks a lot for your feedback. We verified it and deleted the advice about constants that is indeed not the best practice. 

Best regards,
Yiyun
