### ISSUE TITLE
customize-styling

### ISSUE THREAD

**Issue by RobinH81** [mendix/docs#5034]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [customize-styling](https://docs.mendix.com/howto/front-end/customize-styling-new/)

Document link: [customize-styling-new.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/front-end/atlas-ui/customize-styling-new.md)

## My Issue/Suggestion
I think quotes are missing in the last couple of lines.

**Comment by ConnorLand** [comment]
Hi @RobinH81 . Can you please specify which lines you're describing?

**Comment by RobinH81** [comment]
11.2 Using Local Font Files
Open your Mendix app’s theme/web/custom-variables.scss file and locate the following line:

$font-family-import: https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700
Sass (Scss)
Replace that line with the following code:

$font-family-import: ./fonts/open-sans.css
Sass (Scss)
Then, save your changes. Run your app and you should see fonts rendered correctly

**Comment by RobinH81** [comment]
"s around the url and before and after the './fonts/open-sans.css'

**Comment by ConnorLand** [comment]
Thanks @RobinH81 ! I've solved the error your pointed out (as well as one other one) in this PR: https://github.com/mendix/docs/pull/5036

Thank you for using the Docs Feedback widget. In the future, you can also stage doc changes directly by making a pull request.

Thanks for contributing to the Mendix documentation,

Connor
