### ISSUE TITLE
deep-link

### ISSUE THREAD

**Issue by Rob-de-Leeuw** [mendix/docs#5043]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [deep-link](https://docs.mendix.com/appstore/modules/deep-link/)

Document link: [deep-link.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/deep-link.md)

## My Issue/Suggestion
The mention page link to docs.mendix.com for deep-link does not mention if it is safe to upgrade deeplink for your app.
While upgrading from MX8 to MX9, we need to know if upgrading deeplink will not break existing links.
Can this be added to the documentation?
Thanks much in advance!

**Comment by RCatersels** [comment]
I think it already is in the documentation. See paragraph 4 troubleshooting. That is the only breaking change for upgrading from Mx8 to Mx9. So if you also have SSO enabled in your environment you should change this.

**Comment by Luyao-Zhang-1** [comment]
@RCatersels Thank you for the clarification and for mentioning paragraph 4 troubleshooting. Here it is probably implied that you can upgrade from Mx 8 to Mx 9. We can probably still add a note to make this more clear to users. Here I added a note [here](https://github.com/mendix/docs/pull/5050) just to explicitly say that it's safe to upgrade from Mx 8 to Mx 9 without breaking existing links.

**Comment by Luyao-Zhang-1** [comment]
@Rob-de-Leeuw Thank you for your feedback. I added a note into the doc to make it clear that the existing links won't break if you upgrade from Mx8 to Mx9.
