### ISSUE TITLE
native-mobile-resources

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#5057]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [native-mobile-resources](https://docs.mendix.com/appstore/modules/native-mobile-resources/)

Document link: [native-mobile-resources.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/native-mobile-resources.md)

## My Issue/Suggestion
The page lists the UI widgets but has no documentation at all about nanoflow actions.  These are also not described in the Github readme which just sends us back to this page.  In particular, I was trying to understand more about the native register deeplink action.  This is a javascript action and there are some comments in the documentation tab that would benefit from some elaboration but there is no more information that I can find anywhere.

**Comment by ConnorLand** [comment]
Hi @Chris-Karona,

We have recently added a [Nanoflow Actions](https://docs.mendix.com/appstore/modules/native-mobile-resources/#3-nanoflow-actions) section to the Native Mobile Resources document to help users like yourself. 

There is also a [Native Deep Link Category](https://docs.mendix.com/appstore/modules/native-mobile-resources/#35-native-deep-link-category) section to address your specific use-case.

Thank you for making your voice heard. Feedback like yours lead directly to these improvements. 

Connor
