### ISSUE TITLE
template-grid-document-template

### ISSUE THREAD

**Issue by gertbronkhorst** [mendix/docs#5059]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [template-grid-document-template](https://docs.mendix.com/refguide/template-grid-document-template/)

Document link: [template-grid-document-template.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/resources/document-templates/template-grid-document-template.md)

## My Issue/Suggestion
Give a clear example when and how I can use a microflow. I have an object x, which have multiple lines (another entity, associated to x) Each line have an enum attribute. In my case there are 3 different enum values, so I want to gather all information with type 1 and in another template grid I want to gather information with type 2 and so on. Normaly I make a microflow and retrieve from x and next a list operation filter and return the gathered list.

**Comment by gertbronkhorst** [comment]
See my issue / suggestion. Thanks in advance.

**Comment by Yiyun333** [comment]
@gertbronkhorst Thank you for your suggestion. We already have a similar doc on how to use microflow data source on a data grid: [Microflow Source]( https://docs.mendix.com/refguide/microflow-source/). Will this be sufficient for you?

**Comment by Yiyun333** [comment]
@gertbronkhorst If you've seen my previous message, please let us know whether the doc [Microflow Source](https://docs.mendix.com/refguide/microflow-source/) is sufficent to present the above example you've given. Many thanks!

**Comment by Yiyun333** [comment]
@gertbronkhorst since we haven't received your response yet, we will close this issue for now. If you are not satisfied with our solution, please raise the issue again. Thanks!
