### ISSUE TITLE
use-marketplace-content-in-studio-pro

### ISSUE THREAD

**Issue by RobinH81** [mendix/docs#5089]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [use-marketplace-content-in-studio-pro](https://docs.mendix.com/appstore/general/app-store-content/)

Document link: [app-store-content.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/general/app-store-content.md)

## My Issue/Suggestion

Please add paragraph on how updated Marketplace content is presented. Pushed, pulled or else?

**Comment by Adam-Dupaski** [comment]
Hi @RobinH81 thanks for your feedback. I don't quite understand what you'd like to know here, though. Are you asking about how content appears in Marketplace in Studio Pro?

**Comment by RobinH81** [comment]
Wow! New SLA? My comment back from Sept '22 answered two weeks ago and now closed as completed? I am into different kind of work at the moment (at the same company). Mendix isn't part of my work now unfortunately, so a two weeks term seems te me as a little inappropriate, but hey, SLA's stil have a higher priority than customer satisfaction right? Not personal! Here at our company exactly the same b*llsh*t prio unfortunately.

**Comment by Adam-Dupaski** [comment]
Hi @RobinH81 thank you for your comments. I can reopen this feedback item if you can address my request for more info above: 

> I don't quite understand what you'd like to know here, though. Are you asking about how content appears in Marketplace in Studio Pro?
