### ISSUE TITLE
extensibility

### ISSUE THREAD

**Issue by ZeoSmeijsters** [mendix/docs#5101]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [extensibility](https://docs.mendix.com/howto/extensibility/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/extensibility/_index.md)

## My Issue/Suggestion

Looking for documentation to extent the Mexdix Studio Pro with a new panel. See there is a possibility to use base ExtentionApi classes, do you call/inject them using reflexion?

**Comment by ConnorLand** [comment]
Hello @ZeoSmeijsters ,

Apologies for the delay in replying. To learn more about using the extension API to extend your Studio Pro panels, please post a question on the [Mendix Forum](https://forum.mendix.com/p/community).

For more information on panels, see the [Studio Pro Overview.](https://docs.mendix.com/refguide/studio-pro-overview/)

Thank you for reaching out to documentation,

Connor
