### ISSUE TITLE
consume-a-rest-service

### ISSUE THREAD

**Issue by ricketyrack** [mendix/docs#5109]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [consume-a-rest-service](https://docs.mendix.com/howto/integration/consume-a-rest-service/)

Document link: [consume-a-rest-service.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/integration/consume-a-rest-service.md)

## My Issue/Suggestion
Please provide information on how many objects can be returned.  There appears to be a 100 object limit by default.  Also, please include how to increase this if possible.

**Comment by johannahemminger** [comment]
Hi @ricketyrack , thanks for opening this issue. I checked with the development team and they confirmed that there is no 100 object limit by default. I would suggest looking on the Mendix forums or opening a ticket with Mendix Support. For now I will mark this issue as closed, but please don't hesitate to let us know if there's anything else in the documentation that can be improved!

**Comment by johannahemminger** [comment]
Hi again @ricketyrack , just to clarify my response above: there should be no limit, so it's strange that you are running into one. Checking the Mendix Forum or contacting Support might provide more clarity on why you are running into a limit.

**Comment by johannahemminger** [comment]
One more suggestion @ricketyrack -- the limit could be on the side of the REST service you're calling. On the Mendix side there is no limit.
