### ISSUE TITLE
rich-text

### ISSUE THREAD

**Issue by cerego** [mendix/docs#5119]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [rich-text](https://docs.mendix.com/appstore/widgets/rich-text/)

Document link: [rich-text.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/widgets/rich-text.md)

## My Issue/Suggestion
I would add an example of how to list multiple options or at least mention using a semi-column (;) to separate each option

**Comment by ConnorLand** [comment]
Hello @cerego ,

This type of WYSIWYG editor can indeed present complexities. However, our developers here are a little confused about how to implement your documentation suggestions. Can you please [file a pull request directly](https://docs.mendix.com/developerportal/community-tools/contribute-to-the-mendix-documentation/) editing the document? That way we can see exactly what you are proposing.

Thank you for contributing to the documentation,

Connor
