### ISSUE TITLE
generate-an-sdk-script-based-on-an-existing-model

### ISSUE THREAD

**Issue by smg209** [mendix/docs#5120]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [generate-an-sdk-script-based-on-an-existing-model](https://docs.mendix.com/apidocs-mxsdk/mxsdk/generating-code-from-the-model/)

Document link: [generating-code-from-the-model.md](https://github.com/mendix/docs/blob/development/content/en/docs/apidocs-mxsdk/mxsdk/sdk-howtos/generating-code-from-the-model.md)

## My Issue/Suggestion
This page is out of date. 
"import { MendixSdkClient, Project, OnlineWorkingCopy, loadAsPromise } from "mendixplatformsdk";" imports 3 classes that are no longer defined in the mendixplatformsdk. The rest of the code is useless since these classes aren't there to be imported

**Comment by Luyao-Zhang-1** [comment]
@smg209 Many thanks for reporting this issue. 
I am discussing it with our developer, and will come back to you on this soon.

**Comment by Luyao-Zhang-1** [comment]
Developers need to review and update the information first. Once they've done that, I will update the doc.

**Comment by Luyao-Zhang-1** [comment]
@smg209 The [doc](https://docs.mendix.com/apidocs-mxsdk/mxsdk/generating-code-from-the-model/) is updated. Thank you for reporting this issue to us. 

Please continue to let us know in the future if you see documentation that can be improved. Thank you!
