### ISSUE TITLE
implement-mendix-best-practices-for-development

### ISSUE THREAD

**Issue by CoenPijpers1707** [mendix/docs#5152]
Page link: https://docs.mendix.com/howto/general/dev-best-practices/

Document link: [dev-best-practices.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/general/dev-best-practices.md)

## My Issue/Suggestion
At the complexity section, provide an example of doing it wrong and doing it right:
The text: Nested IF statements in a single microflow expression are not recommended. If multiple checks depend on one another, this should be represented by multiple decisions in the microflow, so that the complexity is not hidden away in the expressions. You can use AND and OR operators to produce complex expressions if necessary.

**Comment by Yiyun333** [comment]
@CoenPijpers1707 Thank you very much for your suggestion! Examples are now added for this paragraph in the [Best Practices doc]( https://docs.mendix.com/howto/general/dev-best-practices/) (see section 4.2.4).
