### ISSUE TITLE
set-up-your-partner-profile

### ISSUE THREAD

**Issue by NicoMOST** [mendix/docs#5156]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [set-up-your-partner-profile](https://docs.mendix.com/developerportal/community-tools/how-to-set-up-your-partner-profile/)

Document link: [how-to-set-up-your-partner-profile.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/community-tools/how-to-set-up-your-partner-profile.md)

## My Issue/Suggestion

I am the amdin of our company as Mendix partner but I cannot modify the company profile and create the partner profile. clicking the logo of my company I cannot update it
![2022-10-11 09_22_37-Mendix Developers - Overview and 26 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/85452568/195022477-d4f4f46b-a658-484e-848d-4fea22c2195f.png)

**Comment by Adam-Dupaski** [comment]
Hi @NicoMOST thanks for you feedback, sorry to hear about this problem. Since this isn't related to the documentation, please send a request to Mendix Support if this is still an issue: https://support.mendix.com/hc/en-us
Thanks.
