### ISSUE TITLE
Empty README in ATS attachments

### ISSUE THREAD

**Issue by JelteMX** [mendix/docs#516]
@zwartd I have removed the `README.md` in `ATS/howtos/attachments/getting-started/` (in [this commit](https://github.com/mendix/docs/commit/9135baba6ab7ae05cf854816580cb065674df3a8)), because it was breaking our build. Any reason why that file was there? Just giving you a headsup, if it isn't a problem, I'll close the issue.

**Comment by zwartd** [comment]
@JelteMX  ow sorry, it is a standard file created when i create a folder must have forgotten to remove it. It is not a problem, thanks for the heads up!
