### ISSUE TITLE
consumed-rest-services

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#5164]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [consumed-rest-services](https://docs.mendix.com/refguide/consumed-rest-services/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/integration/consumed-rest-services/_index.md)

## My Issue/Suggestion
It would be really helpful if there was some information here about declaring http header content types.  A header needs to be declared if content is being passed in the request body using JSON but this does not seem to be explained or referenced here.  Without this extra information it seems to assume that you are a high coder moonlighting as a Mendix developer.  I only resolved the issue by comparing with another REST call that someone else had done.  Thank you.

**Comment by johannahemminger** [comment]
Hi @Chris-Karona , thanks for your feedback. I am adding some more info to the file in PR https://github.com/mendix/docs/pull/5215 . I will close this issue for now, but if you have any further questions or feedback about docs please feel free to open another issue!
