### ISSUE TITLE
import-a-large-excel-file

### ISSUE THREAD

**Issue by daeyoungWie** [mendix/docs#5188]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [import-a-large-excel-file](https://docs.mendix.com/howto/integration/import-a-large-excel-file/)

Document link: [import-a-large-excel-file.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/integration/importing-excel-documents/import-a-large-excel-file.md)

## My Issue/Suggestion
got an error... 

![image](https://user-images.githubusercontent.com/105832962/196600601-38892880-4d6b-4bfc-8317-27e753680957.png)

**Comment by johannahemminger** [comment]
Hi @daeyoungWie , thanks for submitting this. I checked with the team and this error occurs when there is a duplicate entry; looks like our sample file is the problem! I am updating the sample Excel in PR https://github.com/mendix/docs/pull/5211 . Sorry for the inconvenience.

If you see any future problems with our docs, please feel free to open another issue. The Mendix Forum and Mendix Support can also help you if you run into errors.
