### ISSUE TITLE
Database Specifications

### ISSUE THREAD

**Issue by rkogushi** [mendix/docs#5198]
We checked with Mendix Support regarding the specifications of Mendix's internal database (*) and received the following response.
(*)Database where domain model entities are stored
---
Mendix does not have a read lock on the database. Therefore, object reads can always be performed.
If there are overlapping update operations, the first update operation gets a write lock on the database, but the next update operation waits until the first one finishes before executing. Therefore, there is no error.
However, if the first update process takes an inordinate amount of time, it may cause a timeout.
---
Could you please include the above information in the Mendox Docs?
Also, if you have any other specifications regarding database locking/exclusion control, please include them in the Mendix Docs.

**Comment by MarkvanMents** [comment]
Hi there,
Sorry about the delay in responding to this issue. We have gone into locking on Mendix in more detail and have included the information in this PR: https://github.com/mendix/docs/pull/5806. This also includes the information you included in this issue.

Thank you for taking the time to help us improve the Mendix documentation. It is often only from feedback from customers using the documentation that we can identify where changes need to be made.

Please let us know if you spot any other improvements which could be made.

Yours
Mark van Ments
