### ISSUE TITLE
deep-link

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#5201]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [deep-link](https://docs.mendix.com/appstore/modules/deep-link/)

Document link: [deep-link.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/deep-link.md)

## My Issue/Suggestion
The page does not describe the options on the runtime configuration of a deeplink.  This is also not covered in the marketplace documentation.  For example, what does this mean "If enabled the incoming link argument will be processed as an Object"? What would this look like if I was constructing the deeplink URL string?

**Comment by Luyao-Zhang-1** [comment]
Hi @Chris-Karona ,

Thank you for raising this issue. I checked with our developer. Here is the answer to you question: 

```
This is an alternative to Java actions SetObjectParameterDeeplink and SetStringParameterDeeplink. With these settings, users can control how a URL parameter will be parsed.

https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/deep-link.md#351-configuring-deep-links-in-after-startup-microflow
```

I hope this helps. Please let me know if you have more questions. Meanwhile, we are working to add a section about these settings in the doc. Hopefully, that can be done soon.

Kind regards,
Luyao

**Comment by Luyao-Zhang-1** [comment]
Hi @Chris-Karona, we added the description of the Configuration settings and Advanced settings in the [doc](https://docs.mendix.com/appstore/modules/deep-link/#34-adding-the-configuration-overview-snippet-the-custom-admin-page). Thank you again for your feedback.
