### ISSUE TITLE
commit

### ISSUE THREAD

**Issue by cyeongb** [mendix/docs#5210]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [commit](https://docs.mendix.com/refguide/commit-dialog/)

Document link: [commit-dialog.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/menus/version-control-menu/commit-dialog.md)

## My Issue/Suggestion
hello i'm developer working with Mendix
I wonder if there is a way to do commit selectively?
We're working together and we want to commit only what each one has worked on.
i can't find how commit selectively . please let me know if you know about it
thank you

**Comment by MariaShaposhnikova** [comment]
Hi @cyeongb , 
Thank you for your feedback!
Could you please provide a bit more details on your use case? Normally, when you commit, this commit only contains your changes. Do you mean that changes of your colleagues get merged? Have you considered working on different branches? Please see documentation on working with branches in the [Using Branches](https://docs.mendix.com/refguide/using-version-control-in-studio-pro/#7-using-branches) section of _Using Version Control in Studio Pro_.
It is not possible to commit selectively, but I hope that information about branches helps. 

Best regards,
Maria

**Comment by MariaShaposhnikova** [comment]
Hi @cyeongb , 
I will close this issue, I hope my response cleared it up and helped. If you have any further details or feedback, you can let us know in a comment. 

Best regards,
Maria
