### ISSUE TITLE
would be nice if the documentation had information on exactly where/how to grant a team member access to logs - can't find that anywhere in the doc

### ISSUE THREAD

**Issue by andy-fitch** [mendix/docs#5227]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [logs](https://docs.mendix.com/developerportal/operate/logs/)

Document link: [logs.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/operate/logs.md)

**Comment by MarkvanMents** [comment]
Hi Andy (@andy-fitch )
Thanks very much for the suggestion. I have added a warning that you can only see logs if you have the right permissions, and added a link to the Node Permissions documentation.
The change is in this commit: https://github.com/mendix/docs/commit/c5cc01e5a74ba3a005ad5bacaf6e822b8a332ace
Thank you for taking the time to help us improve our documentation. Do let us know if you see any other things which could be improved – we rely on users to identify areas where the documentation can be better.
Mark
