### ISSUE TITLE
lts-mts-and-monthly-releases

### ISSUE THREAD

**Issue by RobinH81** [mendix/docs#5228]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [lts-mts-and-monthly-releases](https://docs.mendix.com/releasenotes/studio-pro/lts-mts/)

Document link: [lts-mts.md](https://github.com/mendix/docs/blob/development/content/en/docs/releasenotes/studio-pro/lts-mts.md)

## My Issue/Suggestion

LTS 9.18 is there, but still not mentioned. Ik want to use the page to post on our internal Confluence page.

**Comment by Adam-Dupaski** [comment]
Hi @RobinH81 9.18 is actually an MTS, not an LTS. Thanks.
