### ISSUE TITLE
saml

### ISSUE THREAD

**Issue by elliotclements-mendix** [mendix/docs#5236]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [saml](https://docs.mendix.com/appstore/modules/saml/)

Document link: [saml.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/saml.md)

## My Issue/Suggestion
In Chapter **2.1 Using SSOLandingPage**  the guide documents how to generate a custom index.html file. The steps are incorrect. This link documents the correct approach: https://docs.mendix.com/howto/front-end/customize-styling-new/#custom-web.

I suggest linking out to the documentation:

**Current Documentation**
> To do this, you need to add <meta http-equiv="refresh" content="0;URL=/SSO/" /> to the index.html file. (For Mendix version 9, there is no index.html file, so you need to create this file first. To do so, run your app in Studio Pro, and then copy the index.html file from the /deployment/web/ folder to the /theme/web folder. Mendix then uses this version as the template for index.html.) 

**Proposed Changes**
> To do this, you need to add <meta http-equiv="refresh" content="0;URL=/SSO/" /> to the index.html file. (For Mendix version 9, there is no index.html file, so you need to create this file first. To do so see https://docs.mendix.com/howto/front-end/customize-styling-new/#custom-web)

**Comment by MarkvanMents** [comment]
Hi Elliot,
Thanks for identifying this shortcoming and providing a great solution. I have done what you suggested in this commit: https://github.com/mendix/docs/commit/f3fc03d844b36e0d8ef9206c5f380d51c0f4c763
Great to have this feedback as we can only track things like this by getting the information from people who are actually using the product.
Mark
