### ISSUE TITLE
email-connector

### ISSUE THREAD

**Issue by bentura** [mendix/docs#5246]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [email-connector](https://docs.mendix.com/appstore/connectors/email-connector/)

Document link: [email-connector.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/connectors/email-connector.md)

## My Issue/Suggestion

I don't seem to be able to use a local email client such as PaperCut.  With the old Email Template module, I could configure the server to be 127.0.0.1 or Localhost with Port 25, but when I try this with the Email connector, I get an error saying unable to connect to SMTP server.  Is this something that can be looked into, or am I missing something?

Thanks

**Comment by Adam-Dupaski** [comment]
@NatasaKralj maybe also interesting for you with Email module/connector

**Comment by johannahemminger** [comment]
Hi @bentura , thanks for opening this issue. I checked with the team, and you should be able to configure it as you did before. Start setting up the SMTP account manually, entering localhost as the server host. Then, to connect with PaperCut, enter a random email ID on the login screen (as for Papercut anything would work), and it should work as expected.

I will add this information and other useful tips to the doc in PR https://github.com/mendix/docs/pull/5258 . If you have any further feedback or additions for our docs, please feel free to open another issue!
