### ISSUE TITLE
implement-styles

### ISSUE THREAD

**Issue by rondv5** [mendix/docs#5255]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [implement-styles](https://docs.mendix.com/howto/front-end/styles/)

Document link: [styles.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/front-end/styles.md)

## My Issue/Suggestion
Please consider if this page should not be called "Implement Classes" since that is where one uses these items, and the word class is also "hidden" in the document itself.

**Comment by ConnorLand** [comment]
Hi @rondv5 ,

Our designers agree. The title will be changed.

Connor
