### ISSUE TITLE
find-find-advanced-and-find-usages

### ISSUE THREAD

**Issue by RobinH81** [mendix/docs#5257]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [find-find-advanced-and-find-usages](https://docs.mendix.com/refguide/find-and-find-advanced/)

Document link: [find-and-find-advanced.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/menus/edit-menu/find-and-find-advanced.md)

## My Issue/Suggestion
Plz add (how-to for) search scss files for specific value.

**Comment by Adam-Dupaski** [comment]
Hi @RobinH81 thanks for the feedback. The Find and Find Advanced options are used to find elements in your app. For something like .scss files, you'll want to look at the app directory and search those files. Please see this doc: https://docs.mendix.com/refguide9/app-menu/#4-show-app-directory-in-explorer Good luck!
