### ISSUE TITLE
begin-of-date-function-calls

### ISSUE THREAD

**Issue by simo101** [mendix/docs#5349]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [begin-of-date-function-calls](https://docs.mendix.com/refguide/begin-of-date-function-calls/)

Document link: [begin-of-date-function-calls.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/expressions/begin-of-date-function-calls.md)

## My Issue/Suggestion
We need to make sure that this page makes it clear that these functions only exist in 9.18.0 and above. I've just had a confused customer try to use these in a different Studio Pro.

**Comment by Yiyun333** [comment]
I've added this inforamation to the function page. See PR: https://github.com/mendix/docs/pull/5361
