### ISSUE TITLE
text-area

### ISSUE THREAD

**Issue by shawnsuo** [mendix/docs#5351]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [text-area](https://docs.mendix.com/refguide/text-area/)

Document link: [text-area.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/pages/input-widgets/text-area.md)

## My Issue/Suggestion
"2.8.5 AutoFocus" have the wrong index number, it should be "2.6.8 AutoFocus"

**Comment by MariaShaposhnikova** [comment]
Hi @shawnsuo,
Thanks a lot for reporting the issue, I have fixed the section numbering.

Best regards,
Maria
