### ISSUE TITLE
preferences

### ISSUE THREAD

**Issue by Membad** [mendix/docs#5371]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [preferences](https://docs.mendix.com/refguide/preferences-dialog/#511-executable)

Document link: [preferences-dialog.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md)

## My Issue/Suggestion
Under `Executables` it might be nice to add an example configuration for Visual Studio Code like this:

```
C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\Code.exe
--wait --diff "{0}" "{1}"
```

**Comment by MariaShaposhnikova** [comment]
Hi @Membad ,
Thank you for your feedback! 
I've made the path in the example a bit more general and added it to the [Preferences document](https://docs.mendix.com/refguide/preferences-dialog/#511-executable). 

Best regards,
Maria
