### ISSUE TITLE
apply-ip-protection

### ISSUE THREAD

**Issue by NielsKunst** [mendix/docs#5382]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [apply-ip-protection](https://docs.mendix.com/appstore/creating-content/sol-ip-protection/)

Document link: [sol-ip-protection.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/creating-content/sol-solutions-guide/sol-development/sol-ip-protection.md)

## My Issue/Suggestion

The below sentence in the section '2 Why IP Protection?' is kind of hard to understand:
"Reusable solutions, app services, connectors, and other modules contain IP in the form of app model content like microflows that is reusable and which can be monetized. "

For instance the part 'contain IP', should that be 'contain IP Protection'?
And 'app model content like microflows that is reusable', the noun 'is', does that belong to the subject 'app model content' or to 'microflows' (in which case is should be changed to 'are')? It is hard to decipher this, maybe this can be rewritten?

**Comment by Adam-Dupaski** [comment]
Hi @nelis37 , thanks for your feedback here.

"IP" as an acronym for "intellectual property" is defined in the first sentence of the doc: "you will have intellectual property (IP) protection". It is also reflected in the title of the doc. Following our style guidelines, we believe this is sufficient for understanding the acronym.

And yes, "is" refers to the "app model content." I've rewritten that sentence a bit for clarity in this commit: https://github.com/mendix/docs/commit/ae830b009f60267942db9b8b9faa21c8a8c74e2c

I hope that addresses your concerns here. Please let me know if you have other feedback in a new issue, and thanks for helping to improve Mendix docs!
