### ISSUE TITLE
apply-ip-protection

### ISSUE THREAD

**Issue by NielsKunst** [mendix/docs#5384]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [apply-ip-protection](https://docs.mendix.com/appstore/creating-content/sol-ip-protection/)

Document link: [sol-ip-protection.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/creating-content/sol-solutions-guide/sol-development/sol-ip-protection.md)

## My Issue/Suggestion

Can we change the title 'Apply IP Protection' to 'Apply Intellectual Property Protection'? 

If found this confusing since IP is a well know abbreviation for 'Internet Protocol'

**Comment by Adam-Dupaski** [comment]
Hi @nelis37 thanks for your feedback, I've updated the title in this commit: https://github.com/mendix/docs/commit/ac4c31542ce05be1052f108f5b303ecf1762dfbb

Cheers,
Adam
