### ISSUE TITLE
how to edit the type of an existing attribute in a domain-model in Studio 9?

### ISSUE THREAD

**Issue by goodfriends1** [mendix/docs#5390]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [domain-model](https://docs.mendix.com/studio/domain-models/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/studio/work-with-data/domain-models/_index.md)

## My Issue/Suggestion
how do I modify an existing attribute's type? I am using Studio 9.

**Comment by MariaShaposhnikova** [comment]
Hi @goodfriends1 ,
Thank you for your feedback.
If you click an attribute in the domain model and then open the **Properties** tab on the right, you should be able to change the attribute type there. 

Best regards,
Maria

**Comment by MariaShaposhnikova** [comment]
@goodfriends1,
We also have a document on [attribute type migration](https://docs.mendix.com/refguide/attributes-type-migration/) that contains more detailed information. I hope this helps. 

Best regards,
Maria
