### ISSUE TITLE
runtime-customization

### ISSUE THREAD

**Issue by zjh1943** [mendix/docs#5396]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [runtime-customization](https://docs.mendix.com/refguide/custom-settings/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/runtime/custom-settings/_index.md)

## My Issue/Suggestion

When I upload a file to the server, which directory does the file will be saved on the machine of the server?
I ask this question because I want to mount a network disk to the server to prevent the files from being cleared when the instance of the Mendix application is destroyed.
I think the document should talk more about the situation of the private cloud.

**Comment by MarkvanMents** [comment]
Hi Jinheng,
If you are talking about files uploaded through your app (e.g. [File Documents](https://docs.mendix.com/howto/data-models/working-with-images-and-files/) then these are all stored on S3 storage. None of the data you put into your app is kept in the container where the app is running - this enables the app to be scaled to multiple instances and makes it robust if an instance fails or if the app has to be restarted.
You can see a simple picture of the architecture here: https://www.mendix.com/evaluation-guide/enterprise-capabilities/cloud-architecture/#3-how-is-application-isolation-organized
The Mendix Cloud also makes regular [backups](https://docs.mendix.com/developerportal/operate/backups/) of your data which can be restored if there is an issue with the database or S3 file storage.

In the case of Private Cloud, you need to provide your own [S3 storage plan](https://docs.mendix.com/developerportal/deploy/private-cloud-cluster/#storage-plan) which points to an S3-compatible service. In this case, you are responsible for running the backups.

If you have further questions about this, I suggest you ask on the [Mendix Forum](https://forum.mendix.com/p/questions) where there are many experienced Mendix developers, or through [Mendix Support](https://support.mendix.com). You are likely to get more help there than I can give you.

If you have any specific suggestions for improving the documentation, please do raise a further issue. In this case, I am not sure exactly where an improvement can be made. However, I will make a note of your query and see if we can improve things in the future.

Thanks you for taking the time to contact Mendix.

Yours

Mark
