### ISSUE TITLE
set-up-a-github-repo-to-publish-a-marketplace-item

### ISSUE THREAD

**Issue by scottf** [mendix/docs#5414]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [set-up-a-github-repo-to-publish-a-marketplace-item](https://docs.mendix.com/appstore/creating-content/set-up-repo/)

Document link: [set-up-repo.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/creating-content/set-up-repo.md)

## My Issue/Suggestion

You can't actually create a repo in this form "Mendix/MyFirstApp", because github does not accept the forward slash

**Comment by Adam-Dupaski** [comment]
Hi @scottf thanks for your feedback, this was meant to be a generic UpperCamelCase example, I've clarified it in this commit: https://github.com/mendix/docs/commit/60100aa86b908bcfb1639a374276e172b9e91c7a

Cheers,
Adam
