### ISSUE TITLE
enable-end-users-to-attach-images

### ISSUE THREAD

**Issue by Leonhard-Benkert** [mendix/docs#5430]
Page link: [enable-end-users-to-attach-images](https://docs.mendix.com/studio-how-to/pages-how-to-attach-images/)

Document link: [pages-how-to-attach-images.md](https://github.com/mendix/docs/blob/development/content/en/docs/studio-how-to/pages/pages-how-to-attach-images.md)

## My Issue/Suggestion
Tutorial is wrong in one place, see here: https://forum.mendix.com/link/space/studio/questions/120903

**Comment by MariaShaposhnikova** [comment]
Hi @Leonhard-Benkert ,
Thanks a lot for reporting the issue in the how-to! I tested it and correct the instructions in [this commit](https://github.com/mendix/docs/commit/9555d3b2feb70c04999598f6c3b1b5416804e257), now the how-to is using the association. 
We also added the [attach images use case](https://docs.mendix.com/refguide/attach-images/) to Studio Pro (in case you are using Studio Pro and would like to see how to build this functionality there). 

Best regards, 
Maria
