### ISSUE TITLE
Link to download studio-pro

### ISSUE THREAD

**Issue by johanflikweert** [mendix/docs#5445]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [studio-pro](https://docs.mendix.com/releasenotes/studio-pro/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/releasenotes/studio-pro/_index.md)

## My Issue/Suggestion
An easy button to go to the download section

**Comment by Adam-Dupaski** [comment]
Hi @johanflikweert thanks for the suggestion, I added the button to this RN page: https://github.com/mendix/docs/commit/2677f585d7533cebedc9c7fb1fe7e70943e865b0
