### ISSUE TITLE
Mendix Runtime Overview Diagram

### ISSUE THREAD

**Issue by mxcrawford** [mendix/docs#5454]
Page link: [mendix-runtime](https://docs.mendix.com/refguide/runtime/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/runtime/_index.md)

**Comment by MarkvanMents** [comment]
Hi Alastair,
Thanks for your suggestion. I will ask our design department to have a look at how this can be improved.
