### ISSUE TITLE
manage-local-users-in-studio

### ISSUE THREAD

**Issue by NielsKunst** [mendix/docs#5491]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [manage-local-users-in-studio](https://docs.mendix.com/developerportal/deploy/managing-local-users-after-deployment/)

Document link: [managing-local-users-after-deployment.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/tencent-deploy/managing-local-users-after-deployment.md)

## My Issue/Suggestion
The URL in the introduction points to Mx 8 docs, instead of Mx 9 docs:

> With Mendix Studio Pro, you can configure an Administrator account directly in your security settings. See [Administrator](https://docs.mendix.com/refguide8/administrator/) for more information.

Suggested:

> With Mendix Studio Pro, you can configure an Administrator account directly in your security settings. See [Administrator](https://docs.mendix.com/refguide/administrator/) for more information.

**Comment by MarkvanMents** [comment]
Hi,
Thank you for reporting this issue. I have corrected it in this commit: https://github.com/mendix/docs/commit/5b5b2e3c1ea2f89892ad4d70791bbde71f9fe209.

Thanks for taking the time to report an issue with the Mendix documentation. It really helps us to improve the documentation for everyone. Feel free to report anything else you find, or to make suggestions for improvements.

Yours
Mark van Ments.
