### ISSUE TITLE
runtime-customization Migration Settings incorrect 

### ISSUE THREAD

**Issue by elliotclements-mendix** [mendix/docs#5510]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [runtime-customization](https://docs.mendix.com/refguide/custom-settings/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/runtime/custom-settings/_index.md)

## My Issue/Suggestion
There's duplication of the migration documentation, but two pages say different things:

In this documentation page "Section 4.3 Migration Settings" it states: 

> Before the data copy process starts, the source database will also be brought in line with the model, like the main database. This is necessary to make it possible to copy all the data without problems.

In the Migrating your Mendix Database Documentation a subtly different note is mentioned:  

> Before the data copying process starts, the main database structure will be generated based on the source database structure. This is necessary to make sure all the data is copied without any problems, especially in cases where the source database has a larger element value than what the current domain model specifies.
> 
> The source database structure and data do not change as part of the migration.
https://docs.mendix.com/howto/data-models/migrating-your-mendix-database/#2-overview

I believe "Section 4.3 Migration Settings" is incorrect. The source database is not brought in line with the model. The source database is the **original** database which should not be touched. The data will be copied from the source and transferred to the 'main' database (the new one). It is the main database who's structure is modified to match the source. 

I believe it should read: 
> Before the data copy process starts, the _main_ database will be brought in line with the model, like the _source_ database. This is necessary to make it possible to copy all the data without problems.

Alternatively, and the preferred option imo, would be to replicate the quote word for word here: 
> Before the data copying process starts, the main database structure will be generated based on the source database structure. This is necessary to make sure all the data is copied without any problems, especially in cases where the source database has a larger element value than what the current domain model specifies.

**Comment by MarkvanMents** [comment]
Thanks for the report, Elliot.
I'll pick this up and make a Pull Request. Then get back to you once I have merged the change.

**Comment by MarkvanMents** [comment]
Hi Elliot.
Thanks for your input. I've made the changes you suggested and the PR is now merged.
Yours
Mark
