### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by reinouts** [mendix/docs#5540]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [aqm](https://docs.mendix.com/addons/aqm-addon/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/addons/aqm-addon/_index.md)

## My Issue/Suggestion
The link in the introduction is dead. Should probably go to https://www.softwareimprovementgroup.com/solutions/sigrid-for-mendix-quality-and-security-management/ instead.

**Comment by Adam-Dupaski** [comment]
Thanks @reinouts fixed: https://github.com/mendix/docs/commit/020cc8acde2b7bbc1dc6e65ed234c2933549bf8e
