### ISSUE TITLE
Error when using Login_Mobile_Automatic and Login_Mobile_Button as login page on localhost with MakeItNative app

### ISSUE THREAD

**Issue by VDSApps** [mendix/docs#5550]
Hi,

When using Login_Mobile_Automatic or Login_Mobile_Button as the login page for a native app, the MakeItNative app gives an error. The error I get is a missing module and the build failes.

StudioPro 9.18.3.58938

The error log is:

[Output] error: Error: Unable to resolve module react-native-inappbrowser-reborn from C:\Users\***********\javascriptsource\oidc\actions\JS_OpenAuthURL.js: react-native-inappbrowser-reborn could not be found within the project or in these directories:
[Output]   ..\..\javascriptsource\oidc\actions\node_modules

Is this a know issue or am I doing something wrong?

Thanks!

Kind regards,

Lourens/VDS

**Comment by ConnorLand** [comment]
Hello,

I don't believe this is a known issue, nor is it a common error documentation has an easy fix for. Could you please contact our Support department and provide these details to them?

If there is a documentation update required after your Support ticket is resolved, I'll be happy to handle it then.

Thank you,

Connor

**Comment by VDSApps** [comment]
Thanks, will do!
