### ISSUE TITLE
sdk-introduction

### ISSUE THREAD

**Issue by Michiel-Bijlsma** [mendix/docs#5558]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [sdk-introduction](https://docs.mendix.com/apidocs-mxsdk/mxsdk/sdk-intro/)

Document link: [sdk-intro.md](https://github.com/mendix/docs/blob/development/content/en/docs/apidocs-mxsdk/mxsdk/sdk-intro.md)

## My Issue/Suggestion
If you image it, there is probably a way to do it via these SDKs. > If you can imagine it, there is probably a way to do it via these SDKs.
(In case the current sentence is already correct, I don't understand it.)

**Comment by MarkvanMents** [comment]
Hi Michiel,
Thanks for bringing this to our attention.
I've reviewed the document and this sentence doesn't seem to add anything and seems to have been accidentally published while half-written. I have therefore removed it and done a quick review of the rest of the document as well.
Thanks for taking the trouble to report this - we rely on our readers to draw our attention to errors like this and make the documentation better for everyone.
Yours
Mark van Ments
