### ISSUE TITLE
parse-and-format-decimal-function-calls

### ISSUE THREAD

**Issue by mrgroen** [mendix/docs#5568]
Page link: [parse-and-format-decimal-function-calls](https://docs.mendix.com/refguide/parse-and-format-decimal-function-calls/)

Document link: [parse-and-format-decimal-function-calls.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/expressions/parse-and-format-decimal-function-calls.md)

## My Issue/Suggestion
The parseDecimal function is not the same between Microflows and Nanoflows. Just like the formatDecimal function the system locale is used for the format. Please add some information about this behaviour.

**Comment by Yiyun333** [comment]
Hi @mrgroen,

Thank you for your feedback! We are now working on adding such information for the parseDecimal function. I will keep you posted when we finish updating the document.

Best regards,
Yiyun

**Comment by Yiyun333** [comment]
Hi @mrgroen,

We updated the document according to your feedback. For the details, please see PR: https://github.com/mendix/docs/pull/5655.

Thanks again for your feedback!

Best regards,
Yiyun
