### ISSUE TITLE
native-mobile-styling

### ISSUE THREAD

**Issue by jasonteunissen** [mendix/docs#5593]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [native-mobile-styling](https://docs.mendix.com/refguide8/native-styling-refguide/)

Document link: [native-styling-refguide.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md)

## My Issue/Suggestion
I am looking for documentation of the default class names of MxWidgets so that I can change the default.
for instance, if I would like to change the floating action button I need to know that the default class is called 'com_mendix_widget_native_floatingactionbutton_FloatingActionButton'
It would be nice if the code section in there would contain a styling boilerplate like this: 

```
export const com_mendix_widget_native_floatingactionbutton_FloatingActionButton = {
    container: {
    },
    button: {
    },
    buttonIcon: {
    },
    secondaryButton: {
    },
    secondaryButtonIcon: {
    },
    secondaryButtonCaption: {
    },
    secondaryButtonCaptionContainer: {
    }
};
```

**Comment by ConnorLand** [comment]
Hi Jason,

I will check this with our Mendix developers. Thank you for your suggestion!

**Comment by ConnorLand** [comment]
Hi Jason,

Below each widget you can find the classname. We prefer you use that over a boilerplate, so please use that for reference. 

Thank you for your suggestion,

Connor
