### ISSUE TITLE
openapi-3.0-documentation

### ISSUE THREAD

**Issue by reinouts** [mendix/docs#5615]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [openapi-3.0-documentation](https://docs.mendix.com/refguide/open-api/)

Document link: [open-api.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/integration/published-rest-services/published-rest-technical-details/open-api.md)

## My Issue/Suggestion
As of 9.22, the generated REST documentation is Swagger level 2.0, not OpenAPI 3.0

**Comment by johannahemminger** [comment]
Hey @reinouts , thanks for pointing this out, I have fixed this in this [PR ](https://github.com/mendix/docs/pull/5614)
