### ISSUE TITLE
published-rest-services

### ISSUE THREAD

**Issue by paul-moes-mendix** [mendix/docs#5621]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [published-rest-services](https://docs.mendix.com/refguide/published-rest-services/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/integration/published-rest-services/_index.md)

## My Issue/Suggestion
"When you [allow anonymous users](https://docs.mendix.com/refguide/app-security/#anonymous-users) to your app, all published REST services become available without authentication, or"  

this only applies if the anonymous user has been selected at the allowed roles for the published service and Username and password has been selected as the Authentication Method

The text seems to suggest that enabling anonymous users automatically makes all published rest services work without authentication

**Comment by johannahemminger** [comment]
Hi @paul-moes-mendix , thanks very much for opening this issue. I have added the explanation you suggested to the doc, and will merge once I verify it with the team. Feel free to open any more issues that you come across! Appreciate you helping make our docs better.
