### ISSUE TITLE
mendix-cloud

### ISSUE THREAD

**Issue by dan-covaliu** [mendix/docs#5623]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [mendix-cloud](https://docs.mendix.com/developerportal/deploy/mendix-cloud-deploy/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/mendix-cloud-deploy/_index.md)

## My Issue/Suggestion
Regarding the number of environments per free app, the documentation versus the pricing page provide conflicting information:
 - https://docs.mendix.com/developerportal/deploy/mendix-cloud-deploy/  specifies single environment
 - https://www.mendix.com/pricing/ specifies 2 environments

**Comment by MarkvanMents** [comment]
Hi Dan,
Thanks for the comment and suggestion.
It is confusing, but when the pricing page refers to two environments it is including the ability to deploy the app locally for testing on your own machine. This is the way most low-code companies count their environments.
In the documentation, we are talking about deploying to the cloud and so talk about one _cloud_ environment, to make it clear that there is only one environment that can be shared with users.

I will have a look and see if this can be made clearer.

Thanks for drawing attention to this conflict - I will pass your experience on and see if we can make our messaging clearer.
Yours
Mark
