### ISSUE TITLE
publish-a-rest-service

### ISSUE THREAD

**Issue by mikestgt** [mendix/docs#5625]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [publish-a-rest-service](https://docs.mendix.com/howto/integration/publish-rest-service/)

Document link: [publish-rest-service.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/integration/publish-rest-service.md)

## My Issue/Suggestion
this error is in step 19
![image](https://user-images.githubusercontent.com/14021675/218308755-797b19f8-66d9-4947-b392-3c847864ef0c.png)

**Comment by johannahemminger** [comment]
Hi @mikestgt , thanks for opening this issue! In the documentation example, I don't see httpResponse as one of the parameters (only httpRequest and OrderID), which appears to be the cause of the error. Can you check where you are using that parameter? In the meantime I can check through the steps and see if I can reproduce it.

**Comment by johannahemminger** [comment]
Hi @mikestgt , I am able to reproduce it indeed. The microflow that is created in step 4.2.6 automatically adds that parameter, but that conflicts with adding the export mapping in section 5. Removing the parameter resolves the error, but I will update the how-to to reflect the current behavior of creating the new microflow and check with the team about explaining the reason for this behavior. Thanks very much for reporting this!
