### ISSUE TITLE
installing-mendix-studio-pro

### ISSUE THREAD

**Issue by TSSheppard** [mendix/docs#5658]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [installing-mendix-studio-pro](https://docs.mendix.com/refguide/install/)

Document link: [install.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/general/install.md)

## My Issue/Suggestion

Documentation is wrong:

- Not windowsdesktop-runtime-6.0-win-x64.exe , but windowsdesktop-runtime-6.0-x64.exe -> remove the "-win"

**Comment by MariaShaposhnikova** [comment]
Hello @TSSheppard ,
Thank you for your feedback! I've corrected the document.

Best regards,
Maria
