### ISSUE TITLE
supported-providers

### ISSUE THREAD

**Issue by pietervercammen** [mendix/docs#5667]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [supported-providers](https://docs.mendix.com/developerportal/deploy/private-cloud-supported-environments/)

Document link: [private-cloud-supported-environments.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md)

## My Issue/Suggestion

Can we check if 4.10 is still the latest supported version?

Pieter

**Comment by katarzyna-koltun-mx** [comment]
https://github.com/mendix/docs/pull/5748
