### ISSUE TITLE
restrict-access-for-incoming-requests

### ISSUE THREAD

**Issue by winfried-van-loon-goudse** [mendix/docs#5683]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [restrict-access-for-incoming-requests](https://docs.mendix.com/developerportal/deploy/access-restrictions/)

Document link: [access-restrictions.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/mendix-cloud-deploy/access-restrictions.md)

## My Issue/Suggestion
Screenshot under 4.2, list item 6, seems to be wrong: I would expect a 'scenario 2' screenshot here. What I instead (wrong), is a 'scenario 1' screenshot. 

My suggestion would be to replace the screenshot, to show a scenario 2 situation, where `/ws/` is being edited, like suggested in the text above and below the screenshot.

**Comment by MarkvanMents** [comment]
Hi Winfried,
Thanks for bringing this to our attention. I have updated the documentation in this commit: https://github.com/mendix/docs/commit/3fb4ce4ba5ebb99eb1400350c5196920a6e8f923
Thank you for helping to make the Mendix documentation better. We rely on the community to help us improve the documentation so your contribution is very welcome.
Yours
Mark van Ments
