### ISSUE TITLE
part-7-send-your-first-test-push-notification

### ISSUE THREAD

**Issue by sonam2207** [mendix/docs#5688]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [part-7-send-your-first-test-push-notification](https://docs.mendix.com/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test/)

Document link: [notif-send-test.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md)

## My Issue/Suggestion
Hi, i have an issue with the step, if the app is opened, i am not receiving the notification on my phone. It's only working if app is running in background or closed.

**Comment by ConnorLand** [comment]
Hello @sonam2207 ,

Apologies for the delayed response. The push notification process can be difficult indeed. For development help, I recommend searching or posting a question in the [Mendix Forum](https://forum.mendix.com/p/community). 

If you difficulties persist, please file a [Mendix Support Ticket](https://support.mendix.com/hc/en-us) and they will help identify parts of the product that need to be improved. After that, I'll be notified and I will alter the documentation accordingly.

Thanks for contacting Mendix Documentation,

Connor
