### ISSUE TITLE
migrate-to-git

### ISSUE THREAD

**Issue by franksoong** [mendix/docs#5699]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [migrate-to-git](https://docs.mendix.com/developerportal/collaborate/migrate-to-git/)

Document link: [migrate-to-git.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/collaborate/team-server/migrate-to-git.md)

## My Issue/Suggestion
can you show steps on how to do `migrate-to-git`? 

i already got SCRUM MASTER role, there is no steps what we can do.

**Comment by MariaShaposhnikova** [comment]
Hi @franksoong ,
If your app is eligible for migration, you should see the notification with the **Migrate to Git** button at the top of the **Team Server** screen in the Developer Portal. Clicking the button should be the only step for migration. 
I will add the screenshot to the documentation to make it more visual. I hope this helps.

Best regards,
Maria

**Comment by MariaShaposhnikova** [comment]
Hey @franksoong ,
I've added information about the notification on the **Team Server** screen and the button to click in [this commit](https://github.com/mendix/docs/commit/f650ac65a1b1783fba87c8d7f7202a56493956d5). I hope it makes the document more clear.

Best regards,
Maria
