### ISSUE TITLE
migrate-to-git

### ISSUE THREAD

**Issue by khazaddoom** [mendix/docs#5701]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [migrate-to-git](https://docs.mendix.com/developerportal/collaborate/migrate-to-git/)

Document link: [migrate-to-git.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/collaborate/team-server/migrate-to-git.md)

## My Issue/Suggestion

I cant find the steps to migration the mendix repo to GIT in this documentation page.

**Comment by MariaShaposhnikova** [comment]
Hi @khazaddoom ,
Thank you for your feedback! 
If your app is eligible for migration, you should see the notification with the **Migrate to Git** button at the top of the **Team Server** screen in the Developer Portal. Clicking the button should be the only step needed for migration.
I've added the information above to the document in [this commit](https://github.com/mendix/docs/commit/f650ac65a1b1783fba87c8d7f7202a56493956d5). I hope it makes more clear.

Best regards,
Maria
