### ISSUE TITLE
9.23

### ISSUE THREAD

**Issue by JZelenak** [mendix/docs#5709]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [9.23](https://docs.mendix.com/releasenotes/studio-pro/9.23/)

Document link: [9.23.md](https://github.com/mendix/docs/blob/development/content/en/docs/releasenotes/studio-pro/9/9.23.md)

## My Issue/Suggestion
I was not able to install this version, but I found a workarround.
I got the message "Internal error: ShellExecuteEx returned hProcess=0." Click OK the same message is displayed. Click OK again and the installation process terminates.

![Screenshot 2023-03-03 065757](https://user-images.githubusercontent.com/75006939/222642961-be7eb6e3-3bf6-4864-9fbe-c5c02251293d.jpg)

Here the workarround - if I don't click OK in the first message, the installation process continues.

**Comment by Adam-Dupaski** [comment]
Hi @JZelenak thanks for the message. This channel is for feedback on documentation itself, and this looks like a product problem that requires a Support ticket. Please contact Mendix Support - https://support.mendix.com/hc/en-us - to communicate this problem.
Cheers,
Adam

**Comment by Adam-Dupaski** [comment]
Hi @JZelenak , reopening this issue, as I created a Mendix Support ticket for it. I will update here upon resolution.

**Comment by Adam-Dupaski** [comment]
Hi @JZelenak I heard back from Mendix Support:

Thanks for reporting this issue to us and sharing the resolution.
This issue doesn't seems to be specific to Mendix Platform but a system issue.
Please make sure all the System requirements mentioned in the below document are installed correctly.
https://docs.mendix.com/refguide/system-requirements/
 
You can check below document to resolve the issue.
https://www.thewindowsclub.com/fix-shellexecuteex-failed-code-error-in-windows-10
https://answers.microsoft.com/en-us/windows/forum/all/shellexecuteex-error/4cec9d0c-8497-48ab-b273-67871e9f03c7
 
If you want to report any platform-related Mendix issue we recommend you to reach out to Mendix Support and you can also post your queries on our Mendix Forum.
https://support.mendix.com/hc/en-us
https://forum.mendix.com/
