### ISSUE TITLE
file-manager

### ISSUE THREAD

**Issue by uonlynik** [mendix/docs#5714]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [file-manager](https://docs.mendix.com/refguide/file-manager/)

Document link: [file-manager.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/pages/image-and-file-widgets/file-manager.md)

## My Issue/Suggestion

when file manager use with association it save file along with the reference object also. it does not store in virtual memory like other entity object. In my scenario i want to store multiple files in one entity, so i create two entity generalize with FileDocument and associate with the parent entity, but when i want to create multiple object of parent entity virtually file manager commit the object of both file entity along with the parent object also.

So, this is make very tedious to handle

**Comment by MariaShaposhnikova** [comment]
Hi @uonlynik ,

Thank you for your feedback! 
I have double-checked the document, but there is nothing I can improve from the documentation side as your feedback is about the widget in general. I suggest posting it in the [Mendix Forum](forum.mendix.com). If you post it as an [idea](https://docs.mendix.com/developerportal/community-tools/mendix-forum/#3-ideas) it can get upvoted and picked up my developers. I hope this helps.

Best regards,
Maria
