### ISSUE TITLE
configurations

### ISSUE THREAD

**Issue by SevYi** [mendix/docs#5718]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [configurations](https://docs.mendix.com/refguide/configuration/)

Document link: [configuration.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/app-explorer/app/app-settings/configuration.md)

## My Issue/Suggestion
If you can give some example in the document will be much more helpful

**Comment by MarkvanMents** [comment]
Hi there,
Sorry this has taken a year to implement, but there is now an example of a configuration in the documentation.
I hope this is makes the document more helpful.
Thanks for your suggestion - it is customer suggestions which help us to identify improvements we can make to our documentation.
Apologies again for not implementing your idea sooner.
Yours
Mark
