### ISSUE TITLE
nanoflows

### ISSUE THREAD

**Issue by scottwalkery** [mendix/docs#5719]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [nanoflows](https://docs.mendix.com/refguide/nanoflows/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/_index.md)

## My Issue/Suggestion
I wanted to learn more about nanoflows as a datasource

**Comment by Yiyun333** [comment]
Hi @scottwalkery,

Thank you for the feedback. I found an existing document about using nanoflows as a datasource: https://docs.mendix.com/refguide/nanoflow-source/

Please let me know if you need more information or you have more suggestions.

Best regards,
Yiyun

**Comment by Yiyun333** [comment]
Hi @scottwalkery,

Cross-references have also been added for the above document (https://github.com/mendix/docs/pull/5730). I hope this helps with finding relevant information in our documentation. 

Best regards,
Yiyun
