### ISSUE TITLE
installing-mendix-studio-pro

### ISSUE THREAD

**Issue by zjh1943** [mendix/docs#5720]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [installing-mendix-studio-pro](https://docs.mendix.com/refguide/install/)

Document link: [install.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/general/install.md)

## My Issue/Suggestion

We can not install the WebViewer2 with the `Evergreen Runtime installer` when offline, because the ` Evergreen Runtime installer` needs to download some files from the MS server. Suggest updating the instruction to ensure the user can install the whole environment when offline.

**Comment by MariaShaposhnikova** [comment]
Hi @zjh1943,
Thank you for your feedback! I have verified the information and updated the document in[ this commit](https://github.com/mendix/docs/pull/5745/commits/b1bd84a2edf064b85f4b88d8d6adc397d2f3f7e0).

Best regards,
Maria
