### ISSUE TITLE
mx-command-line-tool

### ISSUE THREAD

**Issue by elize-vdr** [mendix/docs#5728]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [mx-command-line-tool](https://docs.mendix.com/refguide/mx-command-line-tool/)

Document link: [mx-command-line-tool.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/general/mx-command-line-tool.md)

## My Issue/Suggestion
Perhaps the word `tree-way` was meant to be `three-way`

**Comment by MariaShaposhnikova** [comment]
Hi @elize-vdr!
Thanks a lot for your feedback, good catch! I've fixed the typo in [this commit](https://github.com/mendix/docs/commit/ecdb9a6f8c99d1a96da5ea3678e09539e1b7b364).

Best regards,
Maria
