### ISSUE TITLE
千帆玉符-sso-qianfan-single-sign-on

### ISSUE THREAD

**Issue by mengdix** [mendix/docs#5739]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [千帆玉符-sso-qianfan-single-sign-on](https://docs.mendix.com/developerportal/deploy/qianfan-sso/)

Document link: [qianfan-sso.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/tencent-deploy/qianfan-sso.md)

## My Issue/Suggestion

File download URL should be updated to:
https://mendix-cdn-prod-1305133312.cos.ap-shanghai.myqcloud.com/qianfansso/QianFanSSO.mpk

**Comment by Adam-Dupaski** [comment]
Hi @mengdix that looks the same as the current link used in section 4.1: 

https://mendix-cdn-prod-1305133312.cos.ap-shanghai.myqcloud.com/qianfansso/QianFanSSO.mpk

**Comment by mengdix** [comment]
Hi Adam, sorry, to be more specific, the case of the link is not correct. According to our team in some cases using the wrong case it will result in download failure. Could it be replaced with the suggested case above?

**Comment by Adam-Dupaski** [comment]
Thanks @mengdix - I see, it was the link text, not the actual URL of the link - updated: https://github.com/mendix/docs/commit/c96efb462a79cda3c01f6dce9069f4c8646909fd
