### ISSUE TITLE
login-behavior

### ISSUE THREAD

**Issue by vinicius-ambrosio-truechange** [mendix/docs#5744]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [login-behavior](https://docs.mendix.com/refguide/login-behavior/)

Document link: [login-behavior.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/runtime/login-behavior.md)

## My Issue/Suggestion

> Login behavior can be customized by implementing a custom Java action and registering it to be used instead of the default login action.
> 
> Cluster manager behavior currently cannot be changed.

This part would be clearer! 
* How can I proceed with 'registering it to be used instead of the default login action'?

A step-by-step guide would help!

**Comment by MarkvanMents** [comment]
Hi,
Thanks for reporting this, and sorry for the delay in responding.
I have spoken to our developers and updated the login-behavior document in PR #5856. I hope this gives you a bit more information and enables you to add the functionality you want.

Thank you for your feedback - it is important to us to get feedback from customers when the documentation is not clear or needs to be improved.
Yours
Mark van Ments.
