### ISSUE TITLE
export-mappings

### ISSUE THREAD

**Issue by ismkaya** [mendix/docs#5749]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [export-mappings](https://docs.mendix.com/refguide/export-mappings/)

Document link: [export-mappings.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/integration/mapping-documents/export-mappings.md)

## My Issue/Suggestion

Gibt es eine Begrenung bei der Einbindung einer JSON-Struktur? Ich habe sechs JSON-Objekte in einer JSON-Struktur, sehe aber fünf JSON-Objekt-Verknüpfungen, wenn ich das export mapping anwähle.

**Comment by johannahemminger** [comment]
Hi @ismkaya , thanks for opening this issue (and sorry I don't speak German!). I have checked with the team and verified that no doc update is needed at the moment. I suggest posting this question and specifics about your app in the [Mendix Forum](forum.mendix.com) so it's clear what are experiencing. I hope this helps!
