### ISSUE TITLE
debug-java-actions-remotely

### ISSUE THREAD

**Issue by elize-vdr** [mendix/docs#5786]
The following line is not good, place the line to paste in the `Extra JVM parameters` on a new line rather, I missed the hyphen `-` that is on the previous line's end, this line:

3. Go to the Server tab of the configuration, add the following line to the Extra JVM parameters field: `-
agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005`

Will be better like this: 

3. Go to the Server tab of the configuration, add the following line to the Extra JVM parameters field: 
`-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005`

**Comment by MarkvanMents** [comment]
Hi Elize,
Thanks for reporting this issue. Sorry about the delay in getting back to you.
I've tested it in Firefox and I don't get the strange wrapping which you identified. But I see that it wraps differently in Chrome and Edge and causes confusion.
Thanks for reporting this, I'd never have seen it in my reviews. I've updated the latest two versions of the document in this commit: https://github.com/mendix/docs/commit/b2c9a5b42a2fb5874a7060904d172442876a268e
Thanks for taking the trouble to report this and improve our documentation.
Please let us know if you see anything else which could be improved.
Yours
Mark van Ments.
