### ISSUE TITLE
microsoft-windows

### ISSUE THREAD

**Issue by Ravi-Chotaliya** [mendix/docs#5787]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [microsoft-windows](https://docs.mendix.com/developerportal/deploy/deploy-mendix-on-microsoft-windows/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/on-premises-design/ms-windows/_index.md)

## My Issue/Suggestion
Below rule is missing in the doc

```
<rule name="sso">
    <match url="^(sso/)(.*)" />
    <action type="Rewrite" url="http://localhost:8080/{R:1}{R:2}" />
</rule>
```

**Comment by katarzyna-koltun-mx** [comment]
Thank you for the feedback! This is only required when using the SAML module, so https://docs.mendix.com/appstore/modules/saml/ is likely the place to add it. In progress.

**Comment by katarzyna-koltun-mx** [comment]
The article (https://docs.mendix.com/appstore/modules/saml/) has been updated. We have added the requested item as a prerequisite.
