### ISSUE TITLE
email-connector

### ISSUE THREAD

**Issue by wpenris2** [mendix/docs#5798]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [email-connector](https://docs.mendix.com/appstore/connectors/email-connector/)

Document link: [email-connector.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/connectors/email-connector.md)

## My Issue/Suggestion

Please add documentation giving an example of a token that is used in an html template. The token format has changed (I believe); the old email module token does not work any more.

**Comment by johannahemminger** [comment]
Hi @wpenris2 , thanks for the submission! I am checking with the team on this and will get back to you as soon as possible.

**Comment by Tanuka-Majumder** [comment]
Hi @wpenris2, the latest email connector module uses mx model reflection version 6.2.0 and old email module also used the same version of mx model reflection. Therefore token format should not be changed. Can you please elaborate further on the token format issue.

**Comment by johannahemminger** [comment]
I will close this issue because there are no documentation updates to make, but if you continue to have this issue please feel free to open a Support ticket. Thanks again for bringing this to our attention!
