### ISSUE TITLE
widget-styling-guide radio btns missing

### ISSUE THREAD

**Issue by bartheijsconclusion** [mendix/docs#5802]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [widget-styling-guide](https://docs.mendix.com/refguide/mobile/designing-mobile-user-interfaces/widget-styling-guide/)

Document link: [native-styling-element-guide.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/mobile/designing-mobile-user-interfaces/native-styling-element-guide.md)

## My Issue/Suggestion

Hi, I miss the radio button in this list. Thank you!

**Comment by ConnorLand** [comment]
Hello @bartheijsconclusion ,

My apologies for your feedback item staying unaddressed for so long. Radio Buttons is [not available](https://docs.mendix.com/refguide/radio-buttons/) for native pages, and the document you commented is only for native-enabled widgets (please see the [intro](https://docs.mendix.com/refguide/mobile/designing-mobile-user-interfaces/widget-styling-guide/#native-mobile-styling) for more info).

May I suggest you use the pluggable, native-enabled [Radio Button Native](https://marketplace.mendix.com/link/component/116717)? It's documentation tab in the Marketplace has styling information for all its components.

You may also like playing around with[ RadioButton List](https://marketplace.mendix.com/link/component/20), but I am not sure if it will fit your use case.

Thank you for reaching out. We really value your questions, and if you find any errors in the Widget Styling Guide please let me know.

Connor
