### ISSUE TITLE
configuring-parallels

### ISSUE THREAD

**Issue by walterverburgtmendix** [mendix/docs#5826]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [configuring-parallels](https://docs.mendix.com/refguide/using-mendix-studio-pro-on-a-mac/)

Document link: [using-mendix-studio-pro-on-a-mac.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/general/using-mendix-studio-pro-on-a-mac.md)

## My Issue/Suggestion

Under '5 viewing your app on a testing device', step 3, the last semicolon should be removed. This should result in the following Host field input: {your IP address}:8080

Furthermore, it would be of help if the corresponding screenshot showed an input value in the host field, instead of an empty field,

**Comment by ConnorLand** [comment]
Hi Walter. I see what you mean -- the last semicolon is supposed to introduce the screenshot underneath it, but it can appear to be a part of the typed text. I'll change that so that it's clearer. Thanks for this feedback.
