### ISSUE TITLE
differences-between-git-and-svn

### ISSUE THREAD

**Issue by JesperPeterse** [mendix/docs#5827]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [differences-between-git-and-svn](https://docs.mendix.com/refguide/svn-git-differences/)

Document link: [svn-git-differences.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/version-control/svn-git-differences.md)

## My Issue/Suggestion
_change this_
Submits all local commits to the server. If other developers have pushed changes to the server that are not in your local app yet, you have to update/push first.

_To this_
Submits all local commits to the server. If other developers have pushed changes to the server that are not in your local app yet, you have to update/pull first.

**Comment by MariaShaposhnikova** [comment]
Hi @JesperPeterse ,
Thank you for your feedback, good catch! I have corrected the text in [this commit](https://github.com/mendix/docs/commit/14b83a6691c57288c289d258b706c6e06c6da77d). 

Best regards,
Maria
