### ISSUE TITLE
epics

### ISSUE THREAD

**Issue by joshuamoesa** [mendix/docs#5828]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [epics](https://docs.mendix.com/developerportal/collaborate/epics/)

Document link: [epics.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/collaborate/epics.md)

## My Issue/Suggestion

The first table in 3.3.2 contains a column name with a typo in it. See third column: "Additionnal".

**Comment by Adam-Dupaski** [comment]
Thanks @joshuamoesa for the feedback, fixed here: https://github.com/mendix/docs/commit/6669e58d5ec83d7fa787807ee169d8e2df82b729
