### ISSUE TITLE
upgrade-a-solution

### ISSUE THREAD

**Issue by Michiel-Bijlsma** [mendix/docs#5841]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [upgrade-a-solution](https://docs.mendix.com/appstore/creating-content/sol-upgrade/)

Document link: [sol-upgrade.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/creating-content/sol-solutions-impl-guide/sol-upgrade.md)

## My Issue/Suggestion

the beginning of the document starts with an example of Mendix 9.6.0 and the second part of the document is talking about upgrading he solution with the one click upgrade that is only available for version 9.21.0 and above, this is very confusing. Maybe contact David Hartveld to ask about the correct communication of this feature, thanks a lot!

**Comment by Adam-Dupaski** [comment]
Hi @Michiel-Bijlsma thanks for the feedback, the `9.6` reference was just a generic version example and not to meant to have any dependency, it's been changed to `10.0.`
