### ISSUE TITLE
use-marketplace-content-in-studio-pro

### ISSUE THREAD

**Issue by melvingrootenboers** [mendix/docs#5846]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [use-marketplace-content-in-studio-pro](https://docs.mendix.com/appstore/general/app-store-content/)

Document link: [app-store-content.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/general/app-store-content.md)

## My Issue/Suggestion
The image used in step 2.1.5 shows the Blank App. The Blank App is a template, and those will no longer be shown in the Marketplace in Studio Pro. I suggest to use the "Community Commons" module instead.

**Comment by Adam-Dupaski** [comment]
Thanks for the heads-up here @melvingrootenboers - I made these changes! 
Cheers,
Adam
