### ISSUE TITLE
Issue while connecting to Azure SQL Database

### ISSUE THREAD

**Issue by tsrikanth2511** [mendix/docs#5860]
## My Issue
I installed Database Connector module from Mendix marketplace.
I was not able to connect from mendix app to Azure SQL Database while using ActiveDirectoryPassword authentication mode on database. The connection was failing with below error message
![image](https://user-images.githubusercontent.com/69192814/231166348-df0a6cf5-6196-4d34-8da1-e1a07e1dfd7b.png)

After adding msal4j jar I was getting below error 

![image](https://user-images.githubusercontent.com/69192814/231169486-16dafe13-0cf7-46e9-a4d0-18287149ea9b.png)
I was assuming something was wrong with username and password, later found that jackson-databind.jar was missing.

## Suggestion
I would expect these kind of scenarios covered in your documentation and clear error messages.

**Comment by tsrikanth2511** [comment]
I also had to add jackson-core, jackson-annotations jar files

**Comment by johannahemminger** [comment]
Hi @tsrikanth2511 , thanks very much for opening this issue. I will discuss this with the team and then will make further documentation updates.

**Comment by johannahemminger** [comment]
@tsrikanth2511 thanks for your patience. I have passed along your feedback on the error messages to the team, and have opened PR #5904 to bring further attention to the JAR dependencies. There are many use cases for this connector and we aren't able to document all possibilities, but if you see something else missing please let me know, or feel free to open a pull request to update the doc with your suggestion. Thanks for helping make our docs better!
