### ISSUE TITLE
administration

### ISSUE THREAD

**Issue by YoungCheese** [mendix/docs#5952]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [administration](https://docs.mendix.com/appstore/modules/administration/)

Document link: [administration.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/administration.md)

## My Issue/Suggestion

give a guide how to upgrade this module from marketplace

**Comment by Adam-Dupaski** [comment]
Hi @YoungCheese thanks for your feedback. We have documentation on upgrading modules here: https://docs.mendix.com/appstore/general/app-store-content/#module

Is this what you're looking for?
