### ISSUE TITLE
aws-connectors - twinmaker

### ISSUE THREAD

**Issue by samverma05** [mendix/docs#5956]
can you please let me know when the AWS - Twinmaker documentation will be available ? 

Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [aws-connectors](https://docs.mendix.com/appstore/aws-connectors/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/connectors/aws/_index.md)

**Comment by katarzyna-koltun-mx** [comment]
The documentation has been published: https://docs.mendix.com/appstore/connectors/aws/aws-iot-twinmaker/

Let us know if you have any further questions or comments!
