### ISSUE TITLE
data-view-and-list-view

### ISSUE THREAD

**Issue by ricketyrack** [mendix/docs#5992]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [data-view-and-list-view](https://docs.mendix.com/studio/page-editor-data-view-list-view/)

Document link: [page-editor-data-view-list-view.md](https://github.com/mendix/docs/blob/development/content/en/docs/studio/page-editor/page-editor-widgets/page-editor-data-view-list-view.md)

## My Issue/Suggestion
Please indicate whether a Microflow data source is invoked when the 'Visible' attribute is false.  Hopefully, it is not since it is unnecessary.

**Comment by MariaShaposhnikova** [comment]
Hi @ricketyrack, 
Thanks a lot for your feedback!
Can you please give a bit more details on what you mean by "Microflow data source is invoked when the 'Visible' attribute is false"? If you are asking whether a Microflow data source is triggered when it is hidden by a condition (e.g. by user role or expression), the answer is no. A microflow datasource is not triggered when the widget is conditionally hidden. 
Did I understand the question correctly? In this case I can add this information to the documentation.

Best regards,
Maria

**Comment by MariaShaposhnikova** [comment]
Hi @ricketyrack ,

I will close this issue, I hope my answer above contained the information you needed. If you still have questions, please feel free to contact us.

Best regards,
Maria
