### ISSUE TITLE
leave-delete-or-deactivate-an-app

### ISSUE THREAD

**Issue by 5cientist** [mendix/docs#6015]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [leave-delete-or-deactivate-an-app](https://docs.mendix.com/developerportal/collaborate/leave-delete-app/)

Document link: [leave-delete-app.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/collaborate/general-settings/leave-delete-app.md)

## My Issue/Suggestion

i am not able to  switch back to Mendix Public Cloud for delete

**Comment by MarkvanMents** [comment]
Hi,
This issue mechanism is for reporting problems with the documentation. Your comment seems to be about a problem you are having with the way your app has been set up.
If you are still having an issue, please contact [Mendix Support](https://support.mendix.com) or, alternatively, ask a question on the [Mendix forum](https://forum.mendix.com/) where there are many community members who may be able to help you.

If you have a specific issue with the process description in the documentation, please feel free to raise a new issue and we will be happy to investigate for you and update the process to make it clearer or indicate additional steps which might be needed.
Yours
Mark van Ments
