### ISSUE TITLE
deploy-your-first-mendix-native-mobile-app with private gitlab instance

### ISSUE THREAD

**Issue by bufferoverflow** [mendix/docs#6018]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [deploy-your-first-mendix-native-mobile-app](https://docs.mendix.com/refguide/mobile/distributing-mobile-apps/building-native-apps/deploying-native-app/)

Document link: [deploying-native-app.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/mobile/distributing-mobile-apps/building-native-apps/deploying-native-app.md)

## My Issue/Suggestion

I like to deploy a mendix native mobile app using a private GitLab instance, do you have an example on how to do this?

**Comment by ConnorLand** [comment]
Hello @bufferoverflow ,

Apologies for the late reply. For your specific use case, I recommend you follow [this guide](https://medium.com/mendix/connecting-mendix-with-gitlab-241ebf960fbc).

If you have any issues implementing it, please file a [support ticket](https://support.mendix.com/hc/en-us).

Thank you for reaching out to documentation,

Connor
