### ISSUE TITLE
build-a-pluggable-native-widget

### ISSUE THREAD

**Issue by zjh1943** [mendix/docs#6027]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [build-a-pluggable-native-widget](https://docs.mendix.com/howto/extensibility/build-native-widget/)

Document link: [build-native-widget.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/extensibility/build-native-widget.md)

## My Issue/Suggestion

In the chapter 3.38: https://docs.mendix.com/howto/extensibility/build-native-widget/#338-adding-a-custom-default-style
The file `test/MxTestApp/theme/styles/native/app/custom.js` can not be found in the mendix project directory.

**Comment by ConnorLand** [comment]
Hello @zjh1943 ,

Apologies for the delayed response, and thank you for reaching out. When this document was written, we did not observe this error. You might find success discussing this issue with users on the [Mendix Forum](https://forum.mendix.com/index3.html).

If your development issue persists, please file a [Mendix Support TIcket](https://support.mendix.com/hc/en-us) so they can help troubleshoot your issue.

Thank you for reaching out to documentation,

Connor
