### ISSUE TITLE
logistic-regression-example

### ISSUE THREAD

**Issue by chelsealeeveenstra** [mendix/docs#6040]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [logistic-regression-example](https://docs.mendix.com/refguide/machine-learning-kit/using-ml-kit/logistic-regression/)

Document link: [logistic-regression-example.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/logistic-regression-example.md)

## My Issue/Suggestion

All the links to the Logistic regression example in the in the [Mendix ML Kit Demo Respository ](https://github.com/mendix/mlkit-demo-apps#getting-started). are not working.

**Comment by johannahemminger** [comment]
@chelsealeeveenstra thanks very much for opening this issue, I'll take a look!

**Comment by johannahemminger** [comment]
@chelsealeeveenstra Sorry about that, I have updated the links to point to the [new repo](https://github.com/mendix/mlkit-example-app) in PR #6041 . I will check everything again and then close this issue once I've verified that all are OK. Thanks for reporting this and helping improve our documentation!

**Comment by chelsealeeveenstra** [comment]
It’s working now! Thank you 😊

Met vriendelijke groet,

***@***.***
[Afbeelding met logo  Automatisch gegenereerde beschrijving]
 Make the future happen

 ***@***.*** <https://www.capegroep.nl/>  ***@***.*** <https://www.facebook.com/capegroep/>  ***@***.*** <https://www.linkedin.com/company/capegroep>
  Chelsea Veenstra
  Consultant

    Mobiel:
06-18351355
    Mail:
***@***.******@***.***>
    Website:
www.capegroep.nl<http://www.capegroep.nl/>
***@***.***


Van: Johanna Hemminger ***@***.***>
Verzonden: vrijdag 12 mei 2023 09:50
Aan: mendix/docs ***@***.***>
CC: Chelsea Veenstra ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [mendix/docs] logistic-regression-example (Issue #6040)


@chelsealeeveenstra<https://github.com/chelsealeeveenstra> Sorry about that, I have updated the links to point to the new repo<https://github.com/mendix/mlkit-example-app> in PR #6041<https://github.com/mendix/docs/pull/6041> . I will check everything again and then close this issue once I've verified that all are OK. Thanks for reporting this and helping improve our documentation!
