### ISSUE TITLE
to-string

### ISSUE THREAD

**Issue by nickvdmunt** [mendix/docs#6052]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [to-string](https://docs.mendix.com/refguide/to-string/)

Document link: [to-string.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/expressions/to-string.md)

## My Issue/Suggestion
Please explain what happens when an empty object/attribute is passed.

**Comment by Yiyun333** [comment]
Hi @nickvdmunt,

Thank you for the question. 

I've just confirmed with the dev team. If you pass an empty object/attribute, you will get an empty string. I've also updated the doc accordingly. 

I am closing this issue now. Please let us know if you have further questions.

Kind regards,
Yiyun
