### ISSUE TITLE
use-the-odata-connector-for-sap-solutions

### ISSUE THREAD

**Issue by yehoshouaGPT** [mendix/docs#6064]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [use-the-odata-connector-for-sap-solutions](https://docs.mendix.com/partners/sap/use-sap-odata-connector/)

Document link: [use-sap-odata-connector.md](https://github.com/mendix/docs/blob/development/content/en/docs/partners/sap/use-sap-odata-connector.md)

## My Issue/Suggestion
products instead of customers : 

_In the microflow, make the return value of the microflow **List of Products**. This is so that you can call the microflow as a data source in a page._

**Comment by MarkvanMents** [comment]
Thanks for spotting this error.
I have corrected it in the commit https://github.com/mendix/docs/commit/f09c9190be30ed4bfdcbf70b95eaa9cb9735abf0
Thanks for taking the time to contact us - we rely on customers to tell us about errors they see and make the documentation of Mendix better for everyone.
Yours
Mark van Ments.
