### ISSUE TITLE
apd-installation-guides

### ISSUE THREAD

**Issue by joshuamoesa** [mendix/docs#6065]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [apd-installation-guides](https://docs.mendix.com/appstore/partner-solutions/apd/ig/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/partner-solutions/apd/ig/_index.md)

## My Issue/Suggestion

The links under '2 Main Documents in This Section' are broken. 
Please also review all other links under APD because more links are broken. 
Thanks.

**Comment by Adam-Dupaski** [comment]
Thanks very much for this feedback item @joshuamoesa - I fixed all the links (and screenshots) in this PR: https://github.com/mendix/docs/pull/6068
Cheers,
Adam
