### ISSUE TITLE
microsoft-sql-server

### ISSUE THREAD

**Issue by tieniber** [mendix/docs#6099]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [microsoft-sql-server](https://docs.mendix.com/developerportal/deploy/mendix-on-windows-microsoft-sql-server/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/on-premises-design/ms-windows/sql-server/_index.md)

## My Issue/Suggestion
There are documents in this section that are not linked on this page.

**Comment by Adam-Dupaski** [comment]
Thanks @tieniber for pointing this out, I've fixed it in this commit: https://github.com/mendix/docs/commit/17381208821feb7b2611a6eebb4d5881fe1c4355
Cheers,
Adam
