### ISSUE TITLE
node-permissions

### ISSUE THREAD

**Issue by CarlesZ** [mendix/docs#6125]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [node-permissions](https://docs.mendix.com/developerportal/deploy/node-permissions/)

Document link: [node-permissions.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/mendix-cloud-deploy/node-permissions.md)

## My Issue/Suggestion
Please explain how to unlink a node from an app

**Comment by Adam-Dupaski** [comment]
Hi Carles, saw your post on Slack as well, does this cover what you're looking for?: https://docs.mendix.com/developerportal/deploy/licensing-apps/#unlink-licensed

**Comment by CarlesZ** [comment]
Yes, you're right. I was reading the document but I skip this part! :-) Sorry and thanks for being so quick!

**Comment by Adam-Dupaski** [comment]
No problem, glad we sorted it out, cheers!
