### ISSUE TITLE
enumerations-in-expressions

### ISSUE THREAD

**Issue by joshsonofmichael** [mendix/docs#6167]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [enumerations-in-expressions](https://docs.mendix.com/refguide/enumerations-in-expressions/)

Document link: [enumerations-in-expressions.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/expressions/enumerations-in-expressions.md)

## My Issue/Suggestion

Show an example of how to evaluate two enumeration values to check to see if they are the same

**Comment by Yiyun333** [comment]
Hi @joshsonofmichael,

Thank you for the suggestion. I will discuss it with the developers to get a good example and add it to the documentation. I will keep you posted.

Kind regards,
Yiyun

**Comment by exec-astraea** [comment]
Hello @joshsonofmichael!
By "evaluate two enumeration values to check to see if they are the same" do you mean example with basic comparison? 

Like that?
```
if $Order/Status = MyFirstModule.OrderStatus.Completed
then true else false
```

**Comment by Yiyun333** [comment]
Hello @joshsonofmichael,

A kind reminder: please provide us some further information by replying to the [above question](https://github.com/mendix/docs/issues/6167#issuecomment-1607389289) from @wrdsnd. 

Thanks!

**Comment by joshsonofmichael** [comment]
Yes having an example  like the one you gave would be very helpful. Even just to showcase the syntax.

**Comment by Yiyun333** [comment]
Thank you for your feedback! @joshsonofmichael 

I just added the example to the doc and it will be online soon.

I am closing this issue now. Please let us know in the future if you have any more feedback :)

Kind regards,
Yiyun
