### ISSUE TITLE
native-app-prerequisites-and-troubleshooting

### ISSUE THREAD

**Issue by CarlesZ** [mendix/docs#6175]
Please use the form below, leaving the prefilled data to help us. Thank you.

No information about how to run old Mendix Native projects despite of the release notes of the Make it Native app says that this documentation explain how to run non 9.24.X app. 

Page link: [native-app-prerequisites-and-troubleshooting](https://docs.mendix.com/refguide/mobile/getting-started-with-mobile/prerequisites/)

Document link: [prerequisites.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/mobile/getting-started-with-mobile/prerequisites.md)

**Comment by ConnorLand** [comment]
Hello @CarlesZ ,

To use the MIN9 app with a Mendix app below 9.24, you must use a **custom developer app**. The Make It Native 9 Release Notes link to this information in the [blue info box at the top of the page](https://docs.mendix.com/releasenotes/mobile/make-it-native-9/).

More specifically, in the _Use Make It Native 9 with an Older Version of Mendix 9_ section of [Native App Prerequisites and Troubleshooting](https://docs.mendix.com/refguide9/mobile/getting-started-with-mobile/prerequisites/#use-MIN-older) you can find a link to to the [Creating a Custom Developer App](https://docs.mendix.com/refguide9/mobile/distributing-mobile-apps/building-native-apps/how-to-devapps/) tutorial.

However, we recommend using 9.24 for all Mendix 9 apps if possible, as that version has [LTS status](https://docs.mendix.com/releasenotes/studio-pro/lts-mts/#lts).

Best,

Connor
