### ISSUE TITLE
parse-integer

### ISSUE THREAD

**Issue by joepveenman** [mendix/docs#6202]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [parse-integer](https://docs.mendix.com/refguide/parse-integer/)

Document link: [parse-integer.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/expressions/parse-integer.md)

## My Issue/Suggestion

The Parse-integer functie didn't work in a Xpath for me. 

- Using the word 'casting' or 'type conversion' would be useful if you want experienced programmers to easily find the information they need and helps new programmers learning the right terms.

**Comment by Yiyun333** [comment]
Hi @joepveenman,

Thank you for your feedback. 

The parseInteger function is indeed not supported in XPath queries. For more information on what's supported in XPath queries, please see [XPath Constraints](https://docs.mendix.com/refguide/xpath-constraints/) and [XPath Aggregate Functions](https://docs.mendix.com/refguide/xpath-aggregate-functions/).

I've added words like "casting" and "type conversion" as tags for this [Parse Integer](https://docs.mendix.com/refguide/parse-integer/) doc. I hope this can help with the search results. Given that Mendix is a low-code platform, we tend to use words that non-coders/low-coders can also easily understand. However, still thanks for the feedback! 

I am closing this issue now. Please let us know if you have any more feedback in the future.

Kind regards,
Yiyun
