### ISSUE TITLE
broken-template-link

### ISSUE THREAD

**Issue by sbont** [mendix/docs#6219]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [5.1 Using a template](https://docs.mendix.com/developerportal/community-tools/contribute-to-the-mendix-documentation/#51-using-a-template)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/community-tools/contribute-to-the-mendix-documentation/_index.md)

My Issue/Suggestion
Link to the template is broken (and I can't find the template in the folder either)

**Comment by Adam-Dupaski** [comment]
Thank you @sbont for the heads-up - fixed here: https://github.com/mendix/docs/commit/81a2631b80e367d6358303b5b0722922f36848ef

Cheers,
Adam
