### ISSUE TITLE
customize-styling

### ISSUE THREAD

**Issue by GerbenDol** [mendix/docs#6235]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [customize-styling](https://docs.mendix.com/howto/front-end/customize-styling-new/)

Document link: [customize-styling-new.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/front-end/atlas-ui/customize-styling-new.md)

## My Issue/Suggestion
It says to include the following code: `@import "../../themesource/mytheme/web/custom-variables.scss`
This is missing a `"` at the end and thus not working.

**Comment by ConnorLand** [comment]
Hi @GerbenDol . 

Thank you for bringing this to our attention. I have fixed the punctuation error in the code example, and the docs will be correct when I push my changes to our website.

Thank you for contributing to the documentation,

Connor
