### ISSUE TITLE
list-view

### ISSUE THREAD

**Issue by RCshare** [mendix/docs#6265]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [list-view](https://docs.mendix.com/refguide/list-view/)

Document link: [list-view.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/pages/data-widgets/list-view.md)

## My Issue/Suggestion

Can you give us a solution to hide the empty section when no data is load by the list view component ? ( i found no more solution except a workaround here (https://forum.mendix.com/link/space/microflows/questions/88589))

Regards

**Comment by ConnorLand** [comment]
Hello @RCshare ,

Apologies for the late reply. Thank you for checking the Forum. For deeper development advice, please file a [Support Ticket ](https://support.mendix.com/hc/en-us) to receive help.

Thanks for reaching out to documentation,

Connor
