### ISSUE TITLE
mendix-mini-surveys

### ISSUE THREAD

**Issue by omarmayland** [mendix/docs#6271]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [mendix-mini-surveys](https://docs.mendix.com/developerportal/collaborate/product-insights/)

Document link: [product-insights.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/collaborate/product-insights.md)

## My Issue/Suggestion
says surve(s) instead of survey(s) in multiple places

**Comment by Luyao-Zhang-1** [comment]
I have fixed the typos. Thank you for reporting this!
