### ISSUE TITLE
export-to-excel

### ISSUE THREAD

**Issue by Minus50DKP** [mendix/docs#6282]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [export-to-excel](https://docs.mendix.com/howto/integration/using-the-excel-exporter/)

Document link: [using-the-excel-exporter.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/integration/using-the-excel-exporter.md)

## My Issue/Suggestion
The guide is missing lots of steps and screenshots. Especially paragraph 8, where lots of steps and explaination is skipped.

**Comment by Luyao-Zhang-1** [comment]
Thanks for reporting this to us. I already added this issue to my backlog. I will take a holiday soon. I will get back to you on this when I am back.

**Comment by Luyao-Zhang-1** [comment]
Hi @Minus50DKP Could you please specify where you got stuck when you follow this how-to?
