### ISSUE TITLE
scheduled-events-task-queue

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#6289]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [scheduled-events-task-queue](https://docs.mendix.com/refguide9/scheduled-events-task-queue/)

Document link: [scheduled-events-task-queue.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide9/modeling/resources/scheduled-events/scheduled-events-task-queue.md)

## My Issue/Suggestion
There is a constraint that "You cannot run more than ten scheduled events in parallel per cluster node."

In a large project with many scheduled events running in different modules it would not be hard to exceed this limit.  Can you please say what will happen if the limit is exceeded. For example, will the jobs run in sequence from the queue when another scheduled event completes, or will they fail to run? Is there a log message that we can search for? 

Thanks (asking for a client)

**Comment by MarkvanMents** [comment]
Hi Chris,
Thanks for your suggestion. I have taken this up with the developers and they have said that the eleventh event will be queued and run once one of the current events has completed.
I'm updating the documentation in Pull Request #6361,
Thanks for suggesting this improvement - we rely on feedback to improve the Mendix documentation.
Yours
Mark van Ments
