### ISSUE TITLE
system-texts

### ISSUE THREAD

**Issue by viktororosso** [mendix/docs#6300]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [system-texts](https://docs.mendix.com/refguide/system-texts/)

Document link: [system-texts.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/app-explorer/app/system-texts.md)

## My Issue/Suggestion
How can I use them? I cannot 'find usages' on them, how do I know where they are used? Please provide a small example/picture where they are used.

**Comment by Yiyun333** [comment]
Hi @viktororosso,

Thank you very much for your feedback.

System texts are used automatically in the system normally as an information or an error message. In Mendix Studio Pro, if you go to **App Explorer** > **App "AppName"** > **System Texts**, you can see all the system texts that are available for now and where they are used. You can also change the texts by clicking on the texts in the **Text** column and editting the texts directly. 

I have also updated the [system-texts](https://docs.mendix.com/refguide/system-texts/) doc accordingly and added an example with an image: https://github.com/mendix/docs/pull/6327.

I am closing this issue for now but please let me know if you have any further feedback on this. 

Kind regards,
Yiyun
