### ISSUE TITLE
consume-a-rest-service

### ISSUE THREAD

**Issue by kirti175** [mendix/docs#6311]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [consume-a-rest-service](https://docs.mendix.com/refguide/integration/consume-a-rest-service/)

Document link: [consume-a-rest-service.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/consume-a-rest-service.md)

**Comment by katarzyna-koltun-mx** [comment]
Thank you for contacting us. I will discuss the suggestion with the team and inform you if we introduce this change.

**Comment by katarzyna-koltun-mx** [comment]
Are you looking for a specific example to use in your app? If you need help applying the API method for your specific use case, the best place to ask for examples is the [Mendix Ideas Forum](https://forum.mendix.com/p/community), where you can discuss the use case with other members. 

Let me know if that helps solve your issue, or if you need further documentation help. I will keep this issue open until next week in case you need assistance from me.
