### ISSUE TITLE
xpath-expressions

### ISSUE THREAD

**Issue by JesperVerschoor** [mendix/docs#6326]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [xpath-expressions](https://docs.mendix.com/refguide/xpath-expressions/)

Document link: [xpath-expressions.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md)

## My Issue/Suggestion
Please include more information on performance cost when using XPath queries

**Comment by Yiyun333** [comment]
Hi @JesperVerschoor,

Thank you for your feedback. 

We currently have [XPath best practices](https://docs.mendix.com/refguide/community-best-practices-for-app-performance/#7-xpath-best-practices) for app performance, [Xpath best practices](https://docs.mendix.com/refguide/dev-best-practices/) for app developement, and [some recommendations from our Best Practice bot](https://docs.mendix.com/refguide/performance-best-practices/) that are related to XPath (you can search in the doc for any XPath-related recommendations).

Are these docs relevant to your question? Please specify a bit more on what aspect of performance cost you want to know about in terms of using XPath queries. Thank you!

Kind regards,
Yiyun

**Comment by Yiyun333** [comment]
@JesperVerschoor 

Can you please let me know whether the docs provided above have the information you are looking for?

I will wait for another week. If I haven't received a reply then, I will close this issue. 

Kind regards,
Yiyun

**Comment by Yiyun333** [comment]
@JesperVerschoor 

I haven't received a reply yet, so I am closing this issue for now. Please let us know in the future if you have more feedback.

Kind regards,
Yiyun
