### ISSUE TITLE
deep-link

### ISSUE THREAD

**Issue by Larvi77** [mendix/docs#6328]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [deep-link](https://docs.mendix.com/appstore/modules/deep-link/)

Document link: [deep-link.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/deep-link.md)

## My Issue/Suggestion
![image](https://github.com/mendix/docs/assets/108678706/7d46e91c-e291-4796-8d54-bc4b0899c3a6)
For the Headline of Chapter 3.4: Instead of "3.4 Adding the Configuration Overview Snippet the Custom Admin Page"
would not "3.4 Adding the Configuration Overview Snippet to Custom Admin Page" be more correct?

**Comment by Yiyun333** [comment]
Hi @Larvi77,

Nice catch! I just corrected it, and the right version will be online soon. Thanks!

Kind regards,
Yiyun
