### ISSUE TITLE
upgrading-from-mendix-studio-pro-9-to-10

### ISSUE THREAD

**Issue by rgrim** [mendix/docs#6332]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [upgrading-from-mendix-studio-pro-9-to-10](https://docs.mendix.com/refguide/upgrading-from-9-to-10/)

Document link: [upgrading-from-9-to-10.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/installation/upgrading-from-9-to-10.md)

## My Issue/Suggestion

Can we add a line mentioning that the migration to Git is mandatory before upgrading? A customer had this issue after following the documentation. Thanks for your help ! 
Romain Grimmonpré

**Comment by katarzyna-koltun-mx** [comment]
@rgrim Thank you for reporting the issue. I will look into it and let you know about any document updates.

**Comment by katarzyna-koltun-mx** [comment]
@ConnorLand here's the migration document request.

**Comment by ConnorLand** [comment]
Hello @rgrim ,

You're right, we need this information more visible. I've added the information here in the 9 to 10 migration document: https://github.com/mendix/docs/commit/d807f00727fbde5ee3588470ae632c08a255217f

Thank you for your contribution to Mendix's documentation,

Connor
