### ISSUE TITLE
restore-a-backup

### ISSUE THREAD

**Issue by pietervercammen** [mendix/docs#6341]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [restore-a-backup](https://docs.mendix.com/developerportal/operate/restore-backup/)

Document link: [restore-backup.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/operate/backups/restore-backup.md)

## My Issue/Suggestion

We got some internal feedback that it would be possible to do a point in time restore via a support ticket, can we add that to our documentation?

Pieter

**Comment by MarkvanMents** [comment]
Hi Pieter,
Thanks for the suggestion.
With our ongoing improvements to backups, it should not be necessary for customers to get a point in time restore as part of their regular processes. This would be too much of a drain on the support resources.
If a customer has a specific issue which means they need to do a point in time restore, then they are likely to be in contact with support in any case, and support can then discuss with them the need to do a point in time restore.
Therefore, after discussion with support, I do not think it is appropriate to have this in our regular documentation.

**Comment by pietervercammen** [comment]
Hi Mark

I strongly disagree. We have cases where we lost mendix cloud ops as we were not aware it was possible at all.

I have done data management and backups in my 14 years prior to mendix. And pit restores are quite common for critical databases.

A footnote that it is possible would be good to convince certain customers to put certain workloads in our cloud.

Even if the note states: for premium resources only.

Pieter



Sent from my Galaxy


-------- Original message --------
From: Mark van Ments ***@***.***>
Date: 27/07/2023 16:51 (GMT+01:00)
To: mendix/docs ***@***.***>
Cc: Pieter Vercammen ***@***.***>, Author ***@***.***>
Subject: Re: [mendix/docs] restore-a-backup (Issue #6341)


Hi Pieter,
Thanks for the suggestion.
With our ongoing improvements to backups, it should not be necessary for customers to get a point in time restore as part of their regular processes. This would be too much of a drain on the support resources.
If a customer has a specific issue which means they need to do a point in time restore, then they are likely to be in contact with support in any case, and support can then discuss with them the need to do a point in time restore.
Therefore, after discussion with support, I do not think it is appropriate to have this in our regular documentation.

**Comment by MarkvanMents** [comment]
Hi Pieter,
Thanks for the additional information.
I'll pick this up internally in the **Support** channel of Slack rather than having a long discussion via GitHub.
Mark
