### ISSUE TITLE
export-to-excel

### ISSUE THREAD

**Issue by unnati1999** [mendix/docs#6354]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [export-to-excel](https://docs.mendix.com/howto/integration/using-the-excel-exporter/)

Document link: [using-the-excel-exporter.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/integration/using-the-excel-exporter.md)

**Comment by MarkvanMents** [comment]
Hi Unnati,
I see you have raised a documentation issue on Mendix, but I can't see what your feedback is.
Can you add something, or let me know I can close it if you opened it by accident.
Thanks
Mark

**Comment by MarkvanMents** [comment]
No response received - closing this issue.
Please open another issue if you have some comments or suggestions for the Mendix documentation site.
Thanks.
