### ISSUE TITLE
export-to-excel

### ISSUE THREAD

**Issue by JuanleRoex** [mendix/docs#6355]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [export-to-excel](https://docs.mendix.com/howto/integration/using-the-excel-exporter/)

Document link: [using-the-excel-exporter.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/integration/using-the-excel-exporter.md)

## My Issue/Suggestion

1. Describe in more detail with a multi-sheet excel export.
2. Provide a sample App to demonstrate the Export process.

**Comment by Luyao-Zhang-1** [comment]
Hi @JuanleRoex Thanks for your suggestion. 

I added info about exporting multiple entities into separate sheets. Please refer to step 10 in the [Creating the Worksheet Layout](https://docs.mendix.com/howto/integration/using-the-excel-exporter/#create-worksheet) section in the doc. Hope this helps! 
Thank you again for helping us improve the doc. Please feel free to contact us again if you find any information missing or outdated in our docs.

Best regards,
Luyao
