### ISSUE TITLE
build-a-pluggable-web-widget-part-1

### ISSUE THREAD

**Issue by laurenra7** [mendix/docs#6370]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [build-a-pluggable-web-widget-part-1](https://docs.mendix.com/howto/extensibility/create-a-pluggable-widget-one/)

Document link: [create-a-pluggable-widget-one.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-one.md)

## My Issue/Suggestion

"npm start" in Step 3 of [3.3 Adding the Attribute](https://docs.mendix.com/howto/extensibility/create-a-pluggable-widget-one/#33-adding-the-attribute) does not work. The error is:

```
'pluggable-widgets-tools' is not recognized as an internal or external command,    
operable program or batch file.
```

This is solved by first running "npm install" or "npm install --legacy-peer-deps" which is not explained in any prior step. Please add this.

**Comment by MarkvanMents** [comment]
@ConnorLand - I think you are best placed to handle this one?

**Comment by ConnorLand** [comment]
Hi yes, we are currently making edits to this document. I will take this issue onboard for that round of revisions.

**Comment by ConnorLand** [comment]
Hello,

Running **npm install --legacy-peer-deps** is suggested right before 3.3, at the end of the 3.2 Widget Scaffolding section:

"Note that whenever it is required to reinstall NPM package dependencies inside the scaffolded widget development app with an NPM version of 7 or higher, make sure to run the installation script with an extra flag: npm install --legacy-peer-deps."


Best,

Connor
