### ISSUE TITLE
migrate-from-to-a-different-public-cloud-datacenter

### ISSUE THREAD

**Issue by dan-covaliu** [mendix/docs#6379]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [migrate-from-to-a-different-public-cloud-datacenter](https://docs.mendix.com/developerportal/deploy/migrating-on-public-cloud/)

Document link: [migrating-to-different-cloud.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/migrating-to-different-cloud.md)

## My Issue/Suggestion
The title is confusing; the use of the form ` from to`  is confusing

**Comment by katarzyna-koltun-mx** [comment]
Thank you for reporting the issue. I've fixed the typo, the update should be published today.
