### ISSUE TITLE
native-mobile-styling

### ISSUE THREAD

**Issue by TKeuterMX** [mendix/docs#6380]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [native-mobile-styling](https://docs.mendix.com/refguide8/native-styling-refguide/)

Document link: [native-styling-refguide.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md)

## My Issue/Suggestion

There is an error in section 11.21 regarding the IntroScreen widget. The default class to style all into screen widgets is not correct and instead refers to the one of the Animation widget.

**Comment by ConnorLand** [comment]
Hi @TKeuterMX , thanks for bringing this to my attention. I have fixed the issue and the changes will be live on the site in a few minutes. Have a nice day.
