### ISSUE TITLE
Custom Dropdown Overlapping in Datagrid2 with Dynamic Content and Virtual Pagination

### ISSUE THREAD

**Issue by MirageG23** [mendix/docs#6406]
![screenshot](https://github.com/mendix/docs/assets/140045304/3a313dbc-a8f5-43c2-a7fc-73eabe7044b1)

**Issue Description:**
In our application, we have observed that when a column is set to dynamic content and contains a custom dropdown control, a problem arises. Specifically, when the dropdown menu list expands, the last row in Datagrid2 experiences an overlap with the parent Datagrid2. This issue is particularly pronounced when the properties of Datagrid2 are configured for 'virtual pagination'.

**Observed Behavior:**
Despite customizing the CSS style of the dropdown control to include a higher z-index value, the dropdown list still gets obscured by the parent Datagrid2. This overlap severely hampers the usability and readability of the interface, affecting the overall user experience.

**Expected Behavior:**
We expect that the custom dropdown control's expanded menu list should not overlap with the parent Datagrid2. Even with 'virtual pagination' enabled, the dropdown list should maintain its distinct visual hierarchy and remain unaffected by the expanding Datagrid2.

**Steps to Reproduce:**
Enable 'dynamic content' option for a column in Datagrid2.
Add a custom dropdown control to the column.
Populate the dropdown with sufficient data to expand the dropdown menu list.
Enable 'virtual pagination' properties for Datagrid2.
Observe the last row in Datagrid2 when the dropdown menu list expands.

**Additional Information:**
- The issue persists despite our attempts to modify the z-index value through customized CSS styles.
- We have tested this behavior across browsers (Google Chrome & Microsoft Edge) using the latest Mendix Studio Pro 10.1.1, and the problem remains consistent.

For your convenience, we have prepared a demo application that showcases this issue. You can download .mpk package for your investigation purposes. The download link is provided below:
https://drive.google.com/file/d/1GRacwaMmY216Ce0cFS8YkxS5JkIlPA61/view?usp=drive_link

**Comment by ConnorLand** [comment]
Hello @MirageG23 ,

Thank you for this detailed explanation of this Data Grid 2 issue. Documentation feedback on GitHub is primarily used for documentation fixes. This product problem would be best handled by our Support department.

Could you please file a [Support Ticket](https://docs.mendix.com/developerportal/support/submit-support-request/) using the existing text you've already written here? I'm sure they'll appreciate the explanation and .mpk. Once they handle the product issue, they'll let me know if I should update the documentation accordingly.

Thank you for improving Mendix with us,

Connor
