### ISSUE TITLE
extending-your-application-with-custom-java

### ISSUE THREAD

**Issue by tswarmerdam-mx** [mendix/docs#6408]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [extending-your-application-with-custom-java](https://docs.mendix.com/refguide/extending-your-application-with-custom-java/)

Document link: [extending-your-application-with-custom-java.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/java-programming/extending-your-application-with-custom-java.md)

## My Issue/Suggestion
FYI The link to the assetmanagement template does not work anymore.
It is the last hyperlink under "2. Prerequisites".

Cheers!
Tom

**Comment by MarkvanMents** [comment]
Thanks for the report Tom (@tswarmerdam-mx )

@Yiyun333 
Can you see if you can find where the asset management template has moved to. Let me know if you need help.
Thanks.
Markj

**Comment by Yiyun333** [comment]
@tswarmerdam-mx 

Thanks for reporting this. I just fixed the link to the template in the docs: https://github.com/mendix/docs/pull/6415.
The fix will be online soon.

Best,
Yiyun
