### ISSUE TITLE
javascript-and-typescript-resources

### ISSUE THREAD

**Issue by winfried-van-loon-goudse** [mendix/docs#6421]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [javascript-and-typescript-resources](https://docs.mendix.com/apidocs-mxsdk/mxsdk/javascript-typescript-resources/)

Document link: [javascript-typescript-resources.md](https://github.com/mendix/docs/blob/development/content/en/docs/apidocs-mxsdk/mxsdk/sdk-refguide/javascript-typescript-resources.md)

## My Issue/Suggestion
Hello, at heading 4 the youtube video is not available, because it's private. 

![image](https://github.com/mendix/docs/assets/93204188/44017371-a814-4d8c-a1ff-81c69b37800e)

**Comment by Adam-Dupaski** [comment]
Thanks @winfried-van-loon-goudse - I removed the video, which was implemented before 2017.
