### ISSUE TITLE
data-grid-2 doc still refers to Data Hub

### ISSUE THREAD

**Issue by sjoerdbreur** [mendix/docs#6451]
In section 3.1 on this page, the Data Hub terminology is still used; this probably got overlooked during the rebranding efforts. 

> The Paging Buttons option will render the default buttons as the previous data grid. When the data source is uncountable _(like entities in Data Hub)_ neither the last page button nor the counting will be be available. The paging can be positioned above or below the grid:

I imagine what is actually being referred to here is External Entities, so probably updated accordingly?

**Comment by sjoerdbreur** [comment]
Also to add to that, in section 4.8:

> This property not available if you enable “Custom content” for the column

Is missing an 'is' IMO.

**Comment by Adam-Dupaski** [comment]
Thanks @sjoerdbreur fixed in this commit: https://github.com/mendix/docs/commit/799ddafb685d020659b6f65b507eb16479f26cde
