### ISSUE TITLE
lts-mts-and-monthly-releases

### ISSUE THREAD

**Issue by tswarmerdam-mx** [mendix/docs#6454]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [lts-mts-and-monthly-releases](https://docs.mendix.com/releasenotes/studio-pro/lts-mts/)

Document link: [lts-mts.md](https://github.com/mendix/docs/blob/development/content/en/docs/releasenotes/studio-pro/lts-mts.md)

## My Issue/Suggestion

There's a small "spelling mistake" in paragraph 1.2, the 18 should be **24** obviously.

_In the 9.24.1 example, the second number (**18**) indicates the minor version._

**Comment by Adam-Dupaski** [comment]
Thanks @tswarmerdam-mx fixed here: [6454](https://github.com/mendix/docs/commit/dc0c2b1e0d7ce0bcb14e153601542fc0eb7a8625)
