### ISSUE TITLE
app-roles

### ISSUE THREAD

**Issue by dlhartveld** [mendix/docs#6493]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [app-roles](https://docs.mendix.com/developerportal/general/app-roles/)

Document link: [app-roles.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/general/team/app-roles.md)

## My Issue/Suggestion

Section (2) Team Member mentions that the Technical Contact of the app can send invites to team members. This is incorrect. Any team member that has the invite permission can send invites. A team member without invite permission can be technical contact, and this team member cannot send invites.

**Comment by Luyao-Zhang-1** [comment]
Thank you for raising this issue to us. I updated the doc in the PR above.
Please do not hesitate to reach out to us again if you see any issues with documentation in the future.
