### ISSUE TITLE
differences-between-git-and-svn

### ISSUE THREAD

**Issue by jpulleman** [mendix/docs#6504]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [differences-between-git-and-svn](https://docs.mendix.com/refguide9/svn-git-differences/)

Document link: [svn-git-differences.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide9/version-control/svn-git-differences.md)

## My Issue/Suggestion
In the second sentence of [chapter 4](https://docs.mendix.com/refguide9/svn-git-differences/#proxy-support) I believe there is a typo: `remove` should be `remote` instead.

> However, it is not performant enough when it comes to communication with **remove** Git servers.

**Comment by MarkvanMents** [comment]
You are right, Jaap.
Corrected in this commit: https://github.com/mendix/docs/commit/0ed891d830e9eb7e4251eeb8ec8c13f746e68155
Thanks for letting us know.
