### ISSUE TITLE
database-replication

### ISSUE THREAD

**Issue by minisoft-rm** [mendix/docs#6517]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [database-replication](https://docs.mendix.com/appstore/modules/database-replication/)

Document link: [database-replication.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/database-replication.md)

Dear Mendix developers, this is a very powerful component. could you share more user manual or step by step ... so that we know how to use it.
by now, I can guess. I can copy data from db1 to db2. but...how to sync assoiation.....like primary table links many secondary items..... please teach us , thanks~~~

**Comment by MarkvanMents** [comment]
Hi @minisoft-rm 
Thanks for your suggestion. I have asked the developers to come up with a simple step-by-step to explain the concepts and some of the areas you mention. They have added this to their backlog, but I cannot currently give you a date on which it will be done as they are also working on other improvements.

I will close this issue, but will add a note to inform you when the additional information is added to the documentation.

Thanks for raising this issue, it is always useful to get feedback on how we can improve the documentation.

Yours
Mark
