### ISSUE TITLE
installing-mendix-studio-pro

### ISSUE THREAD

**Issue by Jorick-K** [mendix/docs#6525]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [installing-mendix-studio-pro](https://docs.mendix.com/refguide9/install/)

Document link: [install.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide9/general/install.md)

## My Issue/Suggestion

Please indicate where and how I can turn off the option to sign in via the web browser.
Before Mx 9.24.4 that was possible, now I can't find that option in the preference menu.
This is very impractical for when I have to use different account for different customers.

**Comment by MarkvanMents** [comment]
Hi @Jorick-K 
Thank you for your inquiry.
I have spoken to the developers and this feature is not available in Mendix 9.24.4 or above. There are no current plans to add this feature, but the developers are discussing your use case and how Mendix Studio Pro might support it in the future.

I'm sorry that this is affecting your workflow and that there is no current workaround, other than signing out once Studio Pro has started. I suggest that you raise your use case in the [Mendix Forum](https://forum.mendix.com/p/ideas) as an idea to see if it gets traction with the community. Popular ideas are often taken up and implemented.
