### ISSUE TITLE
monitoring-mendix-runtime

### ISSUE THREAD

**Issue by Maismaus** [mendix/docs#6550]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [monitoring-mendix-runtime](https://docs.mendix.com/refguide/monitoring-mendix-runtime/)

Document link: [monitoring-mendix-runtime.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/runtime/monitoring-mendix-runtime.md)

## My Issue/Suggestion
I believe this is false:
The request needs to be of the POST type with No Authorization and the following headers:

I needed to use basic auth with MxAdmin and M2EE password on top of the X-M2EE-Authentication header

**Comment by MarkvanMents** [comment]
Hi Marius (@Maismaus)
Thank you for raising this issue.
I have spoken to the developers about this and they tell me that basic auth isn't necessary. Their tests use the setup as described in the documentation and they finish successfully.
Unfortunately, they have not come across the problem you are having and so could not suggest anything which might resolve the issue.
If you continue to have this problem, you could try posting your issue on the [Mendix Forum](https://forum.mendix.com/p/questions) and see if any of our community have had this. You could also raise a ticket with [Mendix Support](https://support.mendix.com/).

I'm sorry that we can't resolve your issue and that the documentation appears to reflect how the developers see this working.
Yours
Mark

**Comment by Maismaus** [comment]
Hi @MarkvanMents ,
Thanks for the response! There's no need to dive into this in my opinion, it works for me with sending the basic Auth at least, so I'm not blocked by this. It probably has something to do with my current project using the docker buildpack instead of being hosted on the Mendix cloud.
