### ISSUE TITLE
maps

### ISSUE THREAD

**Issue by MichaFriede** [mendix/docs#6562]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [maps](https://docs.mendix.com/appstore/widgets/maps/)

Document link: [maps.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/widgets/maps.md)

## My Issue

When you want to set up your map using Lat/Long, you have to make sure that you do not enter text, but only use a reference to an attribute of the object (see 3). Otherwise no marker will be shown 

![ksnip_20230925-140425](https://github.com/mendix/docs/assets/19909793/4a279294-90e6-4d8f-a56a-197e8b19d632)

**Comment by ConnorLand** [comment]
Hello @MichaFriede ,

While you cannot use addresses in the lat/long configuration, you should indeed be able to use them with numbers so long as a decimal place is included.

For the best troubleshooting environment, I recommend you post your query and screenshots on the Mendix Forum. There other users and even MVPs can help you troubleshoot:

https://forum.mendix.com/p/questions

If after using the Mendix Forum you determine this document is in error, please open another Feedback item or Pull Request and the document will be amended.

Best,

Connor
