### ISSUE TITLE
Please use a more professional translater for Chinese language

### ISSUE THREAD

**Issue by zjh1943** [mendix/docs#6564]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [contribute-to-the-documentation](https://docs.mendix.com/developerportal/community-tools/contribute-to-the-mendix-documentation/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/community-tools/contribute-to-the-mendix-documentation/_index.md)

## My Issue/Suggestion

The translated document from English to Chinese is bad. Many keywords in the programming world are translated to meaning in the real world. e.g. String -> [细绳], SAP -> [树液]. It makes the MX developers hard to read and understand. And it leaves the impression of us unprofessional.

Based on the result of the translation now, I assume that you have not proofread the translation result, but just copied the result of the machine translation. Since it is directly from translation tools, could you use a smarter translation tool like ChatGPT or DeepL?
Not much effort, but makes the experience better!

**Comment by Luyao-Zhang-1** [comment]
Thanks for reporting this issue. Could you tell us on which page you found this issue?

**Comment by Luyao-Zhang-1** [comment]
@zjh1943 Thank you for your feedback. I updated our glossary. The translations of "SAP" and "string" should now be correct on the Mendix Docs site. Please reach out to us anytime if you spot any wrong translations of technical terms on the Mendix Docs site. Thank you again for helping us improve our docs.
