### ISSUE TITLE
restore-a-backup-locally

### ISSUE THREAD

**Issue by SimplyTheBrent** [mendix/docs#6566]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [restore-a-backup-locally](https://docs.mendix.com/developerportal/operate/restore-backup-locally/)

Document link: [restore-backup-locally.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/operate/backups/restore-backup-locally.md)

## My Issue/Suggestion

In the section [Restoring Files](https://docs.mendix.com/developerportal/operate/restore-backup-locally/#5-restoring-files) the wording for the following sentence could be:

Current:

```
Extract the entire tree folder from the backup archive to the deployment/data/files folder within your app.
```

Better described:

```
Extract the entire tree folder **contents** from the backup archive to the deployment/data/files folder within your app.
```

In this way it will be more clear whether to move the entire folder or the entire folder's content in.

**Comment by ConnorLand** [comment]
Hello @SimplyTheBrent ,

Thank you for this clarification, I have implemented it here: https://github.com/mendix/docs/commit/b08cc9954a69a8e3726d34acb4739d3b088fabe9

In the future, should you have other language changes, you can implement a [pull request](https://docs.mendix.com/developerportal/community-tools/contribute-to-the-mendix-documentation/) towards our repo.

Best,

Connor
