### ISSUE TITLE
xpath-not

### ISSUE THREAD

**Issue by joepveenman** [mendix/docs#6575]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [xpath-not](https://docs.mendix.com/refguide/xpath-not/)

Document link: [xpath-not.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-constraint-functions/xpath-not.md)

## My Issue/Suggestion

In the mendix course "4.2-The-Not-Function" they state that the not() function slow due to the SQL query that is generated.
I would be nice if this is also mentioned here in the office documentation.
It would be even better if there is also mentioned why it is slow. What kind of SQL is generated and why is that slow. 
I would consider this very impotent information and I hope you guys see it the same way.

**Comment by MarkvanMents** [comment]
Hi Joep,
Thank you for raising this issue. I'm sorry about the delay in getting back to you.
Discussing this with the developers, they are surprised that this is in the Academy course as it is very difficult to identify whether a specific query has performance problems. Their view is that you should not try to predict which queries might have issues, but create the simplest query which gives the answers you want and then test the performance to ensure it matches your expectations. Only if you see a specific query as a bottleneck is it worth spending time trying to identify a workaround.
I have asked the people who maintain the Academy course to look into this recommendation and see whether it should be changed.
Hope this helps.
Yours
Mark
