### ISSUE TITLE
part-1-add-module-dependencies

### ISSUE THREAD

**Issue by Roukema** [mendix/docs#6636]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [part-1-add-module-dependencies](https://docs.mendix.com/refguide/mobile/using-mobile-capabilities/push-notifications/notif-add-module-depends/)

Document link: [notif-add-module-depends.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-add-module-depends.md)

## My Issue/Suggestion

It might be a good idea to note somewhere that the correct app roles are set for the modules. Otherwise, you will run into bugs later in the process that are not immediately clear.

**Comment by ConnorLand** [comment]
Hello @Roukema ,

Do you mean adding some text like "these modules have the correct app roles set up for them from the start"? Did you encounter bugs because you changed the pre-set module roles?

Connor

**Comment by Roukema** [comment]
Hello Conner, 

I should change the 5th point of the next section: 

```
5 Implementing the Native Mobile Resources Module
Skip this section if the [Native Mobile Resources](https://marketplace.mendix.com/link/component/109513/Mendix/Native-Mobile-Resources) module is already implemented in your app, or if you do not plan on using using local or native push notifications. Implement this module by doing the following:


1. Open up the Marketplace from Studio Pro.
2. Search for Native mobile resources.
3. Open the [Native mobile resources](https://marketplace.mendix.com/link/component/109513/Mendix/Native-Mobile-Resources) module.
4. Click Download.
5. No further installation is required. If you want to know more about the module visit the [Native mobile resources marketplace guide](https://docs.mendix.com/appstore/modules/native-mobile-resources/).
```

My suggestion is to add the next sentence: 'The User role is for any user role that needs to interact with notifications' 


Not adding the module-role User to the users that interact with notifications will give you the next error: 
```
An error occurred while executing an action of MoCcaNative.NativeHomepage_Snippet.appEvents1: Could not create 'NativeMobileResources.DeviceInfo' object to store device info

Nanoflow stack:
 "Call JavaScript Action" in nanoflow "PushNotifications.OnPageLoad_RegisterPushNotifications"
```

**Comment by ConnorLand** [comment]
Hi @Roukema ,

I've had a chat with the developers. Our current configuration, where we tell people to download and implement the modules as is, syncs well with the fact that the user roles are correctly configured from the outset. 

We feel that leaving the instructions as is presents the clearest set of instructions for users.

If you follow the documents as written and run into technical malfunctions, please file a [Support ](https://support.mendix.com/hc/en-us/requests/new)ticket.

Thank you for your suggestion,

Connor
