### ISSUE TITLE
registry-configuration

### ISSUE THREAD

**Issue by mxcrawford** [mendix/docs#6641]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [registry-configuration](https://docs.mendix.com/developerportal/deploy/private-cloud-registry/)

Document link: [private-cloud-registry.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/private-cloud-registry.md)

## My Issue/Suggestion

In the code block section I believe the ecr:List permission should be ecr:ListImages

```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowImageBuilds",
            "Effect": "Allow",
            "Action": [
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability",
                "ecr:CompleteLayerUpload",
                "ecr:GetDownloadUrlForLayer",
                "ecr:InitiateLayerUpload",
                "ecr:PutImage",
                "ecr:List",
                "ecr:UploadLayerPart",
                "ecr:DescribeRepositories",
                "ecr:CreateRepository"
            ],
            "Resource": "arn:aws:ecr:<aws_region>:<account_id>:repository/<repository>"
        },
        {
            "Sid": "AllowAuthentication",
            "Effect": "Allow",
            "Action": "ecr:GetAuthorizationToken",
            "Resource": "*"
        }
    ]
}
```

**Comment by katarzyna-koltun-mx** [comment]
@mxcrawford Thank you for reporting the issue. I'll verify it with the dev team and update the document if required.

**Comment by katarzyna-koltun-mx** [comment]
I've verified the issue with the dev team and created PR https://github.com/mendix/docs/pull/6646 to update the document. The update should be published today. Thank you for pointing out the issue and let us know if there's anything else!
