### ISSUE TITLE
video-player

### ISSUE THREAD

**Issue by zjh1943** [mendix/docs#6643]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [video-player](https://docs.mendix.com/appstore/widgets/video-player/)

Document link: [video-player.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/widgets/video-player.md)

## My Issue/Suggestion
The document only says that it does not recommend that we pass the URL of a System.FileDocument to the video player.

But the main question is, what is the recommended way to store and play videos with Mendix? There are no YouTube-like things for the client because the application is deployed in the local network, with no internet access.

**Comment by ConnorLand** [comment]
Hi @zjh1943 ,

I've reached out to our cloud developers to try and help with your issue. They asked for a little clarification: 

"Is the customer's application running on their local network or in the Mendix Public Cloud?"

Could you speak to these details, and anything else regarding your use case that we should know about?

Regards,

Connor

**Comment by zjh1943** [comment]
Hi @ConnorLand,

The application is running in their local network. The video file is saved into an Entity that inherits the system.FileDocument Entity.
The client wants to know:
1. What URL should be passed to the video player (as the document does not recommend that we pass the URL of a System.FileDocument to the video player)? 
2. How to get the URL? (Is there any low-code way to get the URL?)
3. What is the recommended way to store and play videos with Mendix? Any best practice?

From my side, as an expert service team member, I think the document should not only introduce the basic attributes of a widget, but it should contain content about how to use it, what is the recommended way to use it, etc.

**Comment by ConnorLand** [comment]
Hi @zjh1943 ,

I've spoken to one of our widget developers. Mendix currently lacks an out-of-the-box media server solution, and this question is a little specialized relating to the on-environment media server. Therefore please file a [ticket with Support](https://support.mendix.com/hc/en-us) for a bespoke solution that addresses your situation.

Thank you for reaching out,

Connor
