### ISSUE TITLE
decisions

### ISSUE THREAD

**Issue by Marnix-IxD** [mendix/docs#6644]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [decisions](https://docs.mendix.com/refguide/decisions/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/decisions/_index.md)

## My Issue/Suggestion

Add links to expression editor / language, how to make expressions and how to use variables etc.

**Comment by Yiyun333** [comment]
Hi @Marnix-IxD,

Thanks for your feedback. 

As requested, I've added links and some extra instructions on the [Decisions](https://docs.mendix.com/refguide/decisions/) page. Please see the changes in this PR: https://github.com/mendix/docs/pull/6655/files. The PR will be merged and published soon.

Please let me know if you have any further feedback. Thank you!

Best,
Yiyun

**Comment by Yiyun333** [comment]
I've merged the PR :) I will close this issue for now. Please let me know if you have any further feedback. Thanks!
