### ISSUE TITLE
error-handling-in-microflows

### ISSUE THREAD

**Issue by MartijnJansenLinkit** [mendix/docs#6666]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [error-handling-in-microflows](https://docs.mendix.com/refguide/error-handling-in-microflows/)

Document link: [error-handling-in-microflows.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/error-handling-in-microflows.md)

## My Issue/Suggestion

This part is not true:
"(if you used error handling with rollback, this information would not be available)."
You can still access the information also when the rollback is triggered:

**Comment by Yiyun333** [comment]
Hi @MartijnJansenLinkit,

Thank you for your feedback!

The correct behavior should be that when **Custom with rollback** is triggered by an error, everything happened before the error is reverted/rolled back. Hence, the information on the **New order** (created and committed before the error) is also reverted and shouldn't be available anymore. Hence you also cannot create a custom log message after the error about this already non-existent new order information. I don't see anything wrong with the sentence quoted above, but I can make it a bit more informative to avoid any confusion. The [Error Handling - Custom with Rollback](https://docs.mendix.com/refguide/error-handling-in-microflows/#22-error-handling---custom-with-rollback) section has more information on the whole process. 

I hope that I've understood your feedback correctly. Do you have a specific case where you can show that the information created and committed before the error is still available after **Custom with rollback** is triggered by the error?

Best,
Yiyun

**Comment by Yiyun333** [comment]
Hi @MartijnJansenLinkit,

I've created a [pull request](https://github.com/mendix/docs/pull/6811/files) in which I have made the sentence a bit more informative. Please let me know whether this answers your question. I will keep this issue open for another week. If I haven't received a reply then, I will merge the PR and close this issue. Thanks in advance!

Best regards,
Yiyun

**Comment by Yiyun333** [comment]
Hi @MartijnJansenLinkit,

I've merged the PR and closed this issue for now. Please let me know if you have any further feedback. Thank you!

Best regards,
Yiyun
