### ISSUE TITLE
widget-styling-guide

### ISSUE THREAD

**Issue by thomasvlok** [mendix/docs#6678]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [widget-styling-guide](https://docs.mendix.com/refguide/mobile/designing-mobile-user-interfaces/widget-styling-guide/)

Document link: [native-styling-element-guide.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/mobile/designing-mobile-user-interfaces/native-styling-element-guide.md)

## My Issue/Suggestion

Element name is wrong for Badge widget with custom styling.

I tried to apply custom styling on the text element of a Badge widget. This did not work until I changed the 'text' element to 'caption' then my styling worked. Should the documentation not state there is a caption element on Badge instead of text?

**Comment by ConnorLand** [comment]
Hello @thomasvlok ,

Thank you for letting us know about this code issue. We have fixed the issue here: https://github.com/mendix/docs/pull/6692

Thank you for contributing to the documentation,

Connor
