### ISSUE TITLE
build-a-responsive-web-app

### ISSUE THREAD

**Issue by iaindooley** [mendix/docs#6695]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [build-a-responsive-web-app](https://docs.mendix.com/quickstarts/part1/)

Document link: [part1.md](https://github.com/mendix/docs/blob/development/content/en/docs/quickstarts/part1.md)

## My Issue/Suggestion

The instructions say "Delete all the display widgets inside the grid." however before I was able to delete display widgets I had to switch to "Structure mode", whereas the default appears to have been "Design mode".

**Comment by ConnorLand** [comment]
Hi @iaindooley ,

I've added a reminder in the doc to switch out of design mode. Thank you for bringing this to my attention.

Best,
Connor
