### ISSUE TITLE
build-a-responsive-web-app

### ISSUE THREAD

**Issue by iaindooley** [mendix/docs#6696]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [build-a-responsive-web-app](https://docs.mendix.com/quickstarts/part1/)

Document link: [part1.md](https://github.com/mendix/docs/blob/development/content/en/docs/quickstarts/part1.md)

## My Issue/Suggestion

The instructions say "Add the additional path and make sure to select the False path as the one which goes down." but don't tell you how to do that. It turns out I had to click a little red dot at the top of the screen then drag to make a connection from the decision.

**Comment by ConnorLand** [comment]
Hello @iaindooley ,

Thank you for your feedback. We are adding more in-product tutorial tips to teach customers how the dots, arrows, and other elements work. For the short term, I've added a direction in the document telling users how to click the red dots to make connections.

Thank you for your feedback,

Connor
