### ISSUE TITLE
special-checks

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#6712]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [special-checks](https://docs.mendix.com/refguide9/special-checks/)

Document link: [special-checks.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide9/modeling/application-logic/expressions/special-checks.md)

## My Issue/Suggestion
In section 5 Checking Whether an Object Is Synced
The guide says "This function is available only in expressions for *conditional visibility or editability*, as only they are evaluated on client side."
However, I found that the function does work in a nanoflow called in native, which was very useful. If I hadn't tried it anyway, I wouldn't have known. So it would be worth correcting the guide.

**Comment by Yiyun333** [comment]
Hi @Chris-Karona,

Thanks for pointing this out! 
I'll check this and keep you posted here.

Best,
Yiyun

**Comment by Yiyun333** [comment]
@Chris-Karona 

I've verfied with the team and updated the documentation accordingly. 

Thanks a lot for your feedback!

Best,
Yiyun
