### ISSUE TITLE
download-from-version-control-server

### ISSUE THREAD

**Issue by freddsomm** [mendix/docs#6759]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [download-from-version-control-server](https://docs.mendix.com/refguide/download-from-version-control-dialog/)

Document link: [download-from-version-control-dialog.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/menus/version-control-menu/download-from-version-control-dialog.md)

## My Issue/Suggestion

There is no private server on "Download from Version Control Server" on Mendix 10.4

**Comment by MarkvanMents** [comment]
Hi Fred.
I cannot reproduce the issue you mention. I can see the "Private Server" option in Mendix 10.4.
![image](https://github.com/mendix/docs/assets/35492184/f0c79101-a215-4684-9013-e3f35a492d66)
I hope I have understood your issue, but please reopen this if I have misunderstood.
These issues are meant for feedback on the Mendix documentation. If you think this is a bug or missing feature, please reach out to [Mendix Support]([url](https://support.mendix.com/hc/en-us)).
Yours
Mark
