### ISSUE TITLE
share-data-between-apps

### ISSUE THREAD

**Issue by JohannesEichermueller** [mendix/docs#6783]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [share-data-between-apps](https://docs.mendix.com/catalog/share-data/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/catalog/integrate/share-data/_index.md)

## My Issue/Suggestion
There is no description about the authorization. Username/pw. Where can i configure it?

**Comment by MarkvanMents** [comment]
Hi Johannes,
Thanks for your question,
This document shows how to publish data as a Published OData Service. If you look at the documentation for the Published OData Service, you will see that there is a [section on security](https://docs.mendix.com/refguide/published-odata-services/#security) which applies in this case.

I have added a link to this document in commit f08219c48932ed245b38f9fcc8924abde8e4f836 to make it easier to find this information.

Thank you for pointing out this improvement, it makes Mendix easier to use for everyone.
Yours
Mark

**Comment by JohannesEichermueller** [comment]
Thank you. I found my mistake. I always generate a webservice user. But in the section [allowed roles](https://docs.mendix.com/refguide/published-odata-services/#333-allowed-roles) is a hint, that a webservice user cannot access odata service. It's a bit confusing. ;)
