### ISSUE TITLE
style

### ISSUE THREAD

**Issue by 5cientist** [mendix/docs#6845]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [style](https://docs.mendix.com/refguide/style/)

Document link: [style.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/resources/document-templates/style.md)

## My Issue/Suggestion

add some example for 2.3 Custom Styles

**Comment by ConnorLand** [comment]
Hi @5cientist ,

Thank you for your feedback. We have some major plans for this template in the long-term. I have noted your feedback and we will fold it in to the future work we do.

Thank you for contributing your ideas to the documentation,

Connor
