### ISSUE TITLE
use-a-client-certificate

### ISSUE THREAD

**Issue by tieniber** [mendix/docs#6848]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [use-a-client-certificate](https://docs.mendix.com/howto/integration/use-a-client-certificate/)

Document link: [use-a-client-certificate.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/integration/use-a-client-certificate.md)

## My Issue/Suggestion
We should reference the term 'mTLS' here so that it's searchable. For some use cases, just using a client cert covers the needs described as mTLS. In others, there's also a need for server-side certificate pinning, which requires custom code.

**Comment by quinntracy** [comment]
@tieniber Do you want additional content in the article regarding mTLS, or do you just want the article to be searchable using the term mTLS? We can add it into the article tags, or if someone is able to draft a small section to explain/reference mTLS, we can update the article that way too. What are your thoughts?

**Comment by quinntracy** [comment]
@tieniber Per our conversation, I've added the requested information in an alert box, which can be seen in [this PR](https://github.com/mendix/docs/pull/7624).
