### ISSUE TITLE
build-odata-apis-with-rest-best-practices

### ISSUE THREAD

**Issue by RCatersels** [mendix/docs#6851]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [build-odata-apis-with-rest-best-practices](https://docs.mendix.com/refguide/build-odata-apis/)

Document link: [build-odata-apis.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/integration/odata-services/build-odata-apis.md)

## My Issue/Suggestion
The problem is this part:
_The microflow uses a Java action to translate the OData query to an OQL expression using the OQL Dataset as the base query. This ensures that filtering, sorting, and paging work as expected._
Because where do I find this Java action? I have downloaded the OQL module as I was expecting it there. There is an Execute OQL Statement there but it differs from the example because I have the Amount and Offset and Preserve paramaters options in that action. So state where this Java action can be found and if it is the one in the OQL module then you should update the screenshots.

Regards,
Ronald

**Comment by quinntracy** [comment]
@RCatersels  Thank you for flagging this. Additional information has been added in [this PR](https://github.com/mendix/docs/pull/7625) to clarify the issue.
