### ISSUE TITLE
build-pluggable-web-widgets

### ISSUE THREAD

**Issue by 3loader** [mendix/docs#6871]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [build-pluggable-web-widgets](https://docs.mendix.com/howto/extensibility/pluggable-widgets/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/extensibility/pluggable-widgets/_index.md)

## My Issue/Suggestion

The example provided in the document is outdated. It is uses Class-based compilation. It should be Function-based, because all the widgets made by Mendix (/mendix and /mendix-labs repositories) nowadays are Function-based. New people, who are not very familiar with react cannot use Mendix widgets as examples properly because of that

**Comment by ConnorLand** [comment]
Hi @3loader ,

We have updated the [Mx10](https://github.com/mendix/docs/pull/7686) and [Mx9](https://github.com/mendix/docs/pull/8223/) versions of these docs. Now, their code snippets and instructions are clearer and use consistent compilation models.

Thank you for your feedback,

Connor
