### ISSUE TITLE
app-settings URL Prefix in Mx 10.5

### ISSUE THREAD

**Issue by MohamedElNady** [mendix/docs#6884]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [app-settings](https://docs.mendix.com/refguide/app-settings/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md)

## My Issue/Suggestion
I was trying the new features in [Mendix 10.5](https://marketplace.mendix.com/link/studiopro/), especially "We added the option to change the default URL prefix `/p/` for page and microflow URLs." and I found out I get an error from the page when I change the prefix to "pages"
https://forum.mendix.com/link/space/studio-pro/questions/130121

**Comment by ConnorLand** [comment]
Hi @MohamedElNady ,

I'll discuss with the devs about making the list of forbidden prefixes complete. Thank you for bringing this up.

Connor
