### ISSUE TITLE
pdf-document-generation

### ISSUE THREAD

**Issue by ArthurvdMolen** [mendix/docs#6937]
I get error " Timeout while waiting for document content; no content was received"

But no explaination how to fix

Page link: [pdf-document-generation](https://docs.mendix.com/appstore/modules/document-generation/)

Document link: [document-generation.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/document-generation.md)

## My Issue/Suggestion

Add help to fix problem

**Comment by Luyao-Zhang-1** [comment]
@ArthurvdMolen Thank you for the feedback. I will discuss with the team and come back to you.

**Comment by Luyao-Zhang-1** [comment]
Hi @ArthurvdMolen Could you create a support ticket for your issue? 
It would be great if you could also add a bit more context to the ticket and a (test) project for our colleagues to be able to understand what the issue could be. 
Thank you!
