### ISSUE TITLE
epics-api

### ISSUE THREAD

**Issue by rvpuijenbroek** [mendix/docs#6955]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [epics-api](https://docs.mendix.com/apidocs-mxsdk/apidocs/epics-api/)

Document link: [epics-api.md](https://github.com/mendix/docs/blob/development/content/en/docs/apidocs-mxsdk/apidocs/epics-api.md)

## My Issue/Suggestion
From the documentation it is not clear how epics and stories are linked (and they are linked in the Mendix portal). It is also not clear if and to what extent the 'old' stories API is still operational and if we can still use it. Given that the stories API provided a much more detailed way of interacting with individidual user stories it would definitely be a plus if the same functionality was made available in the Epics API (before removing the stories API).

It does not seem to be possible to manage epics at all, just get an overview of epics recorded in the Mendix portal. There is no data on epics with the user stories, although each user story is linked to an epic in the Mendix portal.

Suggestions for improvement:
1. Make it possible to retrieve individual epics. 
2. Make it possible to create/update epics
3. Add a reference to an epic in the user stories and allow to read and update the epic
4. Make it possible to get all stories related to an epic
5. Allow for images and objects to be accessible through the API as well (even if only by providing a URL)

**Comment by Luyao-Zhang-1** [comment]
@rvpuijenbroek Hey, thank you very much for the feedback. 
Regarding how epics and stories are linked – if you mean the project management tools Epics (the current tool) and Stories (the old tool), then you should [migrate data in Stories to Epics](https://docs.mendix.com/developerportal/project-management/epics/planning/#data-migration), and manage your project in Epics. If you mean the terms "epics" and "stories" which are used in the context of project management, then the stories are grouped under an epic, which can be seen in the project management tool.
The Stories API will be retired at certain point. I will let you know when I get more information about the plan.
I have shared your suggestions for improvement with the Project Manager. They will see what they can plan. Thank you again for sharing your valuable feedback on this.

**Comment by rvpuijenbroek** [comment]
@Luyao-Zhang-1 
Thank you for your reply. 
My concern has to do with the Epics-API not being functionally complete, not so much with the portal functionality. We are already using the Epics functionality in the portal. I am aware that we can group stories under an epic.... in the portal. 

However, we want to use the API to get, for example, all stories for an epic, or create/update a story and link it to an epic, or even create an epic through the API. At the moment, the Epics-API has no support for these basic functions (at least the documentation does not mention this). 

If I look at the documentation for the Epics API, then at the moment:
* We can only get all Epics for a project through the API, but not create or update one (or retrieve even a singular epic)
* We can only get all stories for a project, but not all stories for an epic (or retrieve even a singular user story)
* We cannot link a story to an epic when creating/updating a story

Before retiring the old stories-API.

**Comment by Luyao-Zhang-1** [comment]
@rvpuijenbroek Thanks you for your reply. I forwarded your suggestions to the development team! I cannot promise when they can implement these endpoints, but once these end points are added, you will find them in the documentation. I will close this issue, because as the Docs team we cannot do much at this point for this. 
Thank you again. Please feel free to reach out to us if you see anything on the Docs site that needs to be improved.

Have a good weekend!
