### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by Fjordi12** [mendix/docs#6986]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [authentication] (https://docs.mendix.com/apidocs-mxsdk/apidocs/authentication/)

Document link: [authentication.md] (https://github.com/mendix/docs/blob/development/content/en/docs/apidocs-mxsdk/apidocs/authentication.md)

## My Issue/Suggestion

Please include the steps or a screenshot how to implement a certain functionality (how to call API keys for authentication in this case)

**Comment by Luyao-Zhang-1** [comment]
@Fjordi12 Hi, thank you for your feedback! I added a reference to an example in this doc. Hope this helps. Thanks again! If you have more questions, please don't hesitate to reach out to us.
