### ISSUE TITLE
mendix-best-practices-for-development

### ISSUE THREAD

**Issue by ricoroodenburg** [mendix/docs#7025]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [mendix-best-practices-for-development](https://docs.mendix.com/refguide/dev-best-practices/)

Document link: [dev-best-practices.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/dev-best-practices.md)

## My Issue/Suggestion

In 3.4. add some naming patterns too for flows which are triggered by other flows. You can call a microflow from a nanoflow and vice versa. For example
NF_{Purpose}
MF_{Purpose}

Just an idea.

**Comment by Yiyun333** [comment]
Hi @ricoroodenburg,

Thank you for your feedback! I will look into this and investigate what's the best way to approach your feedback. I will get back to you when I have an answer.

Kind regards,
Yiyun

**Comment by Yiyun333** [comment]
Hi @ricoroodenburg,

I've consulted your feedback with our Academy team and checked with them how we normally teach those microflow naming conventions in classroom trainings. 

One of the feedback I've received is that it's actually not clear whether using the **NF_/MF_** prefixes is more useful than the **SUB_** prefix (which we do teach in classroom trainings and also have it documented).

Moreover, nanoflows have not been taught much in our trainings yet. Hence, we need more user feedback on this suggestion still. [Mendix Forum](https://community.mendix.com/p/community) is a more suitable place to post this idea, and if you'd like, please post the idea there. If many developers do vote for this idea, please let us know again and we will update our documentation accordingly. 

I will close this issue for now. Thanks again for your time and patience!

Best regards,
Yiyun
