### ISSUE TITLE
create-custom-error-pages

### ISSUE THREAD

**Issue by 5cientist** [mendix/docs#7037]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [create-custom-error-pages](https://docs.mendix.com/howto/front-end/custom-error-page/)

Document link: [custom-error-page.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/front-end/custom-error-page.md)

## My Issue/Suggestion

What about the native error page? It is not mentioned here.

**Comment by ConnorLand** [comment]
Hi @5cientist ,

I'll look into the differences in creating custom error pages for native apps and reply back to you.

Thank you for your question,

Connor

**Comment by ConnorLand** [comment]
Hi,

I might be the second person to tell you this after Support, but native mobile doesn't really have error pages as users cannot enter URLs that can lead to them.

Error messages can be customized by changing the [system text](https://docs.mendix.com/refguide/system-texts/). 

I [have made this information clearer](https://github.com/mendix/docs/commit/e237b1d73ecf806991d5a85527e5a2bb87de4cbd) in the Custom Error Pages document to prevent further confusion.

Thank you for reaching out to Mendix documentation,

Connor
