### ISSUE TITLE
installing-mendix-studio-pro

### ISSUE THREAD

**Issue by JJFourie** [mendix/docs#7097]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [installing-mendix-studio-pro](https://docs.mendix.com/refguide/install/)

Document link: [install.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/installation/install.md)

## My Issue/Suggestion

At the time of writing it is **only possible to download StudioPro as an executable** (.exe). Unfortunately, and I guess that may be a problem for many other companies, our security rules prohibit us from downloading .exe files, copying to/from USB devices are blocked, etc. Which means something this simple becomes a showstopper for us to use Mendix.

What is strange though is that other of your downloads (such as server distributions) are packaged as e.g. zip files, so you could consider to standardize and make all your downloads available packaged in the same way.

**Comment by MariaShaposhnikova** [comment]
Hi @JJFourie , 
Thanks a lot for your feedback! 
I double-checked with the engineering team and there is no other format than an exe file at the moment. I am afraid this is as far as I can help within the documentation, but perhaps you could post your issue/suggestion on the [Mendix Forum](https://forum.mendixcloud.com)? For example, if the idea gets upvoted, it might get picked up. 


Best regards,
Maria
