### ISSUE TITLE
import-a-large-excel-file

### ISSUE THREAD

**Issue by riyabasak171** [mendix/docs#7120]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [import-a-large-excel-file](https://docs.mendix.com/howto/integration/import-a-large-excel-file/)

Document link: [import-a-large-excel-file.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/integration/importing-excel-documents/import-a-large-excel-file.md)

## My Issue/Suggestion
They also need to show after importing the file how the data's are reflecting in the home page.

**Comment by quinntracy** [comment]
@riyabasak171 Thank you for this feedback. Your suggestion has been implemented, as seen in this [PR](https://github.com/mendix/docs/pull/7165).
