### ISSUE TITLE
oql page mendix documentation

### ISSUE THREAD

**Issue by LianeBizzo** [mendix/docs#7149]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [oql](https://docs.mendix.com/refguide/oql/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/resources/data-sets/oql/_index.md)

## My Issue/Suggestion
The link to the OQL playground shows an offline app

**Comment by MarkvanMents** [comment]
Hi @LianeBizzo 
Thank you for getting in touch with us.
I have just tried the link in the document and it looks like it is working for me. The app might have been down for maintenance, or some other reason, when you tried it before.
If you still have an issue, please check your firewall settings to make sure it isn't blocked.
I hope you can now get to the OQL playground, but please let us know if you see anything else on our website which might need attention.
Yours
Mark van Ments
![image](https://github.com/mendix/docs/assets/35492184/0e59fdc0-72a9-459d-85f4-0968af8cd631)

**Comment by LianeBizzo** [comment]
Hi Mark,

Indeed it works again!

Regards,
Liane
