### ISSUE TITLE
template-grid

### ISSUE THREAD

**Issue by axelenexis** [mendix/docs#7205]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [template-grid](https://docs.mendix.com/refguide/template-grid/)

Document link: [template-grid.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/pages/data-widgets/grids/template-grid.md)

## My Issue/Suggestion
I have heard that Template grid is deprecated. Is that true? If so, then it may be good to mention this in the documentation.

**Comment by ConnorLand** [comment]
Hi @axelenexis ,

The Template grid core widget is not deprecated. You can continue to use it. However, we recommend the [Gallery](https://docs.mendix.com/appstore/modules/gallery/) pluggable widget for any use cases that can support it. The Gallery widget also receives more regular updates than Template.

Best,

Connor
