### ISSUE TITLE
 Inquiry Regarding Hosting in China Cloud

### ISSUE THREAD

**Issue by tyler1677** [mendix/docs#7217]
Dear  Mr./Ms.

I trust this message finds you well. I am writing to inquire about our company's hosting policies and explore the possibility of hosting applications or data in the cloud region located in China.

[
I would welcome the opportunity to discuss this matter further at your earliest convenience. 
Thank you for your time, and I look forward to your guidance on this matter.

Best regards,

Dr.Tyler EB

**Comment by MarkvanMents** [comment]
Dear Dr. Tyler EB,
Thanks for your inquiry. This site is for issues regarding technical Mendix documentation and so I cannot help you directly with your hosting queries. However, I can tell you the following:

Mendix Cloud is currently not offered in China. We do have a presence in China and offer customer on-premises deployment options, such as Mendix for Private Cloud and Server-based deployment. Our sales team in China can provide more information on these. Please reach out to them on our [main Mendix site](https://www.mendix.com/contact-us/#contactform) and schedule a call at your convenience.

Thank you for your interest in Mendix.
Yours
Mark van Ments
