### ISSUE TITLE
private-mendix-platform-prerequisites

### ISSUE THREAD

**Issue by mengdix** [mendix/docs#7244]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [private-mendix-platform-prerequisites](https://docs.mendix.com/private-mendix-platform-prerequisites/)

Document link: [pmp-prerequisites.md](https://github.com/mendix/docs/blob/development/content/en/docs/private-platform/pmp-prerequisites.md)

## My Issue/Suggestion

Update from: Application management | Mendix for Private Cloud Operator | 2.x+
Update to: Application management | Mendix for Private Cloud Operator | 2.12+

**Comment by katarzyna-koltun-mx** [comment]
@mengdix Done! Should be visible sometime tomorrow. Let me know if you need it earlier.
