### ISSUE TITLE
dynatrace-for-mendix-cloud

### ISSUE THREAD

**Issue by lucadesimoni** [mendix/docs#7251]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [dynatrace-for-mendix-cloud](https://docs.mendix.com/developerportal/operate/dynatrace-metrics/)

Document link: [dynatrace-metrics.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/operate/monitoring-with-apm/dynatrace-metrics.md)

## My Issue/Suggestion

Please update the description to consistently say "SaaS Token"

**Comment by dbreseman** [comment]
Hi @lucadesimoni, thanks for helping improve the docs! I corrected the capitalization and checked through our wording to ensure we're aligned with Dynatrace's terminology. These changes will be reflected on the site this evening.
