### ISSUE TITLE
app-roles

### ISSUE THREAD

**Issue by latoch8** [mendix/docs#7274]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [app-roles](https://docs.mendix.com/developerportal/general/app-roles/)

Document link: [app-roles.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/general/team/app-roles.md)

Perminission tab don't exist in enviroment tab. I am not able to change technical contact

**Comment by MarkvanMents** [comment]
Hi there,
Thanks for raising this issue.
I can see the permissions tab when I look at the environments page.
Please note that this is only for licensed apps running on the Mendix cloud. You also need to have the permissions to manage permissions.
If you have a licensed app running on the Mendix cloud, you have the right permissions, and you still can't see the Permissions tab, then please raise a [support ticket](https://support.mendix.com) or ask the question a [Community Question](https://community.mendix.com/p/questions) to get help from our extensive Mendix community.
From a documentation standpoint, I will see if we can make it more explicit that it only applies to licensed apps on the Mendix Cloud.

**Comment by Luyao-Zhang-1** [comment]
We [updated](https://github.com/mendix/docs/pull/7305) the docs to make it clear that you can only change the Technical Contact for licensed Mendix apps, and you cannot change the Technical Contact for Free Apps or apps running outside the Mendix Cloud.

Thank you for helping us improve the docs! If you have further questions regarding docs, please reach out to us again.
