### ISSUE TITLE
community-commons

### ISSUE THREAD

**Issue by kaspergff** [mendix/docs#7279]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [community-commons](https://docs.mendix.com/appstore/modules/community-commons-function-library/)

Document link: [community-commons-function-library.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/modules/community-commons-function-library.md)

## My Issue/Suggestion

The new java action "RandomStrongPasswordWithLowercase" is missing from the documentation.

**Comment by Karuna-Mendix** [comment]
HI @kaspergff, thank you for reporting this issue. I am looking into it.

**Comment by Karuna-Mendix** [comment]
Hi @kaspergff, the document is updated now and will be available soon. Thanks!
