### ISSUE TITLE
Change in Styling folder names

### ISSUE THREAD

**Issue by thierry-inno21-git** [mendix/docs#7280]
When you write "In theme/web/custom-variables.scss"  you mean Styling/web/custom-variables.scss   since there is no longer a Theme folder Am I right?

**Comment by ConnorLand** [comment]
Hi @thierry-inno21-git ,

This point is a bit confusing. The Studio Pro UI indeed leads you to believe that the folder with "web" and "native" in it is called Styling: https://docs.mendix.com/howto/front-end/customize-styling-new/#styling-editor


However if you check your local app's directories, the folder which encompasses both web and native is called "theme":

![folders](https://github.com/mendix/docs/assets/47385345/b05ad0c5-9c2a-4a8c-bbf9-2286f4ed5efd)
