### ISSUE TITLE
build-a-pluggable-web-widget-part-2-advanced missing "children" in export interface

### ISSUE THREAD

**Issue by laurenra7** [mendix/docs#7284]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [build-a-pluggable-web-widget-part-2-advanced](https://docs.mendix.com/howto/extensibility/create-a-pluggable-widget-two/)

Document link: [create-a-pluggable-widget-two.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md)

## My Issue/Suggestion
The code snippet for Alert.tsx won't compile. The error is:

`[!] (plugin typescript) Error: @rollup/plugin-typescript TS2339: Property 'children' does not exist on type 'AlertProps'.
src/components/Alert.tsx (10:79)

10 export const Alert: FunctionComponent<AlertProps> = ({ alertStyle, className, children }) => children ? (`

Whoever wrote the code snippet didn't test it to see that it works. It needs an additional property named children.

**Comment by ConnorLand** [comment]
Hello @laurenra7 ,

This snippet issue has been fixed here: https://github.com/mendix/docs/pull/7296

Thank you for bringing this to the attention of docs and improving Mendix documentation.

Connor
