### ISSUE TITLE
advanced-consumed-rest-services

### ISSUE THREAD

**Issue by rgrim** [mendix/docs#7339]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [advanced-consumed-rest-services](https://docs.mendix.com/refguide/integration/consume-a-rest-service/)

Document link: [consume-a-rest-service.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/integration/rest-services/consumed-rest-services/consume-a-rest-service.md)

## My Issue/Suggestion
Hello, simple feedback from a customer. He was following this tutorial and found out that this tutorial is not respecting the naming convention we have here : https://docs.mendix.com/refguide/dev-best-practices/#354-integration-documents

For the import Mapping, it should start with IMM_.
I know it's not much but my customer was confused. 

Best regards,
Romain Grimmonpré, 
Senior Business consultant, Mendix Expert Services EMEA

**Comment by quinntracy** [comment]
Hi Romain, thanks for flagging this . It has been raised with the team to ensure everyone knows to use proper naming conventions in all documentation. We will work to implement the changes accordingly.
