### ISSUE TITLE
using-version-control-in-studio-pro

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#7358]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [using-version-control-in-studio-pro](https://docs.mendix.com/refguide/using-version-control-in-studio-pro/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md)

## My Issue/Suggestion

I'm reading this page again and still finding it heavy going. 
In section 4.3.1 there are two tree diagrams and neither of them corresponds to the description.
In the first it says, "In this diagram you see that Git doesn’t know how to combine commits #3 and #5" but there is no revision #5.  It would appear this should refer to #4. 
In the second it says, "After solving any conflicts, you need to make a ‘merge commit’. This commit contains any changes that have happened during integration of remote changes into yours.".  The merge action and its corresponding commit is not shown and there is no revision #5.  
This topic is quite involved and having to interpolate what the author may have meant makes it even harder. 
As I have commented previously, the distinction between the working copy and the local repository gets lost in the description. 
Thanks for looking at this.

**Comment by MariaShaposhnikova** [comment]
Hi @Chris-Karona ,

Thanks a lot for your detailed feedback! 
We have addressed it in this PR: https://github.com/mendix/docs/pull/7700. We updated the information and images and we hope that the document is clearer now. 

Please let me know if you have any more suggestions for improving the version control documentation.

Best regards,
Maria
