### ISSUE TITLE
using-version-control-in-studio-pro

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#7359]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [using-version-control-in-studio-pro](https://docs.mendix.com/refguide/using-version-control-in-studio-pro/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md)

## My Issue/Suggestion
This paragraph in section 4.4 needs checking:
_For example, if the last time you pulled you received all changes up to and including revision N, this means that the original for your working copy is revision 40. Since you started making changes to your working copy, other people on your team have made another four commits (X, Y, and Z). If you now pull, you will receive those changes and Z will be the new original to which your changes are compared._
I assume "40" should read "N". 
I think it would be worth elaborating that "original" here means the version which is used for a three-way compare: my changes, their changes, original.
thanks
Chris

**Comment by MariaShaposhnikova** [comment]
Hi @Chris-Karona ,

Thank you for your feedback!

I've addressed your suggestion about explaining what "original" means within this PR: https://github.com/mendix/docs/pull/7696/, commit: https://github.com/mendix/docs/pull/7696/commits/c6193cc597866b638069cd3bf8cff98d923c8799
I did not use a three-way compare to define the term, but tried defining what the term means in general.

The information about the revision was corrected earlier, in this commit: https://github.com/mendix/docs/pull/7449/commits/95ef38c78a512a82215cbcc1e7a5ee808209c190

I hope these changes make the document clearer.

Cheers,
Maria
