### ISSUE TITLE
use-the-external-database-connector

### ISSUE THREAD

**Issue by speedlink1003** [mendix/docs#7376]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [use-the-external-database-connector](https://docs.mendix.com/howto/integration/use-the-external-database-connector/)

Document link: [use-the-external-database-connector.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/integration/use-the-external-database-connector.md)

## My Issue/Suggestion

Double quotes are currently not suppored as an parameter value. When trying to provide a double quote (") you receive a null pointer exeption regarding a currupt json structure.  You need to escape this charactar within the json generation of the parameters.

**Comment by quinntracy** [comment]
Hello, thanks for bringing this to our attention. We've updated the formatting of this example in the **Use the External Database Connector** doc to avoid confusion regarding the use of double quotes. The change can be seen in [this PR](https://github.com/mendix/docs/pull/7387).
