### ISSUE TITLE
Starting docker container fails -> npm run server fails

### ISSUE THREAD

**Issue by KevinVlaanderen** [mendix/docs#741]
"docker-compose build" and "docker-compose run app yarn" run successfully, but "docker-compose up" fails. Running on Mac OSx.

Seems like the node command has been changed from 'server' to 'serve'...

$docs git:(hybrid-release-notes) ✗ docker-compose up
Starting docs_app_1 ...
Starting docs_app_1 ... done
Attaching to docs_app_1
app_1  | yarn run v1.0.2
app_1  | warning package.json: License should be a valid SPDX license expression
app_1  | warning ../../../package.json: No license field
app_1  | error Command "server" not found. Did you mean "serve"?
app_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
docs_app_1 exited with code 1

After I change 'server' to 'serve' in the docker-compose.yml, I get the following:

$docs git:(hybrid-release-notes) ✗ docker-compose up
Recreating docs_app_1 ...
Recreating docs_app_1 ... done
Attaching to docs_app_1
app_1  | yarn run v1.0.2
app_1  | warning package.json: License should be a valid SPDX license expression
app_1  | warning ../../../package.json: No license field
app_1  | $ ./node_modules/.bin/gulp serve
app_1  | [20:01:49] Gulp started at 2017-09-24 20:01:49
app_1  | [20:01:49] Using gulpfile ~/docs/gulpfile.js
app_1  | [20:01:49] Starting 'serve'...
app_1  | [20:01:49] Starting 'clean'...
app_1  | [20:01:49] Finished 'clean' after 5.57 ms
app_1  | [20:01:49] Starting 'clean:css'...
app_1  | [20:01:49] Starting 'clean:js'...
app_1  | [20:01:49] Starting 'write:menu'...
app_1  | [20:01:49] Starting 'build:hugo'...
app_1  | [20:01:49] Finished 'clean:css' after 13 ms
app_1  | [20:01:49] Starting 'dev:sass'...
app_1  | [20:01:49] Finished 'clean:js' after 39 ms
app_1  | [20:01:49] Starting 'build:js'...
app_1  | [20:01:49] [HUGO] Started building sites ...
app_1  | [20:02:12] [MENU_BUILD] File /refguide4/certificates.md has category Deployment which has no file associated to it or is not used in spaces.yml
app_1  | [20:02:12] [MENU_BUILD] File /refguide4/monitoring.md has category Deployment which has no file associated to it or is not used in spaces.yml
app_1  | [20:02:12] [MENU_BUILD] File /refguide4/security-constraints-in-the-mendix-cloud.md has category Deployment which has no file associated to it or is not used in spaces.yml
app_1  | [20:02:12] [MENU_BUILD] File /refguide5/certificates.md has category Deployment which has no file associated to it or is not used in spaces.yml
app_1  | [20:02:12] [MENU_BUILD] File /refguide5/security-constraints-in-the-mendix-cloud.md has category Deployment which has no file associated to it or is not used in spaces.yml
app_1  | [20:02:12] [MENU_BUILD] File /refguide6/certificates.md has category Deployment which has no file associated to it or is not used in spaces.yml
app_1  | [20:02:12] [MENU_BUILD] File /refguide6/version-downgrade-prevention.md has category Deployment which has no file associated to it or is not used in spaces.yml
app_1  | [20:02:12] Finished 'write:menu' after 23 s
app_1  | [20:02:13] Finished 'build:js' after 24 s
app_1  | [20:02:13] Finished 'dev:sass' after 24 s
app_1  | [20:02:29] [HUGO] ERROR 2017/09/24 20:02:29 Error while rendering "page": template: theme/_default/single.html:1:3: executing "theme/_default/single.html" at <partial "header" .>: error calling partial: template: theme/partials/header.html:5:5: executing "theme/partials/header.html" at <partial "base/head" ...>: error calling partial: template: theme/partials/base/head.html:30:5: executing "theme/partials/base/head.html" at <partial "asset" (dic...>: error calling partial: template: theme/partials/asset.html:17:19: executing "theme/partials/asset.html" at <index $assetscss .fi...>: error calling index: index of untyped nil
app_1  | [20:02:29] Hugo exit code is 1, check your Hugo setup
app_1  | error Command failed with exit code 2.
app_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
docs_app_1 exited with code 1

**Comment by r0b1n** [comment]
Removing `node_modules` before running `docker-compose run app yarn` and updating [Hugo version](https://github.com/mendix/docs/blob/development/Dockerfile#L5) to `0.31.1` in Dockerfile fixed a similar issue for me.

I think in case of switching from the local setup to the setup in Docker you have to clean the `node_modules` as it contains binaries of a different platform (mac/windows).

**Comment by JelteMX** [comment]
Fixed the issues with Docker. You now only need `docker-compose build` and `docker-compose up`. No need to remove `node_modules` or anything, this is now done in the docker container itself (and if you do have this folder, it is mounted as an empty folder in the container).
