### ISSUE TITLE
import-and-export-apps-modules-widgets-and-documents

### ISSUE THREAD

**Issue by JKannon** [mendix/docs#7417]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [import-and-export-apps-modules-widgets-and-documents](https://docs.mendix.com/refguide9/import-and-export/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide9/modeling/import-and-export/_index.md)

## My Issue/Suggestion

I cannot import my scss file for my application using because the "Import Document from File" doesn't exist. The "Synchronize App Directory" option also doesn't work. I am using Mendix 9.12.1 because I am trying to complete the "Style your App with Sass" learning path.

**Comment by MarkvanMents** [comment]
Hi Jacob,
Thanks for raising this issue.
I've had a look at my version of 9.12.1 and **Import document from file…** is available to me. So it appears the documentation is correct.
![image](https://github.com/mendix/docs/assets/35492184/9a3f00ed-b4d5-4b4e-bc61-0ab3c94e645e)

If you can't see it, then it sounds like another issue. You can ask about this in [Community Questions](https://community.mendix.com/p/questions) or [raise a support ticket](https://support.mendix.com).

Hope you manage to resolve your issue.
Yours
Mark van Ments
