### ISSUE TITLE
run-a-mendix-docker-image

### ISSUE THREAD

**Issue by MXClyde** [mendix/docs#7424]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [run-a-mendix-docker-image](https://docs.mendix.com/developerportal/deploy/run-mendix-docker-image/)

Document link: [run-mendix-docker-image.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/docker-deploy/run-mendix-docker-image.md)

## My Issue/Suggestion

This page is outdated and should be deleted.

**Comment by katarzyna-koltun-mx** [comment]
@MXClyde Thank you for reaching out! I'll confirm with the dev team and make the update asap.

**Comment by katarzyna-koltun-mx** [comment]
Reached out to the Private Cloud team, but they're not aware of this article and only maintain Docker as needed. It seems that this is truly an orphaned old article that can be removed.

**Comment by katarzyna-koltun-mx** [comment]
@MXClyde After reviewing the files, I found that the Docker article is linked from this Minikube article: https://docs.mendix.com/developerportal/deploy/run-mendix-on-kubernetes/#deploy ("See [Run a Mendix Docker Image](https://docs.mendix.com/developerportal/deploy/run-mendix-docker-image/) for expected value formats."). Is the Minikube article also deprecated and should be deleted? Or should I take out the expected value formats and move them to the Minikube article?

**Comment by MXClyde** [comment]
IMHO we should also delete the Minikube article because keeping it gives the false impression that we somehow have prodcut support for Minikube....

**Comment by katarzyna-koltun-mx** [comment]
Would you happen to know who could help me verify that?

**Comment by katarzyna-koltun-mx** [comment]
If there is no owning team, I may want to delete it as well, but would prefer to check with the doc owners if there are any.

**Comment by MXClyde** [comment]
No, this is another orphaned article, there is no owning team (if there would, it would be Private Cloud).

**Comment by katarzyna-koltun-mx** [comment]
Got it. I'll handle all 3 then. I'll create a PR for all 3 articles in the node.

**Comment by katarzyna-koltun-mx** [comment]
https://github.com/mendix/docs/pull/7459 Here's the PR. I reached out to Carlos per Mark's suggestion, but hopefully there won't be any concerns from him either. The PR is ready to merge.
