### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by MXClyde** [mendix/docs#7425]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [docker](https://docs.mendix.com/developerportal/deploy/docker-deploy/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/docker-deploy/_index.md)

## My Issue/Suggestion

This section is outdated and should be deleted.

**Comment by katarzyna-koltun-mx** [comment]
See related issue https://github.com/mendix/docs/issues/7424 for resolution.
