### ISSUE TITLE
use-docker-with-minikube

### ISSUE THREAD

**Issue by MXClyde** [mendix/docs#7426]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [use-docker-with-minikube](https://docs.mendix.com/developerportal/deploy/run-mendix-on-kubernetes/)

Document link: [run-mendix-on-kubernetes.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md)

## My Issue/Suggestion

This page is outdated and should be deleted.

**Comment by katarzyna-koltun-mx** [comment]
See related issue https://github.com/mendix/docs/issues/7424 for resolution.
