### ISSUE TITLE
ats

### ISSUE THREAD

**Issue by goodconcepts** [mendix/docs#7427]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [ats](https://docs.mendix.com/appstore/partner-solutions/ats/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/partner-solutions/ats/_index.md)

## My Issue/Suggestion
If ATS is not offered as a license anymore what tools does Mendix offer to automate regression testing?

**Comment by MarkvanMents** [comment]
Hi Denise,
Thank you for your question.
I have spoken to the product manager and they are currently looking for a good alternative to ATS. Unfortunately, this is still ongoing so I can't give you a specific replacement which has all the features of ATS.
There are other testing modules for Mendix, such as the ones mentioned in the blogpost [Three tools to test your Mendix application](https://www.mendix.com/blog/three-tools-to-test-your-mendix-application/) but I appreciate that they are not one-for-one replacements for ATS.
You can also ask the [Mendix community](https://community.mendix.com/p/questions) where there are many experienced developers who will have experience of regression testing with Mendix.
Keep an eye on the Marketplace and the documentation and any new Mendix-supported testing tools will be published there.
Thanks for getting in touch.
Yours
Mark van Ments
