### ISSUE TITLE
Add Gradle Networking Requirements

### ISSUE THREAD

**Issue by cdcharlebois** [mendix/docs#7435]
I believe that the use of managed dependencies with version 10.3+ also requires Studio Pro to be able to access the following URLs (to fetch managed dependencies)

```
repo.maven.apache.org
plugins.gradle.org
jcenter.bintray.com
plugins-artifacts.gradle.org
```

This should be added to the documentation, either under system requirements with the other URLs that need to be whitelisted in system requirements [here](https://docs.mendix.com/refguide/system-requirements/#firewall-settings) or with the managed dependencies docs [here](https://docs.mendix.com/refguide/managed-dependencies/#5-migrating-from-unmanaged-to-managed-dependencies)

This issue has come up with multiple customers recently and should be added to the docs.

**Comment by MarkvanMents** [comment]
Hi Connor,
This information is already in our documentation here: https://docs.mendix.com/refguide/managed-dependencies/#8-troubleshooting
And is being rewritten in #7343
I'll pick this up on your PR #7436
