### ISSUE TITLE
workflow-elements

### ISSUE THREAD

**Issue by g-kamesh** [mendix/docs#7522]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [workflow-elements](https://docs.mendix.com/refguide/workflow-elements/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/workflows/workflow-elements/_index.md)

## My Issue/Suggestion

User Tasks and System Actions are showing the same elements ie. call microflow, call workflow
User Tasks need to show Multi-user task and User Task

Documentation mistake in the page, please look into this
PFB, the screenshots for the same.

![image](https://github.com/mendix/docs/assets/88446709/faedabf0-9d95-4852-819e-a8ecfc83d19b)
![image](https://github.com/mendix/docs/assets/88446709/40a8305a-c626-43f0-9cda-a3ca3c966265)

**Comment by Yiyun333** [comment]
Hi @g-kamesh,

That's a great catch! Thanks for pointing this out!

I've made the correction in this PR: https://github.com/mendix/docs/pull/7528. The changes will be online by the end of the day.

I am closing this issue now. If you have any further feedback, feel free to let us know.

Kind regards,
Yiyun
