### ISSUE TITLE
Wrong link was configured in 3D Viewer API

### ISSUE THREAD

**Issue by DISW-Mendix-3DViewer** [mendix/docs#7567]
HI, 
Actually the first link below is wrong
https://github.com/mendix/docs/blob/c51c24da7f500d1e66180397045169d7396f4e1e/content/en/docs/partners/siemens/3d-viewer/3d-viewer-api.md?plain=1#L81

 it should be [3D Viewer API Reference] (https://d102io3ppw18a6.cloudfront.net/)

**Comment by Luyao-Zhang-1** [comment]
Hi @digital-engineering-services-sample-app ,

Thank you for spotting this! I updated the URL in [PR](https://github.com/mendix/docs/pull/7584). This update should be published before next week. 
Enjoy your weekend!

Luyao
