### ISSUE TITLE
using-eclipse

### ISSUE THREAD

**Issue by CrisLange** [mendix/docs#7570]
Missing base classes for com.mendix
![afbeelding](https://github.com/mendix/docs/assets/84906873/79f6009e-4719-4cee-88ad-1a234beaeaaf)

What are the correct settings for Eclipse??? Nowhere to be found in Mendix documentation!!!

**Comment by MarkvanMents** [comment]
Hi,
I'm not sure that I have understood your question fully. You can add a Java action to Mendix and edit it in Eclipse without importing any additional classes. Any classes you import will depend on what your Java action is going to do.

You can see a couple of examples in [Extending Your Application with Custom Java](https://docs.mendix.com/refguide/extending-your-application-with-custom-java/) - the first does not require any classes to be imported. The second just imports the classes which are being used within the Java action. I have had the steps in this document tested and they worked for a new installation of Eclipse if you use the method described in that document to import the project into Eclipse.

If this still doesn't work for you, I suggest you ask on [Community Questions](https://community.mendix.com/p/questions) where there are many Mendix developers who may have come across similar issues and can share their experiences.

I'm sorry you have had this issue - if you resolve the issue and identify something which would have helped you, please let us know and we can add it to the documentation.
Yours
Mark van Ments
