### ISSUE TITLE
Missing options in preferences

### ISSUE THREAD

**Issue by BartLuijtenMx** [mendix/docs#7613]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [preferences](https://docs.mendix.com/refguide/preferences-dialog/)

Document link: [preferences-dialog.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md)

## My Issue/Suggestion

In paragraph 6, the two bottom options on the dialog are missing, see screenshot.

![Screenshot 2024-04-17 105547](https://github.com/mendix/docs/assets/7405062/f4643529-efe9-4823-9f45-57f4e43fb975)

**Comment by quinntracy** [comment]
@BartLuijtenMx Thank you for flagging this. Additional information regarding these options have been added to the document, as seen in [this PR](https://github.com/mendix/docs/pull/7629).
