### ISSUE TITLE
ml-model-mapping is not in beta anymore

### ISSUE THREAD

**Issue by dlhartveld** [mendix/docs#7699]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [ml-model-mapping](https://docs.mendix.com/refguide/ml-model-mapping/)

Document link: [ml-model-mapping.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/integration/ml-model-mapping.md)

## My Issue/Suggestion

Remove 'beta' warning as this has become GA with Mendix 10.0.

**Comment by quinntracy** [comment]
Thanks for flagging this, @dlhartveld. I have removed the alert from the doc.
