### ISSUE TITLE
advanced-custom-settings-in-mendix-runtime

### ISSUE THREAD

**Issue by milu777** [mendix/docs#7726]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [advanced-custom-settings-in-mendix-runtime](https://docs.mendix.com/refguide/tricky-custom-runtime-settings/)

Document link: [tricky-custom-runtime-settings.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/runtime/custom-settings/tricky-custom-runtime-settings.md)

## My Issue/Suggestion
The description "Set the log level of the ConnectionBus_Queries log node to TRACE to show more information about the page or the microflow that leads to this query." gives the customer the wrong expectation that it will tell them which page/microflow is running a long query. 
Actually, the TRACE level logging for ConnectionBus_Queries primarily focuses on the SQL queries themselves rather than pinpointing the exact microflow or page. Therefore, even with the increased verbosity, you won’t see direct references to specific microflows or pages in the logs. Optimizing database queries involves a combination of code analysis, database design, and performance tuning. 
The related ticket is https://mendixsupport.zendesk.com/agent/tickets/215823

**Comment by MarkvanMents** [comment]
Changes made and approved.
Thanks for raising the issue.
