### ISSUE TITLE
oql-parameters

### ISSUE THREAD

**Issue by lordlothar99** [mendix/docs#7840]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [oql-parameters](https://docs.mendix.com/refguide9/oql-parameters/)

Document link: [oql-parameters.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide9/modeling/resources/data-sets/oql/oql-expressions/oql-parameters.md)

## My Issue/Suggestion
provide examples with java for each supported type ; especially using IN operator

**Comment by MarkvanMents** [comment]
Hi François,
Sorry about the delay in getting back to you.
Thanks very much for your suggestion. I have been trying to find time in the developers' schedule to get some input into creating examples of OQL.
You will be pleased to hear that have embarked on a project to substantially improve the OQL documentation altogether and provide a lot more examples and other information about OQL. You should see some improvements in a few weeks time.
Please let us know if you see any other areas for improvement in the OQL documentation once this first pass has been complete.
Thanks again for your suggestion for making the Mendix documentation better.
Yours
Mark van Ments
