### ISSUE TITLE
My first pluggable widget breaks as soon as I add <systemProperty key="Label" />

### ISSUE THREAD

**Issue by GielAmsterdam** [mendix/docs#7912]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [build-a-pluggable-web-widget-part-1](https://docs.mendix.com/howto/extensibility/create-a-pluggable-widget-one/)

Document link: [create-a-pluggable-widget-one.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-one.md)

## My Issue/Suggestion
I am following https://docs.mendix.com/howto/extensibility/create-a-pluggable-widget-one to build my firtst widget, but as soon as I add <systemProperty key="Label" /> to the widget xml the properties “class” and “style” are removed from the generated interface “TextBoxContainerProps” and an error appears in Textbox.tsx and TextInput.tsx:

"Type 'Element' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>>'."

I have followed the instructions from "create-a-pluggable-widget-one" and removed the lines style={props.style} and className={props.class} from TextBox.tsx, so the export function in Textbox.tsx looks like:

export function TextBox(props: TextBoxContainerProps): ReactElement {
    const value = props.textAttribute.value || "";
    return <TextInput value={value} tabIndex={props.tabIndex} />;
}

However, this doesn't solve the issue. I have also removed the style and className references in TextInput.jsx, with no result. Something goes wrong when I add systemProperty key="Label" /> to the widget properties. Please update the page andor let me know how to solve this and add a label to my widget.

Thanks.

**Comment by GielAmsterdam** [comment]
Dear @ConnorLand, I have posted this problem on the Mendix Forum a and got a good answer from someone from the community a couple of weeks ago. Maybe his answer is helpfull to you. https://community.mendix.com/link/space/widgets/questions/136642

**Comment by ConnorLand** [comment]
@weirdwater can you confirm if our recent [pluggable widget doc upgrades](https://github.com/mendix/docs/pull/8044) addressed these issues?

**Comment by weirdwater** [comment]
Hi @GielAmsterdam, sorry to hear you ran into this bug.

To resolve this issue in your widget, please add `"@types/react": "^18.2.0"` to your overrides (npm) or resolutions (yarn). You may need to delete your `package-lock.json` and `node_modules` for the changes to take effect, as overrides/resolutions are applied during install.

The reason why this bug occurs is that with a recent release of the pluggable widgets tools [(10.7.2)](https://github.com/mendix/widgets-tools/releases/tag/untagged-d2fa01994baf19413d75) we upgraded the dependency on the [mendix package](https://www.npmjs.com/package/mendix). This includes a different version of `@types/react`, which causes Typescript to use different definitions, leading to the confusing error ReactElement is not assignable to ReactElement.

To avoid this issue in new widgets, we released a new version of [the widget generator](https://www.npmjs.com/package/@mendix/generator-widget) (10.7.3) that [sets the overrides/resolutions for you](https://github.com/mendix/widgets-tools/pull/97).

**Comment by GielAmsterdam** [comment]
Thanks @weirdwater
