### ISSUE TITLE
My part 1 pluggable widget doesn't include a render function wich is required by part 2.

### ISSUE THREAD

**Issue by GielAmsterdam** [mendix/docs#7913]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [build-a-pluggable-web-widget-part-2-advanced](https://docs.mendix.com/howto/extensibility/create-a-pluggable-widget-two/)

Document link: [create-a-pluggable-widget-two.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md)

## My Issue/Suggestion
I cannot continue with the following instruction because my widget doesn't include a render function:

"In TextBox.tsx, replace the render function with the code below to check if the input should be disabled and pass it to in the TextInput component:"

I think the first part course uses function architecture and the second part course uses component architecture.

Please update the instructions.

**Comment by ConnorLand** [comment]
Hello @GielAmsterdam ,

Thank you for this feedback. The developers have updated the code that you mentioned, and the documentation has also been updated (as you can [see here](https://github.com/mendix/docs/pull/8044/files)). We hope this change in product and documentation accelerates your development.

Thank you for your improvement suggestion,

Connor
