### ISSUE TITLE
Please add detail information at licensing-apps (2 Obtaining a Mendix License 2 Fill in the basic information, such as app name and hosting type.)

### ISSUE THREAD

**Issue by TakehikoKomatsu** [mendix/docs#7925]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [licensing-apps](https://docs.mendix.com/developerportal/deploy/licensing-apps-outside-mxcloud/)

Document link: [licensing-apps-outside-mxcloud.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/deploy/general/licensing-apps-outside-mxcloud.md)

## My Issue/Suggestion

In particular, I understood that the information at [https://docs.mendix.com/developerportal/deploy/licensing-apps-outside-mxcloud/#get-license](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.mendix.com%2Fdeveloperportal%2Fdeploy%2Flicensing-apps-outside-mxcloud%2F%23get-license&data=05%7C02%7Ctakehiko.komatsu%40siemens.com%7C1d9cc300c281407f253f08dc91c9329b%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C638545540554537731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=iDvXKJeUsuPXvsqvV9ZW1cDze6hf%2FaqZqqWgNmxdLAI%3D&reserved=0) is important.
If possible, it would be helpful if you could add details to the Mendix Docs, such as screenshots of "2. Fill in the basic information, such as app name and hosting type.", which is described there.
I think that this will make the Mendix Docs even easier to understand in the future.

**Comment by dbreseman** [comment]
Hi @TakehikoKomatsu, thanks for the suggestion and for getting in touch to improve the docs. I made some text adjustments to this document, and I'll keep an eye out for further feedback in case there is any confusion about the licensing process.
