### ISSUE TITLE
build-a-todo-example-extension

### ISSUE THREAD

**Issue by nathan-JJRplus** [mendix/docs#8032]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [build-a-todo-example-extension](https://docs.mendix.com/apidocs-mxsdk/apidocs/extensibility-api/extensibility-api-howtos/build-todo-example-extension/)

Document link: [build-todo-example-extension.md](https://github.com/mendix/docs/blob/development/content/en/docs/apidocs-mxsdk/apidocs/extensibility-api/extensibility-api-howtos/build-todo-example-extension.md)

## My Issue/Suggestion

1. Paragraph 5 code opening bracket should be below the class declaration instead of below the namespace.
2. Paragraph 8 code change MenuBarExtension to MenuExtension
3. Paragraph 8 code change MenuItemViewModel to MenuViewModel
4. Paragraph 8 code return statement is also wrong, working solution:
``` 
public override IEnumerable<MenuViewModel> GetMenus()
{
    yield return new MenuViewModel(
        "To Do List",
        () => _dockingWindowService.OpenPane(ToDoListDockablePaneExtension.PaneId)
    );
}
```

**Comment by Luyao-Zhang-1** [comment]
@nathan-JJRplus  Thank you so much for reporting these issues to us. We updated the doc [here](https://github.com/mendix/docs/pull/8038/files). 
If you find any other issues in the future, please feel free to contact us again! Thanks for helping us improve our documentation!
