### ISSUE TITLE
build-a-todo-example-extension

### ISSUE THREAD

**Issue by auraqadge** [mendix/docs#8039]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [build-a-todo-example-extension](https://docs.mendix.com/apidocs-mxsdk/apidocs/extensibility-api/extensibility-api-howtos/build-todo-example-extension/)

Document link: [build-todo-example-extension.md](https://github.com/mendix/docs/blob/development/content/en/docs/apidocs-mxsdk/apidocs/extensibility-api/extensibility-api-howtos/build-todo-example-extension.md)

## My Issue/Suggestion
The code block for ToDoListDockablePaneViewModel.cs has a misplaced { 

Have created #8036 pull request for this.

Also, the page references MenuBarExtension which does not appear to be part of the API at this time (at least not that I can see in 10.12.0 or the documentation) - If you convert it to MenuExtension and modify the code a bit then it works fine. 

Have created #8038 pull request for this.

Cheers

**Comment by Luyao-Zhang-1** [comment]
@auraqadge Thank you very much for sharing your suggestion and sending us two PRs. We have approved and merged the PRs.

If you find any other issues in the future, please feel free to contact us again! 
Thanks a lot for helping us improve our documentation!
