### ISSUE TITLE
mxbuild

### ISSUE THREAD

**Issue by tieniber** [mendix/docs#8160]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [mxbuild](https://docs.mendix.com/refguide/mxbuild/)

Document link: [mxbuild.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/general/mxbuild.md)

## My Issue/Suggestion

The command line option --gradle-home is not documented but is part of mxbuild.

**Comment by quinntracy** [comment]
Thanks for the feedback, @tieniber. I've added this information in the MxBuild doc, as seen in [this PR](https://github.com/mendix/docs/pull/8188).
