### ISSUE TITLE
jira

### ISSUE THREAD

**Issue by eh-kppi** [mendix/docs#8252]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [jira](https://docs.mendix.com/developerportal/project-management/jira-connector/)

Document link: [jira-connector.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/project-management/jira-connector.md)

## My Issue/Suggestion
There are no screenshots, demo videos, examples or anything visual to help me understand what the integration does, how it looks or acts in either Jira or Mendix. I can't find a YouTube video, demo, or anything that has some practical visuals or examples of the Jira connector.

**Comment by Luyao-Zhang-1** [comment]
Hi @eh-kppi  Thanks for your feedback! Would it be helpful if we add a screenshot to show what happens when you click **Jira** in the **Apps** navigation pane here?

![image](https://github.com/user-attachments/assets/7e783ea0-302c-42a8-bc45-6d855d8077a5)

**Comment by Luyao-Zhang-1** [comment]
I’ll close this issue since we haven’t received a response from the user.
