### ISSUE TITLE
mendix-best-practices-for-development

### ISSUE THREAD

**Issue by MickBelker** [mendix/docs#8322]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [mendix-best-practices-for-development](https://docs.mendix.com/refguide/dev-best-practices/)

Document link: [dev-best-practices.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/dev-best-practices.md)

## My Issue/Suggestion

In German, 3.6.1 Layouts und Snippets, translations for prefixes are

- not useful, should be language independent¨
- wrong, e.g. "tablette" for "tablet" is really funny.
I suggest to exclude prefixes from translations, keeping it in English.

**Comment by Luyao-Zhang-1** [comment]
@MickBelker Thank you for your valuable suggestions! I will update our glossary to ensure these prefixes are excluded from translation. I'll get back to you once it's fixed.

**Comment by Luyao-Zhang-1** [comment]
We fixed the translations of [these prefixes](https://docs.mendix.com/refguide/dev-best-practices/#layouts-and-snippets). Now they should remain untranslated in the German version.

Thank you again for the feedback! If you see anything in our documentation that can be improved in the future, please reach out to us again!
