### ISSUE TITLE
mx-model-reflection

### ISSUE THREAD

**Issue by masebok** [mendix/docs#8324]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [mx-model-reflection](https://docs.mendix.com/appstore/modules/model-reflection/)

Document link: [model-reflection.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/use-content/modules/model-reflection.md)

## My Issue/Suggestion
Section 2.2 states:
Date attribute:
Pattern: MM/dd/yyyy
Value: 2nd of July 2016
Result: 7/6/2016

The value ("2nd") doesn't reflect the Result (which is the 6th)

**Comment by MarkvanMents** [comment]
Hi @masebok 
Thanks for pointing out this error. The other examples don't look great either, so I have worked with the developers to correct them in #8350.
Thanks for taking the trouble to get in touch and help us improve the Mendix documentation.
Yours
Mark van Ments
