### ISSUE TITLE
jira

### ISSUE THREAD

**Issue by JKGHPO** [mendix/docs#8357]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [jira](https://docs.mendix.com/developerportal/project-management/jira-connector/)

Document link: [jira-connector.md](https://github.com/mendix/docs/blob/development/content/en/docs/developerportal/project-management/jira-connector.md)

## My Issue/Suggestion

This Integration has some flaws, that need to be solved to make it actually functional.

https://community.mendix.com/link/space/connectors/ideas/4751

The suggestion for "team managed boards" to move the backlog doesn't actually solve the issue, as it also shows completed issues that clog up Mendix Studio Pro, unless you also say they need to move away everyt singel story that isn't in the current sprint (backlog, upcoming sprints, and completed items too), which isn't practical solution really.

So it would need to basically say, "this doesn't work for Team Managed Board", until it gets fixed?

**Comment by MarkvanMents** [comment]
Hi there,
Thanks for your feedback.
I note that you have raised am idea on Mendix Community which is definitely the right way to report issues and suggest improvements.
I have asked the developers what they feel is an appropriate addition to the documentation to clarify any additional [limitations](https://docs.mendix.com/developerportal/project-management/jira-connector/#limitations) that should be added to the documentation. I will update the documentation when they get back to me.
Thanks for wanting to make the documentation better and help other members of the Mendix community.
Yours
Mark
