### ISSUE TITLE
oql-select-clause

### ISSUE THREAD

**Issue by aintJoshinya** [mendix/docs#8362]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [oql-select-clause](https://docs.mendix.com/refguide/oql-select-clause/)

Document link: [oql-select-clause.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/resources/data-sets/oql/oql-select-clause.md)

## My Issue/Suggestion
Provide more details around valid Asterisk (\*) usage. simple queries like "SELECT MyFirstModule.Test.* FROM MyFirstModule.Test" will throw an error in a dataset, "All columns of the first select query must be a simple name or have an alias"

**Comment by MarkvanMents** [comment]
Hi Joshua,
Thank you very much for your suggestion for improving the Mendix documentation.
We are currently starting a full review of the OQL documentation as we have identified that customers find OQL difficult to use and there are significant gaps in the documentation.
I have therefore fed your suggestion into the review process and you should, hopefully, see improvements to the OQL documentation over the next couple of months.
I will close this issue, but please do let us know in a couple of months if the improved OQL documentation has not materialized or still has gaps which need to be filled.
Yours
Mark
