### ISSUE TITLE
build-api - German headline "API erstellen" is misleading

### ISSUE THREAD

**Issue by MickBelker** [mendix/docs#8363]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [build-api](https://docs.mendix.com/apidocs-mxsdk/apidocs/build-api/)

Document link: [build-api.md](https://github.com/mendix/docs/blob/development/content/en/docs/apidocs-mxsdk/apidocs/build-api.md)

## My Issue/Suggestion

From a training
  https://academy.mendix.com/link/modules/662/lectures/5112/5.3-Automation-with-Your-CI/CD-Tool-Approach
I was following the "Build" link.
Ending up in a page with headline "API erstellen" (german), which means "Create an API", is confusing.
All other pages in that area have the API name as headline, I would expect untranslated "Build API" as a non-translated name.

Btw., the 1st sentence on the page is correct, not translating "Build API":
"Mit der Build- API können Sie Bereitstellungspakete verwalten"

Kind regards,
  Michael

**Comment by Luyao-Zhang-1** [comment]
Hi @MickBelker thank you for reporting this issue. I will update our glossary to ensure this word is excluded from translation. I'll let you know once it's fixed.

**Comment by Luyao-Zhang-1** [comment]
Hi @MickBelker ,

Now "Build API" is excluded from being translated in the documentation. If you visit the [doc](https://docs.mendix.com/apidocs-mxsdk/apidocs/build-api/) again, you should be able to see that "Build API" remains untranslated in the German version. Thank you for giving us your feedback. If you see anything in our documentation that can be improved in the future, do not hesitate to reach out to us again!

Best regards,
Luyao
