### ISSUE TITLE
administrator

### ISSUE THREAD

**Issue by mxcrawford** [mendix/docs#8381]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [administrator](https://docs.mendix.com/refguide/administrator/)

Document link: [administrator.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/security/app-security/administrator.md)

**Comment by MarkvanMents** [comment]
Have tried to engage over Slack as discussion is easier there.
Will close this issue for now and continue discussions over Slack.
