### ISSUE TITLE
share-the-development-database

### ISSUE THREAD

**Issue by lukastom** [mendix/docs#8408]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [share-the-development-database](https://docs.mendix.com/howto/data-models/sharing-the-development-database/)

Document link: [sharing-the-development-database.md](https://github.com/mendix/docs/blob/development/content/en/docs/howto/data-models/sharing-the-development-database.md)

## My Issue/Suggestion

This sentence "Copy the data directory to the data directory in the deployment directory." is not clear. Does it mean that we should:

1. put data in data so the result will be deployment/data/data?
2. copy new data to the place where old data folder is and overwrite all and leave other files intact (like .policy)?
3. should we basically delete all files in old data and replace by files from new data, is this the meaning?

**Comment by MarkvanMents** [comment]
Hi Lukáš,
Thanks for raising the issue on this document. It does, indeed, seem a bit unclear and I have a planned update to the documentation in PR #8444. Basically, the files in the data directory of the zipped database should replace the files in the deployment/data directory.
Either option 2 or 3, above, should work. The `.policy` file is not needed, it was used a long time ago when Mendix used Java security manager, but has not been used in the last few major versions of Mendix and is not needed. If it is there it will be ignored. It is planned that it will be completely removed in a future version of Mendix.

Thanks again for taking the time to help improve our documentation.
Yours
Mark van Ments.
