### ISSUE TITLE
Document templates not visible in Studio Pro 10.15 for Mac

### ISSUE THREAD

**Issue by leasytime** [mendix/docs#8435]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [document-templates](https://docs.mendix.com/refguide/document-templates/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/resources/document-templates/_index.md)

## My Issue/Suggestion
The document templates do not show as resources in Studio Pro 10.15 for Mac. The generate document microflow action is also not visible.

**Comment by MarkvanMents** [comment]
Hi
I'm afraid that is a [current limitation](https://docs.mendix.com/refguide/system-requirements/#mac-limitations) of the Mac version of Studio Pro. The development team is actively working on bringing feature parity to the Mac and Windows versions of Studio Pro but document templates are still in development.
I'm afraid I do not have a date when they expect to deliver this feature.
Yours
Mark van Ments
