### ISSUE TITLE
delete-objects

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#8531]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [delete-objects](https://docs.mendix.com/refguide/deleting-objects/)

Document link: [deleting-objects.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/object-activities/deleting-objects.md)

## My Issue/Suggestion

Right near the end in section 6.2.3 (5) it says: 
"Marks the object as deleted in the offline database, which makes it possible to synchronize the deletion with the server."

I feel it would be helpful to be explicit about how this is 'possible'.  I assume the only way to sync the deletion is by a "Sync Everything" or a "Sync Unsynced".  Working on a large system we tend to avoid these actions and stick to targeted syncs using "Sync Selected" to have better control. I realise that this won't be an issue for everyone but if my understanding is correct it wouldn't hurt to add this detail, perhaps like this: 
"Marks the object as deleted in the offline database, which makes it possible to synchronize the deletion with the server using Sync Unsynced or Sync Everything." 

thanks

Chris

**Comment by Yiyun333** [comment]
Hi @Chris-Karona,

Thanks a lot for your feedback! I've verified your feedback with the internal team and created a PR to apply your suggestion. 
I'll merge the PR soon. The changes will be online by the end of the day. I'll close the issue soon as well. Thanks again for your contribution!

Best,
Yiyun

**Comment by Chris-Karona** [comment]
Yiyun - thanks :)
