### ISSUE TITLE
module-commands

### ISSUE THREAD

**Issue by tswarmerdam-mx** [mendix/docs#8545]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [module-commands](https://docs.mendix.com/refguide/mx-command-line-tool/module/)

Document link: [module.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/general/mx-command-line-tool/module.md)

## My Issue/Suggestion
The line below [chapter 3](https://docs.mendix.com/refguide/mx-command-line-tool/module/#set-module-version) is confusing and probably wrong: The mx _**set**_-module-version command **_outputs_** the version of a module.

**Comment by quinntracy** [comment]
Hi @tswarmerdam-mx , thanks for pointing this out. I have revised the description of the set-module-version command in [this PR](https://github.com/mendix/docs/pull/8722).
