### ISSUE TITLE
marketplace

### ISSUE THREAD

**Issue by Rob-de-Leeuw** [mendix/docs#8559]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [marketplace](https://docs.mendix.com/appstore/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/_index.md)

## My Issue/Suggestion
It would be great if this chapter can mention that you should never delete a Marketplace module and reinstall it if it has associations to other parts of your app. We recently had a case were data was lost, that could have been avoided if the risk of deleting/reinstalling is explained.

Thanks

**Comment by Luyao-Zhang-1** [comment]
@Rob-de-Leeuw  Thank you for reaching out to us. 

As mentioned in the [warning](https://docs.mendix.com/appstore/use-content/#deleting-marketplace-content-from-your-app) in the documentation, deleting a Marketplace module can result in data loss, which seems to be what happened here.

Thanks for your feedback. We will review the doc to see if we can make this warning more prominent.
