### ISSUE TITLE
offline-synchronization

### ISSUE THREAD

**Issue by Chris-Karona** [mendix/docs#8563]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [offline-synchronization](https://docs.mendix.com/refguide/mobile/building-efficient-mobile-apps/offlinefirst-data/synchronization/)

Document link: [synchronization.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/mobile/building-efficient-mobile-apps/offlinefirst-data/synchronization.md)

## My Issue/Suggestion
In Section 2.4 there is an image of the 'Customize offline synchronization' dialogue.  Could we please have an explanation of why some entries are in bold font and others are not.

**Comment by ConnorLand** [comment]
Hi @Chris-Karona ,

I believe it's merely that if you change the Synchronization mode, then the product emboldens your drop-down choice. If you leave it as the default option, it is not bolded.

This is a UI feature of the product, so we typically do not document those behaviors on our website. 

Do you have any other questions I can help with?

Connor

**Comment by Chris-Karona** [comment]
Hi Connor, 
Well, I'm not sure. I do see that if I change a setting that is not bold, it then goes bold but I think the default option is always "All Objects" and I see some entries that have "Nothing (clear data)" and are not bold.  So I'm not sure that's what it is.  
If it was always bolded for anything other than "All Objects" that would sort of make sense except that in large apps this is the most dangerous option because we have seen cases where the default setting for an entity hadn't been changed and tens of thousands of objects were being synched which was making the app slow to open when a full sync is required.  I'd prefer the default to be "Nothing (clear data)" because you soon find out if that's not right for your app. 
Generally I agree it wouldn't be necessary to document UI features because they should be self-explanatory. But in this case it's not self-explanatory.  It might be better if the bolding wasn't present at all because it only seems to add confusion.  
However, it seems like this might fundamentally be a request to change the app rather than the documentation and I guess that's beyond your remit.
At least I know now that I'm not missing some useful insight into the sync configuration.
Kind regards
Chris

**Comment by ConnorLand** [comment]
Hmm, I see your point. 

I am investigating this behavior, and I will see if we can add some clarity. Because indeed, as you say, we don't want any confusion on this.

Thanks,

Connor

**Comment by ConnorLand** [comment]
Hi again,

I think I've found the answer after searching "synchronization" and "bold" into our site search.

The sync options which have be changed by the dev are in bold. This includes new entities made in the Custom Synchronization dialog, because by definition they have been changed (made) by a Mendix dev: https://docs.mendix.com/refguide/navigation/#customize

Because this is a product UI issue, the best way to get this clarified is actually through a Support ticket. May I ask that you please [raise a Support ticket](https://support.mendix.com/hc/en-us/requests/new), explain how the bolding/non-bolding is confusing and unexplained in the product, and then request a designer to look at the issue?


Connor

**Comment by Chris-Karona** [comment]
Connor
Well done for finding that reference.  I had a vague idea that I had seen something somewhere about it but I was looking in the wrong place. 
So you were right, bold indicates that a setting has been changed from its default (although I'm not sure that this is particularly useful information for the developer to know). 
What I hadn't realised is that the default is not always "All Objects". Looking at the exceptions in my model they seem to be entities that are created but never _retrieved_ in the native UI. 
On balance, I don't think that there is a strong case to change the behaviour and it seems unlikely that it would ever make it to the top of the backlog.  
I do think that it's worth repeating that bit of text into this page (offline-synchronization) though, soemething like: 
"For each entity the default download setting is automatically determined by analyzing the model, but it can be overridden by the devloper, in which case the setting will appear in boldface.".  
I think that would avoid the potential for confusion. 
Thanks for looking at this and pursuing it to a conclusion. 
Best regards
Chris

**Comment by ConnorLand** [comment]
I'll add that to the docs to make it clearer. Thanks Chris!
