### ISSUE TITLE
change-list

### ISSUE THREAD

**Issue by tswarmerdam-mx** [mendix/docs#8670]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [change-list](https://docs.mendix.com/refguide/change-list/)

Document link: [change-list.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/change-list.md)

## My Issue/Suggestion

At some point it was explained that changes in a list in a NANOFLOW do not reflect outside of that nanoflow. This is where the behaviour of a nanoflow is fundamentally different from a microflow regarding lists (call by value vs reference). I wanted to point out the piece of documentation that describes this but I cannot find it anymore today.

**Comment by Yiyun333** [comment]
Hi @tswarmerdam-mx,

Thanks for reaching out! This information is documented in the [Differences between Microflows and Nanoflows](https://docs.mendix.com/refguide/microflows-and-nanoflows/#differences) section: please see the second last point in the list.

It was moved from the [Nanoflows](https://docs.mendix.com/refguide/nanoflows/) page. So if you bookmarked this section before, you won't be able to find it using the old URL. 

I will also add a cross-reference to the [Nanoflows](https://docs.mendix.com/refguide/nanoflows/) page to point to this section, but the information you need is still not immediately visible. Have you tried our **Search** functionality at the top of the website? If you search "changes to a list in nanoflow", "change list sub-nanoflow", or just "list sub-nanoflow", you will find this information easily. If you've tried our search functionality but it didn't work for you, may I ask what words you used for searching? I might adjust our text to help find the relevant result.

Best,
Yiyun

**Comment by Yiyun333** [comment]
More discussions were followed on Slack :)
PR was created and merged: https://github.com/mendix/docs/pull/8678/files. 
I am closing this comment.
