### ISSUE TITLE
consume-a-rest-service

### ISSUE THREAD

**Issue by riesroovers** [mendix/docs#8685]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [consume-a-rest-service](https://docs.mendix.com/refguide9/integration/consume-a-rest-service/)

Document link: [consume-a-rest-service.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide9/modeling/integration/rest-services/consumed-rest-services/consume-a-rest-service.md)

## My Issue/Suggestion
- The content of the link in step 1 has changed and is different then the information displayed in the tutorial. This is confusing when trying to interpret the assignment. 
- Step 3 calls for selecting a 'Raw Data tab'. It is very confusing what is meant by this. Where do i find a 'Raw Data tab'? Is there a tab somewhere with a caption 'Raw Data'?

**Comment by sbont** [comment]
Thanks for logging this issue, Ries! Step 3 is indeed confusing; you're just supposed to copy the JSON data you see in your browser. "Raw Data" might be available in some browsers but isn't necessary here. I'll make sure to update the guide.
Regarding the data you see when you follow that URL: that is expected to be changing (as it's from Wikipedia); but I can see how this is adding more confusion than being helpful. I'll discuss if we should change or remove this instead.
