### ISSUE TITLE
import-excel-documents Download buttons are not working anymore?

### ISSUE THREAD

**Issue by mahendra-mahajan-mendix** [mendix/docs#8691]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [import-excel-documents](https://docs.mendix.com/refguide/importing-excel-documents/)

Document link: [import-excel-documents.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/integration/use-excel-documents/import-excel-documents.md)

## My Issue/Suggestion
Hello Docs team - the Download buttons are not working anymore. On clicking those Download buttons a magnified image of the button is shown, without actually downloading the sample file. Pls can you correct that in this document and anywhere else it might be happening. Thanks.
https://docs.mendix.com/refguide/importing-excel-documents/#creating

**Comment by quinntracy** [comment]
Hey @mahendra-mahajan-mendix , thanks for pointing this out. I have replaced the existing image with a button that can be clicked to download the Excel file in [this PR](https://github.com/mendix/docs/pull/8692). I will do the same with any other affected image links I see.
