### ISSUE TITLE
configuring-ci/cd-on-azure

### ISSUE THREAD

**Issue by jaspervanderhoek** [mendix/docs#8695]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [configuring-ci/cd-on-azure](https://docs.mendix.com/private-mendix-platform/configure-azure/)

Document link: [pmp-configure-azure.md](https://github.com/mendix/docs/blob/development/content/en/docs/private-platform/configuration/pmp-configure-azure.md)

## My Issue/Suggestion

Chapter 2. Configuring the pipeline, explains this: "If you have an Azure organization, you can set Azure as your CI System in Settings > DevOps > CI/CD."

Which settings is this referring to? I've looked in at least 5 different settings pages and nowhere is CI/CD an option to choose.

**Comment by katarzyna-koltun-mx** [comment]
@jaspervanderhoek Thank you for reporting the issue. The page has changed and is now located at the following path:

[Admin mode] > Settings > Build

![image](https://github.com/user-attachments/assets/dde44098-7006-423f-846e-14f102e861cd)

I will update the documentation accordingly.

**Comment by jaspervanderhoek** [comment]
Thanks for the quick response, I am still looking for this feature. Where would I enable this 'admin mode', I don't see this in my cluster. Where can that be found?

**Comment by katarzyna-koltun-mx** [comment]
@jaspervanderhoek Click on the user icon in the upper right corner of the screen, and then select "Switch to Admin Mode" from the list. You can switch back to normal user mode in the same way.

**Comment by katarzyna-koltun-mx** [comment]
https://docs.mendix.com/private-mendix-platform/reference-guide/common/navigation/#account

**Comment by jaspervanderhoek** [comment]
Thanks! Clear!
