### ISSUE TITLE
upgrade-a-solution

### ISSUE THREAD

**Issue by paul-moes-mendix** [mendix/docs#8708]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [upgrade-a-solution](https://docs.mendix.com/appstore/creating-content/sol-upgrade/)

Document link: [sol-upgrade.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/create-content/create-solutions/implement-solutions/sol-upgrade.md)

## My Issue/Suggestion

(via the feature flag). > this was Mendix 9 only. Feature flag is no longer needed

**Comment by katarzyna-koltun-mx** [comment]
@paul-moes-mendix Thank you for reporting the issue. I will look into it and update the documentation as required.

**Comment by katarzyna-koltun-mx** [comment]
@paul-moes-mendix I've created a PR for the change. Let me know if you have any comments: https://github.com/mendix/docs/pull/8710
