### ISSUE TITLE
version-control-menu

### ISSUE THREAD

**Issue by GG-O-BP** [mendix/docs#8754]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [version-control-menu](https://docs.mendix.com/refguide/version-control-menu/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/refguide/modeling/menus/version-control-menu/_index.md)

## My Issue/Suggestion

The Korean translation is so poor that it is impossible to read. Please make it easy to access the original text in German or English, even when accessing from Korea.

**Comment by MarkvanMents** [comment]
Hi,
Sorry to hear that your experience with the Korean translation of the website is so bad. Unfortunately, we are currently using machine translation to produce the Korean version, with all the limitations that imposes.
You should be able to return to the English or German version of the document using the switcher in the bottom right. We don't automatically turn on translation into any particular language based on your location or any other factor.
![image](https://github.com/user-attachments/assets/0a202b43-e9d6-4cff-9a53-034ec8180013)

Although we can't manually translate the whole document, if there is anything which is consistently badly/wrongly translated and would improve the document we can override this and try to make the translation better.

Thanks for letting us know your experience.
Yours
Mark van Ments
