### ISSUE TITLE
mendix-profile

### ISSUE THREAD

**Issue by MbM4G1C** [mendix/docs#8794]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [mendix-profile](https://docs.mendix.com/community-tools/mendix-profile/)

Document link: [_index.md](https://github.com/mendix/docs/blob/development/content/en/docs/community-tools/mendix-profile/_index.md)

**Comment by MarkvanMents** [comment]
Hi there,
I cannot see any information on the issue you have with the documentation. I will close this, but please raise another issue if you have a suggestion for improving the documentation.
