### ISSUE TITLE
combo-box

### ISSUE THREAD

**Issue by julisbf** [mendix/docs#8813]
Please use the form below, leaving the prefilled data to help us. Thank you.

Page link: [combo-box](https://docs.mendix.com/appstore/widgets/combobox/#properties-pane)

Document link: [combobox.md](https://github.com/mendix/docs/blob/development/content/en/docs/appstore/use-content/platform-supported-content/widgets/combobox.md)

## My Issue/Suggestion

I spotted a typo: the "L" in the word panel on the title and description is missing.

<img width="1134" alt="Screenshot 2024-12-20 at 11 45 59" src="https://github.com/user-attachments/assets/d08bb5ed-290f-4353-a020-429329aca9e7" />

**Comment by MarkvanMents** [comment]
Hi Juliana,
Thanks for raising an issue on the documentation.
This isn't a typo, it is the way we refer to parts of the Studio Pro interface. We use pane as in "window pane" to indicate an area of the Studio Pro interface.
You can see more information here: [Dockable Panes](https://docs.mendix.com/refguide9/studio-pro-overview/#panes).
Hope that makes sense to you.
Yours
Mark

**Comment by julisbf** [comment]
Thank you, Mark, for the explanation. I just learned something new :)
