### ISSUE TITLE
importing WSDL link

### ISSUE THREAD

**Issue by MirSultana** [mendix/docs#928]
Please add the documentation link (https://www.w3schools.com/xml/tempconvert.asmx?wsdl) on step 5 of https://docs.mendix.com/howto/integration/consume-a-simple-web-service#2-importing-a-wsdl

People are getting errors.

Thanks

**Comment by Adam-Dupaski** [comment]
Hi Sultana, I made the fix, thanks for telling me about the broken link. If you find any other problems with the documentation, feel free to contact me directly.
Cheers,
Adam

**Comment by MirSultana** [comment]
Thank you!
